### ISSUE TITLE
Discussion about the Chinese documents

### ISSUE THREAD

**Issue by sunny0826** [kubernetes-sigs/kustomize#1001]
I am a developer from China. kustomize is awesome. I hope to contribute Chinese documentation to make more Chinese developers use kustomize. what should I do?

**Comment by monopole** [comment]
That would be fantastic!

As a point of reference, https://kubernetes.io has its content stored [here](https://github.com/kubernetes/website/tree/master/content).  Immediately below this is `en`, `zh` etc.  It appears the `en` version is canonical, and is translated per [these instructions](https://kubernetes.io/docs/contribute/localization/).

Kustomize doesn't have such a fancy website.   There's https://kustomize.io, which is very nice but it's basically a fancy front door to this repo.  We don't have a formal content management system, with string identifiers and language injection.  We also don't have a decent means to forward users hitting links that no longer work because someone reorganized the docs.

Perhaps simply start by creating a new `zh` tree under `docs`?  Or a sibling directory `docs-zh` would be fine too.  I'd rather not change docs, as that would break links.

**Comment by sunny0826** [comment]
@monopole All right. I will creating a new ```zh-CN``` tree under ```docs```,  because I am using Simplified Chinese. First I will provide a translation of the ```README.md```.  Can I add a link to the main README ?
like 
![image](https://user-images.githubusercontent.com/24563928/56546120-2faa9700-65ac-11e9-80bd-8f185479bbc6.png)
or
![image](https://user-images.githubusercontent.com/24563928/56546139-3a652c00-65ac-11e9-8860-2c98fe27f205.png)
