### ISSUE TITLE
Pass Loader to Go plugins

### ISSUE THREAD

**Issue by jcassee** [kubernetes-sigs/kustomize#1018]
The `Loader` interface is useful for plugins to load files. It is used by the builtin `Files` and `EnvFiles` plugins.

I created [two external plugins](https://github.com/goabout/goabout-kustomize-plugins) that mimic these plugins but use [sops](https://github.com/mozilla/sops) to decrypt their content. It would be useful to be passed the Loader to those plugins too, so they can use the same security safeguards.

1. I could not find a way to get the current `LoadRestrictorFunc` to create a loader from `loader.NewLoader`. Did I miss it?
2. If not, could we add `Ldr ifc.Loader` to the `KVSource` struct, or pass it to `Get` in Go plugins?

**Comment by Liujingfang1** [comment]
The `loader` is passed to goplugins for [generators and transformer](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/plugins/loader.go#L86), but not for secret generator plugins. 
We should scandalize that for secret generator plugins.

**Comment by jcassee** [comment]
@Liujingfang1 Language barrier: what does "scandalize" mean in this context? :-)

**Comment by Liujingfang1** [comment]
My bad typing. I mean `standardize`.

**Comment by monopole** [comment]
The loader is now passed to all generator and transformer plugins.
it is not passed to KVSource plugins, which are going to be removed since we cannot have two plugin systems and since generator plugins are a superset of kvsource (configmap/secret) generators.

@jcassee see this example: https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/someteam.example.com/v1/secretsfromdatabase/SecretsFromDatabase.go
for migrating your KVSource plugin to the new generator framework.  Please advise if it makes sense.

See notes in https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins.md

Example of a loader being passed into Config:
https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/builtin/secretgenerator/SecretGenerator.go

We don't have an example of a loader being passed and used in a _user-authored_ plugin.

Wish we had one.

**Comment by jcassee** [comment]
@monopole Alright, makes sense.

I'm looking at the exec plugin to replace my KVSources plugins with. Is there an example using the exec plugin to generate ConfigMaps / Secrets with (the replacement for) `behavior: merge` somewhere?
