### ISSUE TITLE
Easy way to update the container image name

### ISSUE THREAD

**Issue by bickfordb** [kubernetes-sigs/kustomize#109]
In order to reduce copy and paste in large applications, it would be nice to be able to patch multiple resources with one patch via some kind of selector other than name.  For instance, in my  Kubernetes application, I have separate web and job pods that share the same Docker image, most of the same pod values which I need to copy and paste into each.  If one could write a patch that matched on a label or some other kind of selector, these shared values could be factored out.

**Comment by bickfordb** [comment]
Maybe this could mostly be accomplished by allowing the name field to be a regular expression?

**Comment by Liujingfang1** [comment]
The idea in #122 can help this. If kustomize provides to way to declare a user defined transformation and use that, this transformation can will be applied during `kustomize build`. To patch multiple objects with one patch, you only need to provide a proper transformer.

**Comment by itsnagaraj** [comment]
I love this idea/feature as well. I work on mono-repo project where we manage kubernetes spec for 30 microservice. We have templated everything in spec so that adding new service is a breeze. Templating logic is so complicated we have decided to move away from that approach and start evaluating tools like Kompose. Kompose doesn't fit for the project structure as the selector for deployment works by metadata->name and I will end up overlays for each service and lots of duplication

**Comment by nhoughto** [comment]
Does seem to make sense to be able to target resources with something other than name, label perhaps.  

The README relates kustomize to sed `it's like sed, in that it emits editted text.`, which is a great comparison, and is how i want it to work, but unless i'm missing something I can't use arbitrary values to target things for overlays? Name, label, or even just type would be great. I'd like to be as generic as possible.

**Comment by Liujingfang1** [comment]
Regardless of the patches or transformation. The original request is to ask an easy way to update the container image name wherever it is used.

**Comment by Liujingfang1** [comment]
@bickfordb What pod values you need to update? Can you give an example?

**Comment by pwittrock** [comment]
I think there are 2 issues here:

- Write patches that can match label / names
- Support a simple way to update images without a patch

**Comment by Liujingfang1** [comment]
> I think there are 2 issues here:
> 
> Write patches that can match label / names

This can be solved by #122 
> Support a simple way to update images without a patch

This is supported by `imageTags`. See the [imageTags demo](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/imageTags.m)

**Comment by bickfordb** [comment]
@Liujingfang1 are you particularly opposed to allowing patches to match on a label based selector?

**Comment by monopole** [comment]
@bickfordb  This issue was closed because of it's name and the introduction of set imageTag command.

The notion of applying patches guided by a label based selection could certainly be opened as a new issue.

As could the If you have time, please look at the conversation in #300 (less so the one in #169) and feel free to comment.  It's closely related so some of what you mentioned above w/r (outside the scope of changing only the image tag).

**Comment by bickfordb** [comment]
👍
