### ISSUE TITLE
Empty list item in secretGenerator creates nameless secret

### ISSUE THREAD

**Issue by ptemmer** [kubernetes-sigs/kustomize#1182]
```
secretGenerator:
- name: r509-database-properties
  env: r509-database.properties
- 
- name: remote-redis-properties
env: remote-redis.properties
```

Not really a bug, however it would be nice if an error message could be thrown.
It took me quite some time to figure out that there was an empty list item in one of my kustomize files.

Kubernetes errors out with:

> The Secret "-f8hfghffhd" is invalid: metadata.name: Invalid value: "-f8hfghffhd": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**Comment by Liujingfang1** [comment]
When `name` is missing from an item in the ConfigMapGenerator or SecretGenerator, throw an error.

**Comment by marga-kinvolk** [comment]
/reopen

This issue is still present. I ran into it today, running version 1.18.6, because I mistakenly added a new "item" when trying to add a namespace field, and only when I found this issue I managed to figure out that the problem was the spurious "-".

This snippet:

```
secretGenerator:
- namespace: my-namespace
- name: my-secret
  files:
  - my-file.yaml
```

Led to this error: `The Secret "-f8hfghffhd" is invalid: metadata.name: Invalid value: "-f8hfghffhd": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

Changed it to:

```
secretGenerator:
- name: my-secret
  namespace: my-namespace
  files:
  - my-file.yaml
```

And the error went away.

This is a UX issue. When dealing with many different config files and things going on, it's hard to track down where the error is coming from when the error message is so unhelpful.  As mentioned above, this should be fixed by adding a helpful error message when the `name` field is empty.
