### ISSUE TITLE
Specifying behavior for generator plugins

### ISSUE THREAD

**Issue by julienp** [kubernetes-sigs/kustomize#1207]
In [runGenerators](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/target/kusttarget.go#L253) the result maps of external generators are added to the accumulator with AppendAll ([kusttarget.go#L279](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/target/kusttarget.go#L279)) , whereas builtin generators use AbsorbAll ([kusttarget.go#L265](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/target/kusttarget.go#L265)), and thus allow specifying a behavior.
Is there a reason not to support `behavior` for custom plugins?

**Comment by Liujingfang1** [comment]
Since ConfigMap and Secret contains data, as key value pairs. It's quite straightforward to define the `merge`, `replace` behavior. For general generator plugins, depending on the type of resources it generates, different behaviors are not well defined. On the other side, you can apply patches to your generator config, which can be used to modify the behavior of generators from the overlay.

**Comment by donbowman** [comment]
so i have a plugin for generating secrets:
https://github.com/Agilicus/kustomize-sops

formerly this used the kvSources, and thus the merge worked.
Now it cannot work anymore due to this removal.

In the short term i apply this patch:
https://github.com/Agilicus/kustomize-sops/blob/master/kustomize.patch

(and below). But i don't know what your desired solution is. I need to be able to Merge, there is no way I can see to pass that info back from the plugin interface, and the plugin doesn't have access to the other objects to do the merge.

So how do you recommend we achieve this goal? It used to work, the function still has the case for 'legacy generators' but not the new ones.

```
diff --git a/pkg/target/kusttarget.go b/pkg/target/kusttarget.go
index a26fdce6..4bbbfe35 100644
--- a/sigs.k8s.io/kustomize/pkg/target/kusttarget.go
+++ b/sigs.k8s.io/kustomize/pkg/target/kusttarget.go
@@ -278,7 +278,10 @@ func (kt *KustTarget) runGenerators(
 		}
 		err = ra.AppendAll(resMap)
 		if err != nil {
-			return errors.Wrapf(err, "merging from generator %v", g)
+			err1 := ra.AbsorbAll(resMap)
+			if err1 != nil {
+				return errors.Wrapf(err, "merging from generator %v", g)
+			}
 		}
 	}
 	return nil
```

**Comment by rslinckx** [comment]
Our use case is similar in that we need to override or merge a secret/config generated in a base kustomization with additional keys in the config or secret coming from a generator. I believe this isn't possible currently

**Comment by ianmuscat** [comment]
I also ran into the exact same issue @donbowman outlined while trying to migrate a similar SOPS Kustomize plugin away from `kvSources`.

**Comment by imranismail** [comment]
For anyone trying the go plugin route. Supplying to behavior to go plugins didn't help

```go
func (p *plugin) Generate() (resmap.ResMap, error) {
	args := types.SecretArgs{}
	args.Name = p.Name
	args.Namespace = p.Namespace
	args.Behavior = 'replace'
	args.Type = p.Type
	...
```

**Comment by devstein** [comment]
@Liujingfang1 What is the best approach if you want your Go plugin to generate a resource that should be merged with a base resource (i.e a generated patch)?
