### ISSUE TITLE
Strategy to know which version of Kustomize is embedded in Kubectl?

### ISSUE THREAD

**Issue by Lawouach** [kubernetes-sigs/kustomize#1267]
Hi all,

I was wondering what was the documented strategy of synchronizing kustomize and kubectl? I see for instance there was 2.1 and now an upcoming 3.0 of Kustomize. What is the version is kubectl 1.14 using?

Cheers,

**Comment by monopole** [comment]
AFAIK, the kubectl binary doesn't have a command to show this. @Liujingfang1 ?

The intent is to pull latest release of kust into kubectl, but for kubectl v1.15 that had to be v2.0.3 (same as kubectl v1.14), because too many things were in motion at that cut point (primarily the migration to Go modules).  kubectl v1.16 should get kust v3.0 or higher.

**Comment by monopole** [comment]
FWIW, the front page of the kustomize repo mentions the version alignment.

**Comment by Liujingfang1** [comment]
We don't have a command in kubectl to show which version of Kustomize is used. As @monopole mentioned, we have this message on the front page of Kustomize repo.
In the future, we'll try to use the latest version of kustomize when a new kubectl version is released.

**Comment by Lawouach** [comment]
Thanks for the feedback. I think a command isn't strictly speaking needed for me, the README being up to date is great already. Just wanted to raise awareness that, if Kustomize evolves more rapidly, one might get surprised. 

I'm happt to close this one if you want.

**Comment by monopole** [comment]
ok, closing. Maybe add a feature request to [kubectl](https://github.com/kubernetes/kubectl) for a kustomize version command.
