### ISSUE TITLE
Customizing File Name

### ISSUE THREAD

**Issue by moserke** [kubernetes-sigs/kustomize#1353]
I have tried reading through the code and I believe the answer is no, but is there a way to modify the list of accepted filenames?  Currently 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' are the only acceptable names.  Is it possible to change that?

The use case is when wrapping kustomization functionality for internal users, having a filename that makes more sense to them helps in clarity.  This of course is a minor thing, but wanted to ask.

**Comment by richardmarshall** [comment]
The set of filenames for the kustomization file is [set in the source](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/pgmconfig/constants.go#L24) and currently can't be tweaked at runtime.

Since you're wrapping kustomize it seems like part of that logic could be mapping your internal version of the file to what kustomize expects.

**Comment by moserke** [comment]
yup for sure! I was just seeing if perhaps I missed an easier way.  You know don't invent the wheel if it's already there and such.  Thanks for the quick response!
