### ISSUE TITLE
Not able to change replicas count of nested overlays

### ISSUE THREAD

**Issue by benjamin-bergia** [kubernetes-sigs/kustomize#1399]
I have a repository with nested overlays. I noticed that in the kustomization.yml file of my top-level overlay, I cannot update the replicas count of my resources using the `replicas` field. I thought that it might be related to the fact that my nested overlays also have a `replicas` field in their kustomization, but it is not. Here is a short example. Using a structure like

```
env/
  overlays/
    prod/
      kustomization.yml (A)
  base/
    kustomization.yml (B)
    app/
      base/
        kustomization.yml (C)
      overlays/
        web/
          kustomization.yml (D)
        worker/
          kustomization.yml (E)
```
In *A* I would like to overwrite the replicas count of app/worker.
Here is what I noticed:
- if *E* contains a `replicas` field or not doesn't change anything
- if *A* includes *B* and *B* includes *E*, I cannot overwrite the replicas count
- if *A* includes *E* directly, I cannot overwrite the replicas count
- only *E* can overwrite the replicas count of it's base
Maybe related:
- if *A* includes *D* and *E* directly I get an error for multiple matches on the name of the configmap defined in app/base
- If *A* includes *B* and *B* includes *D* and *E*, I don't get this error

PS:
I just noticed that in *A* specifying the name of the deployment as defined in the app/base does work.
But it means that it will change the replicas count for all the overlays of this base.

**Comment by Liujingfang1** [comment]
@damienr74 Can you take a look at this?

**Comment by damienr74** [comment]
Sure!

@benjamin-bergia I don't really have a clear description of what you're trying to do with just a directory structure and potential imports. It would help immensely if you could:
- make a copy of the directory structure `mkdir minimal && cp -r env/* minimal/`.
- remove anything that isn't relevant to this issue (or that you don't want on public github).
- paste the output of `tail -n+1 $(find . -name "*.yml")` from the `./minimal` directory.
- briefly highlight which value you want changed, or what your ideal output would look like.

Also, if you are familiar with patches, can you test if it is possible to get the intended behavior by using a patch? Otherwise, I can look into it.

**Comment by benjamin-bergia** [comment]
Hi @damienr74 
I created a simple env from scratch to illustrate the issue.

The base deployment contains `replicas: 1`.
I would like to have 2 web and 4 worker in prod. So if you run `kustomize build env/overlays/prod` I would expect this to be the case, but it doesn't work.
In an other hand `kustomize build env/overlays/qa` works but doesn't let you change the replicas count of web and worker independently. 


[kustomize-1399.tar.gz](https://github.com/kubernetes-sigs/kustomize/files/3435096/kustomize-1399.tar.gz)

**Comment by damienr74** [comment]
Thanks for this complete example! :)

So patching does work, it appears the problem is with [this line](https://github.com/kubernetes-sigs/kustomize/blob/e646bba1ff4acafe820c5befee33f824a7a5fb47/plugin/builtin/replicacounttransformer/ReplicaCountTransformer.go#L39). Since it's using `GetByOriginalId`, it was only matching the original name of the resource. (Should be using `GetById`)

Will create a PR to fix this and add the test case soon.

>- if A includes D and E directly I get an error for multiple matches on the name of the configmap defined in app/base
> - If A includes B and B includes D and E, I don't get this error

Since the configmap issue doesn't exist with this minimal example, feel free to open another issue with just that problem.

Also in the meantime, in case you do not know, you can use patches to achieve what you're looking to do. For instance in  `env/overlays/prod/kustomization.yml`, add the following lines:
```yaml
patchesStrategicMerge:
  - web-patch.yml
  - worker-patch.yml
```
where `env/overlays/prod/worker-patch.yml` patch looks like this:
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-worker
spec:
  replicas: 4
```

**Comment by benjamin-bergia** [comment]
Hi @damienr74, It's true that with the new patch syntax it is pretty easy.
Anyway thank you for the help.
