### ISSUE TITLE
Impossible to use values from external sources

### ISSUE THREAD

**Issue by srfrnk** [kubernetes-sigs/kustomize#1406]
Many CI/CD systems inject required values via environment.
Currently `kustomize edit` allows only a limited set of changes to be injected from environment.
My use case involves a version timestamp generated by the build script.
I need to inject this timestamp both as the image tag and a `version` label to some K8S objects.
With current implementation I am forced to use `sed` or `envsubst` which makes using Kustomize redundant as well as being an ugly solution in itself.
Further more - injecting the full image requires me to maintain the image name in the scripts instead of just the version tag!
It would be favorable to just inject the tag and have the name stored in the original manifest.

**Comment by monopole** [comment]
@srfrnk as commented on #1407 

we're looking at this and related issues to try to come up with a more flexible declarative approach. seriously, thanks for helping to inform it.

- secrets are indeed a pain to declarative config, but kustomize doesn't require that they be stored in version control. PTAL at the two secret generator plugins in these [examples](https://github.com/kubernetes-sigs/kustomize/tree/master/docs/plugins#examples-1)
the secret values can come from literally anywhere (a database, the command line, RPC to a server on a satellite, etc.)
- the `kustomize edit` command can be improved.  i think it has been since this issue was filed. e.g. one can say things like `kustomize edit set image node:8.15.0 mysql=mariadb alpine@sha256:24a0c4b4a4c0eb97a1aabb8e29f18e917d05abfe1b7a7c07857230879ce7d3d3` and of course any of those args could come from the ENV.

**Comment by srfrnk** [comment]
@monopole Thanks for reaching out. I will stay tuned for any solution to this issue.
