### ISSUE TITLE
v3.1.0 does not accept null patches

### ISSUE THREAD

**Issue by no2a** [kubernetes-sigs/kustomize#1422]
Previous versions handle `patches: null` as if it were `patches: []`, but v3.1.0 failes. It is inconsistent that null is still allowed in other places such as resources. 

To reproduce:

* kustomization.yaml with null patches
```
patches:
```

* build it with v3.1.0 results in an error
```
$ kustomize_3.1.0_darwin_amd64 version
Version: {KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T18:11:16Z GoOs:darwin GoArch:amd64}
$ kustomize_3.1.0_darwin_amd64 build .
2019/08/01 15:10:30 invalid patches from <nil>
```

No error with v3.0.3 and v2.1.0
```
$ kustomize_3.0.3_darwin_amd64 version
Version: {KustomizeVersion:3.0.3 GitCommit:30b378a9244d757c1cda31b95694fabd6cbdb8e1 BuildDate:2019-07-18T17:45:11Z GoOs:darwin GoArch:amd64}
$ kustomize_3.0.3_darwin_amd64 build .
```
```
$ kustomize_2.1.0_darwin_amd64 version
Version: {KustomizeVersion:2.1.0 GitCommit:af67c893d87c5fb8200f8a3edac7fdafd61ec0bd BuildDate:2019-06-18T22:01:59Z GoOs:darwin GoArch:amd64}
$ kustomize_2.1.0 build .
```

**Comment by richardmarshall** [comment]
In 3.1.0 the new extended patch system was added which is reusing the previously deprecated `patches` field. To maintain compatibility with older kustomization files new fix up logic was added to fix up data in the old format.

https://github.com/kubernetes-sigs/kustomize/blob/2a2a889c378df641fe90f28417ac3b10372a1f63/pkg/types/fix.go#L43

In this fix up path a check for a nil value is not performed before a type assertion which is causing the error you're seeing. Since this is inconsistent with all the other slice types in the kustomization file I would say this is a bug.

/kind bug

**Comment by no2a** [comment]
same with 3.4.0
