### ISSUE TITLE
Remote Build Cache

### ISSUE THREAD

**Issue by tustvold** [kubernetes-sigs/kustomize#1431]
Currently [ClonerUsingGitExec](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/git/cloner.go#L38) creates a new directory within /tmp and checks out remote git repositories to that location. This is not ideal for many reasons:

- Makes iteration on a kustomize patch for a remote config incredibly slow and arduous as it checks out the repository every single time
- /tmp is often tmpfs and so checking out large git repositories to it is potentially ill advised
- If kustomize exits with an error it will leak the files in /tmp - if using tmpfs this is especially bad

I would like to propose some way to instruct kustomize to use a specific directory to check out remotes persistently, potentially via an environment variable. This would resolve all of the above and make kustomize a lot less painful to use on large projects.

This would potentially mitigate #1132 and #1147

**Comment by pyaillet** [comment]
I think it's already possible to instruct kustomize to use a specific directory by using the environment variables used by golang itself, see [here](https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/fs/confirmeddir.go#L33) and [there](https://golang.org/pkg/os/#TempDir)

However, I would too like to see some remote build cache implemented. 
I have tried a naive implementation of such a thing locally.

- Without cache: 

`kustomize build . > out.nocache  23,98s user 29,99s system 38% cpu 2:19,85 total`

- With cache: 

`~/Tools/go/src/sigs.k8s.io/kustomize/kustomize build . > out.cache  2,55s user 0,66s system 68% cpu 4,658 total`

Would it be acceptable to have a shared temp base folder to handle cleanup globally ?

**Comment by dsyer** [comment]
/reopen
/remove-lifecycle rotten

Please re-open. The build times are excruciating.

**Comment by ringerc** [comment]
See also https://github.com/kubernetes-sigs/kustomize/issues/1735 https://github.com/kubernetes-sigs/kustomize/issues/2460

**Comment by ringerc** [comment]
The option to specify a map of `--reference` repos would be a big help if people are worried about cache freshness. That way you can clone very quickly while still being guaranteed a fresh result.

**Comment by edrandall** [comment]
The rotten issue robot is a backlog antipattern, particularly when a project is clearly underresourced.

**Comment by ringerc** [comment]
Also, note that while it's tempting to think you can add a `--reference-if-able ~/.kustomize/gitcache` or something, where a single bare git repo serves as a cache for multiple upstreams, this will fall down rapidly. Git's logic for finding common commits between a reference repo and an upstream to clone does not scale to very large numbers of heads in in the reference repo, and will quickly become extremely slow. In practice you need one reference repo to serve as a cache for *each* upstream repo.

**Comment by ringerc** [comment]
There's a truly nasty way to make this work without patching `kustomize`, and a clean way to solve this in `kustomize`.

The nasty way, which suffers from the issue I mentioned above with a mega-cache repo and too many heads, but can still help, is to use the `GIT_ALTERNATE_OBJECT_DIRECTORIES` environment variable to essentially inject reference repos into every git invocation under kustomize's control.

Here's a demo showing how it works.

```
# normal clone
git clone --bare https://github.com/kubernetes-sigs/kustomize kustomize-cache
# now re-clone with the other repo as a cache. It'll be almost instant.
GIT_ALTERNATE_OBJECT_DIRECTORIES=kustomize-cache/objects git clone https://github.com/kubernetes-sigs/kustomize
```

Here's an example of how you might use it for commonly cloned upstreams. For each commonly cloned upmstream:

```
kustgitcache=$HOME/.kustomize/cache/git
mkdir -p $kustgitcache
git clone --bare --no-tags MY_REPO_URL $kustgitcache/MY_REPO_NAME
```

(It'll be more efficient if you can limit the refs you add, instead of fetching all heads)

You can construct your `GIT_ALTERNATE_OBJECT_DIRECTORIES` with something like

```
GIT_ALTERNATE_OBJECT_DIRECTORIES="$(ls -d -1 $kustgitcache/*/objects | paste -s -d ':')"
```

So if you run `kustomize` with that, it'll use any of the matching alternates as if they were passed to `--reference-if-able`, e.g.:

```
GIT_ALTERNATE_OBJECT_DIRECTORIES="$(ls -d -1 $kustgitcache/*/objects | paste -s -d ':')" kustomize build $my_kustomization_dir
```

It would work *much* better if implemented in https://github.com/kubernetes-sigs/kustomize/blob/master/api/internal/git/cloner.go with a caching cloner option or something, since then it could set up a `GIT_ALTERNATE_OBJECT_DIRECTORIES` that points only to a cache for a specific repo, reducing the number of refs that must be checked. It could also populate the cache if it doesn't already exist.

**Comment by ringerc** [comment]
@natasha41575 That sounds cool and useful. However it will *not* solve the use cases here IMO.

In particular, for CI systems, pre-commit hooks, and other automation, you often have almost the same kustomizations being built running repeatedly, but with a few small variations.

A fully localized, cacheable tree doesn't help much with that unless the cache can be used as a base to be refreshed with only more recent updates.

In those cases what's really desirable is:

* For git remote bases, a reference repository to use when cloning the remote;
* For https file remote bases, a cache of downloaded files, and http requests that can send `If-Modified-Since` cache headers so servers can respond with 304 when the resource is unchanged

**Comment by briceburg** [comment]
Agree w/ ^^^.  

I'd like to use a kustomize repo where we develop and version shared bases and components in a conventional way.

e.g.

```yaml
resources:
- https://github.com/acme/kustomize//bases/service?ref=v1

components:
- https://github.com/acme/kustomize//components/ingress-public/overlays/dev?ref=v1
- https://github.com/acme/kustomize//components/secretstore/overlays/dev?ref=v1
- ../../components/secrets
```

... and to avoid the maintenance burden and duplicate code (wet not DRY?) of vendoring.

Not sure this issue is closed, can the bot re-open ? =)
