### ISSUE TITLE
Version kustomization.yaml files

### ISSUE THREAD

**Issue by r2d4** [kubernetes-sigs/kustomize#144]
I'm hoping to do some parsing of the kustomization.yaml files and it would be helpful if the config was versioned. Maybe kubernetes style?

**Comment by Liujingfang1** [comment]
@r2d4 I took a look at your PR, you want to add the support of custom path instead of using current directory. In skaffold.yaml, you can add a field for this custom path. `kustomize` is able to build a given direcory as `kustomize build <path>`.

**Comment by r2d4** [comment]
Hi @Liujingfang1, the reference is not necessarily for the PR, but for the comment in the code. 

To get the file dependencies of the kustomization.yaml file, we could need to unmarshal the YAML and parse it. To ensure that parsing doesn't break, we should parse it according to some well known version, e.g. `kustomize/v1alpha2`

**Comment by Liujingfang1** [comment]
@r2d4 `kustomization.yaml` doesn't have version since it is not a kubernetes type. I don't think adding a version for it makes sense.

**Comment by r2d4** [comment]
If there are breaking changes to the kustomization.yaml, how downstream tooling that reads or generates kustomize files know?

**Comment by monopole** [comment]
@r2d4 we had this (standards k8s metadata / group-version-kind fields) and dropped it temporarily as, at the time, those fields weren't consumed by anything and in the case of a simple overlay (e.g. just adding a nameprefix)  could double the size of the file.

Decided to add them back as soon as we needed to make any kind of breaking change, or had a tool that exploited them.   Should probably do it sooner rather than later to avoid confusion about how they'll be versioned.
