### ISSUE TITLE
Cannot reference non-HEAD or untagged commits

### ISSUE THREAD

**Issue by mgoodness** [kubernetes-sigs/kustomize#1452]
I believe #857 introduced a regression that prevents the use of specific GitHub commits as references unless they are either the HEAD of a branch or tagged. For example, building from the following kustomization.yaml succeeds because commit `df7ed659a7b6280bb28838e0f87d54de435afe83` is tagged `v0.1` in the repo.

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/mgoodness/sample-app-deploy/base?ref=df7ed659a7b6280bb28838e0f87d54de435afe83
```

However, commit `769f3aae20c1527e2ebc0fbbf89cc3a6e71e8d23` is neither a HEAD nor tagged, so the following build fails.

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/mgoodness/sample-app-deploy/base?ref=769f3aae20c1527e2ebc0fbbf89cc3a6e71e8d23
```

The root cause is that [GitHub doesn't allow fetching commits by hash](https://github.com/isaacs/github/issues/436).

Using specific commits is considered by some a [best practice](https://argoproj.github.io/argo-cd/user-guide/best_practices/#ensuring-manifests-at-git-revisions-are-truly-immutable), so we should find away to re-enable it.

**Comment by kinghajj** [comment]
This bug prevents us from updating past v2.0.3. Are there any plans to support this workflow again? We could work around this by pushing tags on the specific commits we reference, but that's not as secure, since [Github won't let you prevent tags from being modified](https://github.com/isaacs/github/issues/1091). Perhaps there could be two `Cloner` implementations, the post-#857 one and the pre-#857 one, and a command line flag used to enable the previous behavior?
