### ISSUE TITLE
Update kustomize version that's shipped in kubectl?

### ISSUE THREAD

**Issue by pascalgn** [kubernetes-sigs/kustomize#1500]
Not sure where the right repository is for this, maybe here, maybe https://github.com/kubernetes/kubectl, maybe https://github.com/kubernetes/kubernetes?

Kubernetes has just released [v1.16.0-beta.2](https://github.com/kubernetes/kubernetes/releases/tag/v1.16.0-beta.2) and so far I haven't seen anything about a new kustomize version in the changelogs. I think if we want to have an updated version shipped in kubectl 1.16, we need to do something in the near future.

Are there any plans for updating the kustomize version that's integrated into kubectl?

**Comment by dijitali** [comment]
It was mentioned in https://github.com/kubernetes-sigs/kustomize/issues/1267#issuecomment-506554768 that the intention is for each `kubectl` release to use the latest `kustomize` version.  

Is this issue the correct place to be tracking progress on this?

Just for context: the mismatch in functionality is a proving bit inconvenient for us when we're trying to build automation around `kustomize`.

See also: https://github.com/kubernetes-sigs/kustomize/issues/1424

**Comment by dijitali** [comment]
Not sure if I'm supposed to marking this issue as fresh.  My apologies if not. 

From my perspective I think this is still an issue and some guidance would be appreciated as we're attempting to use kustomize in automation.

Sounds like from the discussion in https://github.com/kubernetes/kubernetes/pull/85146 that there might be a different approach proposed here?

**Comment by ofek** [comment]
Any update on this?

**Comment by Shell32-Natsu** [comment]
We are working on this.

**Comment by Shell32-Natsu** [comment]
Another issue about removing apimachinery and related libraries. https://github.com/kubernetes-sigs/kustomize/issues/2506

**Comment by monopole** [comment]
Update: targetting kubectl release v1.21, code freeze.

Per: https://www.kubernetes.dev/resources/release/

> Tuesday, February 9th: Week 5 - Enhancements Freeze
> Tuesday, March 9th: Week 9 - Code Freeze

[v3.9.2]: https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.9.2

The best way to help on this issue is use and report bugs in the latest standalone version of kustomize in the _3.9_ series -  e.g. [v3.9.2].

This instance of the kustomize CLI uses the same libraries which will be linked into kubectl; we're shaking out the bugs.  Kustomize releases every two weeks, while kubectl releases at most once a qtr.
