### ISSUE TITLE
do kustomize suppport template

### ISSUE THREAD

**Issue by magicsong** [kubernetes-sigs/kustomize#1503]
each time i run kubebuider i need to use `sed` to change values in the patch. and then the temporary will push to my repo if i forget to change it back. Is it possible to use `go template` in patch file and i can do something like `export image_name=sedgoaway kustomize build`

**Comment by magicsong** [comment]
btw, `sed -i` is different in macos and linux.

**Comment by Liujingfang1** [comment]
@magicsong Since this is a kubebuilder project. You can update the Makefile to avoid updating the patch each time.

**Comment by magicsong** [comment]
@Liujingfang1 problem still exsits. The patch is always changed.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by karlmutch** [comment]
Not sure if this helps in your specific case, I am using yq, https://github.com/mikefarah/yq. It allows me to modify the kustomization.yaml files I have as a preprocessing step.

**Comment by magicsong** [comment]
@karlmutch the tool you recommended is great. however, in my condition, it is just a replacement of sed and still i need to change the patch each time

**Comment by ivanseidel** [comment]
I think this is something that needs attention. I came to kustomize because I wanted simplicity, but it seems it only supports inheritance but not templating (kubetpl does a good job on it, but mustache would do a good job as well).

I just want to replace some vars prior to building, and without changing the file.

The first phrase at kustomize says:

> kustomize lets you customize raw, template-free YAML files for multiple purposes, leaving the original YAML untouched and usable as is.

This isn't true, because a simple `kustomize edit` modifies `kustomize.yaml` witch is an `yaml` file.

I wish I could override and make templating as simple as it is... without having to inherit everything and make it strict as hell.

**Comment by bzub** [comment]
The value in kustomize, and what sets it apart from other tools is because everyone who runs kustomize build on the same resources get the same result. If you want to do templating there are plenty of tools for that.

https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#unstructured-edits

https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#build-time-side-effects-from-cli-args-or-env-variables

**Comment by magicsong** [comment]
@bzub helm is not a CI/CD tool at least for me. it is heavy and i am still uncomfortable with its C/S architecture - why i need a server when i just want "apply a yaml"
