### ISSUE TITLE
Multiple variants to deploy

### ISSUE THREAD

**Issue by lenlen** [kubernetes-sigs/kustomize#152]
I'm using kustomize to deploy my apps with kubernetes. I'd like to explain my user case that doesn't seem to fit in kustomize specifications.
I have two kinds of configuration for my app dev and production, so I've implemented the overlay with two sub folder and a common base.
Furthermore I have N numbers of experiments, N means that the number could be very high and every experiment is only a slight modification of the command of the application. So in total I have 2*N variants.
It is impossible write 2*N variant, but I'd like to have only two variants (dev/production) and dynamically choose the experiment to patch the final yaml.

Below my actual configuration for a single experiment:

```
- overlays:
  - dev
    kustomization.yaml
    patches.yaml
  - prod
    kustomization.yaml
    patches.yaml
  kustomization.yaml
```

I'd like to have a parameter or an environment variable to run kustomize with the experiment, for example
```
EXP=exp1.yaml kustomize build overlays/dev
EXP=exp2.yaml kustomize build overlays/prod
```

and in the overlays/[dev/prod]/kustomization.yaml

```
bases:
  - ../../
patches:
- patches.yaml
- ${EXP}
```
Thanks

**Comment by Liujingfang1** [comment]
@lenlen You can create 2N variants by scripts with the main steps as
```
for i in {1..N}; do
cp -r overlays/dev overlays/dev-exp${i}
cd overlays/dev-exp${i}
kustomize edit add patch exp${i}.yaml 
kustomize build .
done
```

**Comment by bhack** [comment]
@Liujingfang1 it could be hard to do in this way when you are using kustomize trough Google Skaffold. What do you think?

**Comment by Liujingfang1** [comment]
@bhack Do you have a Skaffold issue? Or can you explain more how you want to use it through Skaffold?

**Comment by lenlen** [comment]
Thanks @Liujingfang1. I use kustomize with skaffold, for this reason I'm thinking about an environment variable. With skaffold it is only possible pass the path of kustomize yaml and is not possible use a loop. See the snippet below

```
    deploy:
      kustomize:
         kustomizePath: overlays/dev/
```

**Comment by bhack** [comment]
If you think that this use case involve only skaffold we will close it and open on Skaffold.

**Comment by monopole** [comment]
There's a couple of things going on here.

At the moment `kustomize build {target}` operates on one target.  To operate on N targets, as @Liujingfang1 points out you need N build commands, and it's on you to understand the consequences.  We could build that loop into kustomize, but in making that "easy" we'd be somewhat obligated to also make sure those N things didn't do anything surprising (e.g. namePrefix collisions, since N namePrefix directives could operate at the _same target level_ rather than stack up).

But if all you want to do is turn on an experiment (e.g. turn on a flag to make some UX feature change color), its probably easiest to frame activation of the experiment as editting one line in a multi-line env file that's used to configure a configMap (rather than attempt to frame it as a "patch").

**Comment by Liujingfang1** [comment]
Kustomize doesn't support any resource or patch from an environment variable. https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#build-time-side-effects-from-cli-args-or-env-variables
