### ISSUE TITLE
pre-upgrade Hook

### ISSUE THREAD

**Issue by kvokka** [kubernetes-sigs/kustomize#1580]
Given the scenario, when kustomization contains only DB migration and deployment. The good practice is to run the migration first and on success run the deployment.

The possible option is to control it on the client with 2 kustomize executions.

At this moment the idea of creation the plugin, which wrap up all the migration and deployment in some Job and ship both in order.

With Helm there is possible to use `pre-upgrade` hook. But are there any built-in solutions with Kustomize?

Thank you!

Connect #168

**Comment by bzub** [comment]
I don't think kustomize will get built-in support for this. Compared to helm, kustomize is meant to be a building block tool rather than managing the lifecycle of k8s deployments as helm tries to offer.

Kustomize does offer creating an [inventory object](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/inventory_object.md) which can be used by another tool to manage deployment lifecycle.

See also: [Eschewed Features: Build-time side effects from CLI args or env variables](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#build-time-side-effects-from-cli-args-or-env-variables)

**Comment by alahijani** [comment]
#903 could be a neat solution if it ever gets implemented.

**Comment by reegnz** [comment]
Can someone reopen this issue please? Would be nice to give at least a common pattern on what one is supposed to be doing to work with this problem.
