### ISSUE TITLE
Consider/document how to use Jobs with Kustomize

### ISSUE THREAD

**Issue by paultiplady** [kubernetes-sigs/kustomize#168]
As part of some CI/CD steps it's necessary to run a one-off job from inside the cluster. An example from my pipeline would be running a Django database migration before upgrading the code in staging/production.

There are a few ways of achieving this that I've come across;

1. as an initContainer
2. as a k8s Job
3. using `kubectl run`

I've tried these in Kustomize, and getting k8s Jobs to play nice is a little challenging.

These Jobs need to consume Secrets/Configmaps that are created and hashed by Kustomize, so I think they need to be generated by Kustomize too.

Since a Job name must be unique, unless I have some way of transforming the Job name into something unique, I can't re-run a job inside the same namespace (e.g. I want to apply new code in staging => re-run migration job). A possible workaround here would be to always try to do a `kubectl delete job myjob` before applying the new `kustomize build` output, but then I lose the old job history.

In some cases (per-branch / per-commit / per-tag jobs) It might be enough to do name hashing based on the contents of the Job. I could easily imagine wanting to run a job on every apply though, i.e. requiring fully randomized Job names.

I don't see any issues/discussion on this subject; what's the current best-practice on this subject?

**Comment by Liujingfang1** [comment]
@paultiplady I'm trying to understand your problem. You wan to run some CI jobs and you want every job to have a different name. You can try this. You can put Secrets/Configmaps and your job into the same kustomization. Then for every job you need to run, you can add a different namePrefix, maybe the commit hash. You can do this by `kustomize edit set nameprefix <commit hash>`.  Then `kustomize build . | kubectl apply -f -`. Then the jobs will have different names.

**Comment by lswith** [comment]
Here is the context for myself and possibly others:

I have a CI/CD pipeline that requires database migrations to run before a deployment begins. The database migration needs to exit with a non-zero status before the deployment can start its rollout.

I am currently using Kubernetes Jobs to run the migration beforehand, checking the result and then setting a deployment's image if it succeeds. 

I understand coupling migrations to deployments is bad practice but in general, there are many times where I need to couple a kubernetes Job to a deployment rollout. It's not useful to do an initContainer because an initContainer is per pod. I need an initJob that can run before a deployment rollout.

Obviously this scope is quite large but it would be nice to use kustomize to generate a job per deployment similar to what is being done for configMaps.

**Comment by Liujingfang1** [comment]
@paultiplady @lswith There is a proposal to handle your database migration before rolling out a deployment https://github.com/kubernetes/community/pull/1171. Before these hooks are available, continuing using Kubernetes Job is a good approach. 

Now how could Kustomize help with this? I don't think kustomize can handle the whole thing all by itself. Coupling Kustomize with some scripts could definitely help. For example, you can try separate your configs into two kustomization. One is for the Job running the database migration. The other is for the deployment itself. For any ConfigMaps and Secrets that are shared by the Job and deployment, put them into a common base. Then the script need to `kubectl apply` the Job kustomization and watch the status. Once it succeeds, the script need to `kubectl apply` the other kustomization.

**Comment by Liujingfang1** [comment]
@paultiplady @lswith Have you got a chance to look at and try the approach of two kustomizations. Any suggestions or comments? If it looks good, we will document this approach.

**Comment by burdiyan** [comment]
I would suggest to try running these one off jobs in bare pods without any controller. I haven’t tried it but seems like it may be a solution.

**Comment by DeadZen** [comment]
You have even more issues if you need to run multiple jobs in succession and that if a migration step fails, kubernetes will just keep trying to rerun it, it seems the solution to each issue is to just create a deployment with a replica count of 1 and when its done successfully, deploy. Is there an effective alternative?

**Comment by silviogutierrez** [comment]
@Liujingfang1: I think the simplest thing here would be to be able to have first class support to set a jobSuffix and be able to edit it with `kustomize edit set`

Right now, my release script (that is, script that creates a release *not* the deployment) does this:

```bash
cd $PROJECT_ROOT/containers/release/base
kustomize edit set image joy-client=$CLIENT_IMAGE:$VERSION_TAG
kustomize edit set image joy-server=$SERVER_IMAGE:$VERSION_TAG
```

Base has everything of mine, *including* the migration job. If we had a simple command to kustomize jobSuffix or something of the like, then I could just also call, right below:
```bash
kustomize edit set jobSuffix migrations=$VERSION_TAG
```

Or something like that. Thus updating my `kustomization.yaml` nicely and letting my deploy script stay as simple as:

```bash
kustomize build containers/release/overlays/production | kubectl apply -f -
```

No waiting, or anything else.

**Comment by jamshid** [comment]
I'm surprised k8s / kustomize don't seem to have a good way to accomplish something like a one-off db migration. Seems that could have been handled pretty well with a `docker-compose run`.

**Comment by matti** [comment]
workaround: https://github.com/kubernetes-sigs/kustomize/issues/903#issuecomment-590593588

**Comment by stefanv** [comment]
The workaround suggested in the comment above is to delete the old job, and to then re-run the job.  That works, but ideally you want to simply create a new job, with a name like `job-name-[timestamp]` or `job-name-[iteration]`.  I.e., kustomize could help to provide simple templating support, so that a unique job id is generated for each invocation.

**Comment by wotzhs** [comment]
ran into this problem a while back, and have been search high and low how to get this done. I found out from some article online saying with the same job name, you can `kubectl create` many times without running into the name problem, whereas `kubectl apply` requires unique name each time.

luckily in my case, I am using `argo` for the continuous deployment, so to achieve the `kubectl create` one can include the following annotation to the job:
```yaml
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
```

this way there won't be any issues with Job & kustomize, hope it helps!

ref: https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#replace-resource-instead-of-applying-changes

**Comment by strowk** [comment]
You can ask k8s to remove job after it is done using `ttlSecondsAfterFinished` , see: 
https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically

This allows to run the same job on every kustomize apply, so far as you don't do it more often than the specified ttl. I set 30 seconds, because for me now it is enough to read logs during development and I don't deploy more often than that. 

With kustomize magic you can set value to 0 for your other environments where you do not control how often deployments happen. Zero results in immediate removal in my test with k3d.

The downside is that troubleshooting might be harder in some situations, but if you collect logs and events from pods centrally on your cloud environments, it is workaroundable.

**Comment by lopezchr** [comment]
I'm using kustomize with argocd and I need to specify the changes into the kustomization files. It will be fine if we could specify a sufix like kustomize uses with config maps or secrets.
