### ISSUE TITLE
Patches not applied when used alongside patchesStrategicMerge  

### ISSUE THREAD

**Issue by jslusher** [kubernetes-sigs/kustomize#1706]
Kustomize version = 3.2.3

kustomization.yaml:
```
bases:
  - ../../../../apps/redis-ha/5.0.5

commonLabels:
  env: staging

patches:
- set-ha-sts-monitoring.yaml
- set-ha-sts-resources.yaml
- set-ha-sts-update-policy.yaml

patchesStrategicMerge:
- redis-ha-configmap.yaml
- redis-ha-healthchecks.yaml
```

I have an overlay that is trying to apply a few patches along with a couple of `patchesStrategicMerge` objects. The strategic merge object are applied, but the patches are not. If I remove the strategic merge objects from the kustomization the patches are again applied. This was working in v1.0.11 but when I try to use version 3.2.3 the patches are not applied. Is this intentional?

**Comment by Liujingfang1** [comment]
In Kusotmize 2.0, `patches` is marked deprecated.

In 3.2.3, `patches` have different [syntax](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins/builtins.md#field-name-patches). This change is since 3.1.0 and here is the [release note](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/v3.1.0.md#extended-patches).
Please change it to
```
patches:
- path:set-ha-sts-monitoring.yaml
- path: set-ha-sts-resources.yaml
- path: set-ha-sts-update-policy.yaml
```

**Comment by jslusher** [comment]
@Liujingfang1 I totally missed that. Thank you for the quick response!
