### ISSUE TITLE
Idea: vendor external resources including non-kustomize manifests

### ISSUE THREAD

**Issue by yujunz** [kubernetes-sigs/kustomize#1735]
Remote build of kustomize could be slow if the repository is huge while we only need a small piece from it. For example, when adding https://github.com/argoproj/argo-cd/tree/master/manifests/cluster-install as a remote resource, kustomize needs to clone the whole repository which takes a long time.

The idea of vendor external resources is similar to `go mod vendor` which makes vendored copy of dependencies to speed up `kustomize build`.

If you find it useful too, please 👍 this ticket and I will draft a KEP for further review.

**Comment by bzub** [comment]
Similar issue: https://github.com/kubernetes-sigs/kustomize/issues/1132

Vendoring seems like it could be done easily enough outside of kustomization using git submodule, git subtree or simple forking/cloning.

To me it would only be worth mimicking go modules if kustomize also supported similar go.mod/go.sum validations. Otherwise the same issues with latency and security for remote bases would remain that exist today -- a remote not under your control could change at any time.

Here's another proposal that could help with speed via caching, as a compromise: https://github.com/kubernetes-sigs/kustomize/issues/1431

**Comment by bzub** [comment]
The ability to specify a git clone depth like [go-getter](https://github.com/hashicorp/go-getter#git-git) does could satisfy a lot of use-cases in a simple way.

**Comment by yujunz** [comment]
We did implement a go-getter plugin as in https://github.com/kubernetes-sigs/kustomize/tree/master/plugin/someteam.example.com/v1/gogetter .

**Comment by yujunz** [comment]
go-getter supports checksum validation, subdirectory and almost everything we want for dependency management. The current drawbacks is it requires extra configuration steps to enable the plugin and building with alpha flag. Maybe we just need to connecting the dots to make life easier for end users.

**Comment by yujunz** [comment]
A quick example in https://github.com/yujunz/kustomize-vendor-example

**Comment by pietervincken** [comment]
If I'm not mistaken the git clone is already performing a shallow clone? (see https://github.com/kubernetes-sigs/kustomize/blob/644f2ddcdc3123b285f86e3e1d288b540042e4a1/api/git/cloner.go#L69
). Are you sure it is slow due to the git clone?

We've experienced slow (30-60s) builds as well, but from the verbose logging is seems that it's actually all the processing that is performed, not the git clone. The CPU (single core) is also pinned at 100% during this time.

**Comment by bb010g** [comment]
I just ran into this when packaging the [Flux CLI](<https://github.com/fluxcd/flux2>) for Nixpkgs due to it running `kustomize build` on manifests specified as HTTPS URLs. A simple `kustomize vendor` command would be great for package maintainers.
