### ISSUE TITLE
namePrefix should not apply to declared namespace

### ISSUE THREAD

**Issue by surki** [kubernetes-sigs/kustomize#1899]
This is a duplicate of #235, as that fix seems to have been lost, we could still see the issue.
Lot of us are using json patch hack to overcome this, we would like to have this fixed in kustomize.

**Comment by schaze** [comment]
Can this be picked up again please? I am not sure why an issue which has (apparently) a working fix but is not actually fixed stays closed? This problem is a real annoyance for a lot of people and I for my part am getting tired of having to patch/fix these "strange" behaviors out of kustomize in my yamls (same goes e.g. for the commonLables problem with the selectors in netowrkpolicies...).

**Comment by neilharris123** [comment]
+1, this issue is a real problem
