### ISSUE TITLE
pseudo/k8s/api protobufs interferes with standard k8s.io/api packages

### ISSUE THREAD

**Issue by dsharp-pivotal** [kubernetes-sigs/kustomize#1906]
We use `krusty.MakeKustomizer()` in tests of our operator. Our operator also, naturally, uses k8s.io/api packages. When we run the test that uses krusty, we get many log lines of `proto: duplicate proto type registered: %s`, since both packages register the same protos.

I understand the desire to vendor a snapshotted version of k8s packages. However, I don't think it is working as intended, since the protobufs don't remain isolated from each other.

One workaround I considered was to add a "replace" directive in our go.mod file that would replace `sig.k8s.io/kustomize/pseudo/k8s/api` with the real `k8s.io/api`. I'm not 100% sure this would even work. However, `pseudo/k8s/api` is not a module (`pseudo/k8s` is the module), so it can't be replaced. Could `pseudo/k8s` be re-engineered so that the k8s modules are still modules?

**Comment by jbrette** [comment]
You are not the only one who realized how deeply the apimachine code  copy/paste into pseudo negatively impacted the usability of the k8s.io/api

It seems that copy/paste of 3000 files was trying to break the dependency loop in kubectl where kustomize is imported, an finally be able to upgrade "kubectl apply -k"from kustomize 2.x to kustomize 3 or 4.

- The side effect is that your code cant not really use the k8s.io/api v2.x  as a submodule when it needs to use the official apimachinery code.
- Even the internal kustomize project called kstatus had to revert back [the changes from pseudo back to apimachinery](https://github.com/kubernetes-sigs/kustomize/blob/master/kstatus/status/generic.go#L11)
- It also breaks the SMP merge patch handling for CRD by kustomize. because you can not do [scheme.Register](https://github.com/keleustes/kustomize/blob/airshipctl/kustomize/register/MonitoringCRDRegister.go#L20) anymore.
 
I'm not really sure when we will be able to reuse kustomize/api as a library as we could before the "pseudo/kyaml/crawler" gigantic PRs.

kustomize/api v0.1.1 is probably your best hope.
or if you want to have access to the latest version of the kustomize without the "pseudo" copy paste you can have a look [here](https://github.com/keleustes/kustomize)

**Comment by monopole** [comment]
https://github.com/kubernetes-sigs/kustomize/tree/master/pseudo/k8s
needs to go.

**Comment by pwittrock** [comment]
https://github.com/kubernetes-sigs/kustomize/pull/1935

**Comment by muvaf** [comment]
@jbrette I'm looking at the fork you linked. Is there a plan to merge those extra features upstream? Especially feature 4 would be **really** useful https://github.com/keleustes/kustomize#feature-4-let-you-referinline-field-from-on-k8s-resource-to-another
