### ISSUE TITLE
allow `kustomize config run` to run as job in target cluster

### ISSUE THREAD

**Issue by bkuschel** [kubernetes-sigs/kustomize#2096]
Use Cases:
- I don't have docker engine installed, only have access to the target cluster and want to execute a config function
- I am running in a docker container in kubernetes and not able to run docker engine but can create jobs.

**Comment by bkuschel** [comment]
@pwittrock any thoughts around this?

**Comment by bzub** [comment]
I really like this idea, just not sure if it should be in scope for kustomize CLI. I like that `kustomize config run` is devoid of a kubernetes client and focuses on client-side only. Maybe it could help create a Job resource config but things would get complex quickly if it had to query a cluster to get the output of config functions.

Have you tried using config functions with something like [Tekton](https://github.com/tektoncd/pipeline) yet? I've been meaning to try it myself.

**Comment by bkuschel** [comment]
How would you use Tekton, doesn't it also need to be run in a kubernetes cluster?

**Comment by bzub** [comment]
Tekton seems like a possible solution for your use case of running config functions via kubernetes cluster rather than via local docker instance. It has a similar concept of a pipeline of containers like `kustomize config run` implements and is mentioned here: https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/docs/api-conventions/functions-impl.md
