### ISSUE TITLE
`kubectl kustomize version` should report version info

### ISSUE THREAD

**Issue by nicks** [kubernetes-sigs/kustomize#2142]
**Expected behavior:**

```
kubectl kustomize version
```

should print information about the version of Kustomize templates that `kubectl kustomize` accepts, similar to the `kustomize version` command

**Actual behavior**

```
kubectl kustomize version
``` 

doesn't work. 

The kubectl command only accepts kustomize version 2+, but the main kustomize repo is on version 3+. This has caused some confusion for our users, because they thought that they should be using the "new way" of preferring `kubectl kustomize` over `kustomize`

Obviously, we could work around this by keeping a map from kubectl versions to compatible kustomize versions, but it would be nice if we could get this info from `kubectl kustomize`

PS -- I also filed https://github.com/kubernetes/kubectl/issues/797, but someone there commented that this belongs in the kustomize repo. I'm not totally clear on the relationship between kustomize team and the `kubectl` team, and why `kustomize version` is in one but not the other. Happy to redirect conversation to the appropriate place!

**Comment by leoskyrocker** [comment]
as an aside - should you not prefer `kubectl kustomize` over `kustomize`?

**Comment by davidnqd** [comment]
Should it be `--help` or `--version`? (Just to avoid conflict with a possible `./version` in the cwd)

**Comment by greenstatic** [comment]
> Should it be in `--help` or `--version`? (Just to avoid conflict with a possible `./version` in the cwd)

It should probably be simply `kubectl kustomize version` since the version subcommand is present in kustomize (`kustomize version`) and even kubectl (`kubectl version`). Having two sets of CLI syntaxes for the same program (kustomize) will probably be confusing,

Regarding the name clash with a file named `version` in the cwd, maybe it would be better not to link `kubectl kustomize` to `kustomize build` and to have the `build` argument in there?
