### ISSUE TITLE
kustomize build could not find plugin path in Gitlab CI environment

### ISSUE THREAD

**Issue by liuyangc3** [kubernetes-sigs/kustomize#2348]
version
```shell
kustomize version
{Version:3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-17T14:23:25+00:00 GoOs:darwin GoArch:amd64}
```
files
```
tree -l
├── base
│   └── kustomization.yaml
├── kustomize
│   └── plugin
│       └── f2pool
│           └── chartinflator
│               └── ChartInflator
└── overlays
    ├── kustomization.yaml
```

cmd works well in local Mac env
```
XDG_CONFIG_HOME=$(pwd) kustomize build --enable_alpha_plugins $(pwd)/overlays 
```

but the same cmd not works in Gitlab CI, CI config
```
job:
  script:
    - ls -l $(pwd)/kustomize/plugin/f2pool/chartinflator/ChartInflator
    - XDG_CONFIG_HOME=$(pwd) kustomize build --enable_alpha_plugins $(pwd)/overlays
```

below is CI output, even I typed `ls -l $(pwd)/kustomize/plugin/f2pool/chartinflator/ChartInflator` to chcek out wether the plugin file exist. but kustomize can not find it.
```shell
gitlab-runner exec shell job
Running with gitlab-runner 12.8.0 (1b659122)
Running on runner--project-0-concurrent-0 via yangdeMacBook-Pro.local...
Fetching changes...
Initialized empty Git repository in /builds/project-0/.git/
...

$ ls -l $(pwd)/kustomize/plugin/f2pool/chartinflator/ChartInflator
-rwxrwxrwx    1 root     root          4987 Apr  8 10:33 /builds/project-0/kustomize/plugin/f2pool/chartinflator/ChartInflator
$ XDG_CONFIG_HOME=$(pwd) kustomize build --enable_alpha_plugins $(pwd)/overlays
Error: accumulating resources: recursed accumulation of path '/builds/project-0/base': failure in plugin configured via /tmp/kust-plugin-config-388698460; fork/exec /builds/project-0/kustomize/plugin/f2pool/chartinflator/ChartInflator: no such file or directory: fork/exec /builds/project-0/kustomize/plugin/f2pool/chartinflator/ChartInflator: no such file or directory
ERROR: Job failed: exit code 1
FATAL: exit code 1
```

**Comment by NingPekin** [comment]
I hit the same problem using alpine image. It seems that it's not compatible on alpine. Try use debian, it works for me.

**Comment by liuyangc3** [comment]
alpine need to install this package
```
apk add libxdg-basedir
```

**Comment by BoKKeR** [comment]
Posting here since this is the only post that comes up on google.

`trouble decrypting file Error getting data key: 0 successful groups required, got 0Error: accumulating resources: accumulation err='accumulating resources from 'rest-client': '/Users/git/iam-k8s-config/local-dev/rest-client' must resolve to a file': recursed accumulation of path '/Users/git/iam-k8s-config/local-dev/rest-client': failure in plugin configured via /var/folders/ly/80p2c9zx2jl15d0mv0f2lb3r0000gn/T/kust-plugin-config-2032692962; exit status 1: exit status 1`

This has happened to me when I renamed the AWS profile from default to something else. It was trying to use the wrong credentials to decode sops
