### ISSUE TITLE
Request providing a windows binary in release

### ISSUE THREAD

**Issue by wolfm89** [kubernetes-sigs/kustomize#2521]
There seems to be no .tar.gz file for Windows in the new release: https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.5.5

What is the reason behind this? Should we build it ourselves? Thanks for clarification!

**Comment by monopole** [comment]
See comment in https://github.com/kubernetes-sigs/kustomize/blob/master/releasing/cloudbuild.sh#L45.  Windows support was dropped as it was blocking releases for linux (and mac).  linux gets priority because many kustomize users run kustomize in a linux-derived container, irrespective of their desktop.

help wanted please to reinstate the windows build.

issue title changed  to reflect this.

**Comment by monopole** [comment]
thanks @MadVikingGod  !
