### ISSUE TITLE
CMD UX  proposal for delete setter and delete substitution

### ISSUE THREAD

**Issue by jijiew** [kubernetes-sigs/kustomize#2569]
corresponds to the create setter and create a substitution, the proposal for delete setter and delete substitution is below:

kustomize config delete-setter DIR NAME         see  #2553 
DIR: A directory containing Resource configuration.
NAME: name of the setter to delete

kustomize config delete-subst DIR NAME
DIR:A directory containing Resource configuration.
NAME:name of the substituion to delete

**Comment by mortent** [comment]
If we wanted to just have a delete command that would handle both setters and substitutions, do we think there are any challenges with implementing that solution? I'm not sure if it is better ux though, since just calling the command delete would not make it clear what it is actually deleting. Unless we can come up with a good name (more specific than just `delete` but less awkward than `delete-setter-or-substitution`), I think I lean towards having two different commands.

Also, could we expand this to explain how we would handle deleting setters that might be used in substitutions? And is there anyway nested substitutions could be broken by deleting a substitution?

@phanimarupaka @frankfarzan

**Comment by jijiew** [comment]
Just adding more information, the current implementation for delete setters #2553 , as aligned with the above proposal have the following cmd UI

kustomize config  delete-setter DIR NAME

right now, the delete-setter will look for the setter name if it exists, return error if the setter to delete does not exist; then it checks if the setter is used in substitutions, if it is used in substitution, it will return error and asked the users to delete the substitution first, maybe composition as well in the future. If the setter is a standalone setter, it go ahead and delete the setter by 1. removing the setter definition from schema 2. removing the comment from resource file, similar to what create setter does, but the opposite way. 

With that, the delete substitution can have two ways with flag/arg guarded option: remove substitution only or remove setters in addition to the substitution. 

let me know your thoughts @frankfarzan @mortent  @phanimarupaka
