### ISSUE TITLE
Kustomize broken when run from within go path

### ISSUE THREAD

**Issue by emosbaugh** [kubernetes-sigs/kustomize#282]
`isRepoUrl` function returns true for paths that contain `.com` or `.org`.

for example `/go/src/github.com/myorg/myrepo/`

https://github.com/kubernetes-sigs/kustomize/blob/aff09b11085bc18915a23b332de93ec156c2dda3/pkg/loader/githubloader.go#L78

error:

```
Error: loadResMapFromBasesAndResources: couldn't make app for ../../base: open /tmp/base/kustomization.yaml: no such file or directory
```

**Comment by Liujingfang1** [comment]
That's too bad. Maybe we only need to keep "https://"

**Comment by emosbaugh** [comment]
Would it be enough to check if the file exists? happy to make a contribution if we can settle on implementation.

**Comment by Liujingfang1** [comment]
Kustomize uses a loader interface to load files from local or from a remote place. In current code, the logic goes by this way: first check the target by `isRepoUrl` and create githubloader if this function returns true; then check if the target exist in local filesystem and create fileloader.

Since `github.com` can also be a directory in local filesystem, so you see this bug. We can change the logic a little bit by first checking if the target exists locally. If it doesn't, then check with `isRepoUrl`.
The code I mentioned in `NewLoader` function. https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/loader/loader.go#L41

@emosbaugh It would be nice if you can contribute. Take a look at the code and let me know if you need any help.

**Comment by emosbaugh** [comment]
Happy to. PR shortly
