### ISSUE TITLE
Provide Default For Properties Set By Environemnt Variable

### ISSUE THREAD

**Issue by sstubbs** [kubernetes-sigs/kustomize#2881]
Hi,

I apologise if I've missed this somewhere in the documentation. I have this problem here https://github.com/sstubbs/direct-csi/commit/b26ba15fce36a1fcb2d2a4577befe4b7eb8bd5e1 if I add a default value for KUBELET_DIR_PATH then this overwrites the environment variable but I want the environment variable to overwrite the default.

**Comment by secret104278** [comment]
It seems impossible because current implementation only checks environment variable if value is not specified in env file.

https://github.com/kubernetes-sigs/kustomize/blob/6e7713281e716232481659fd5f602b66140c9a16/api/kv/kv.go#L163-L169

**Comment by YiannisGkoufas** [comment]
I am really puzzled about how to kustomize a CSI deployment in this cases. KUBELET_DIR_PATH should be customizable. For instance in this yaml:
https://raw.githubusercontent.com/kubernetes-csi/csi-driver-host-path/master/deploy/kubernetes-1.18/hostpath/csi-hostpath-plugin.yaml is located in multiple places. Is there a suggested way to kustomize KUBELET_DIR_PATH?

**Comment by Shell32-Natsu** [comment]
@monopole Should we exchange the order of these 2 value sources?

**Comment by Shell32-Natsu** [comment]
Kustomize is not designed to consume an env var form the OS. [link](https://kubernetes-sigs.github.io/kustomize/faq/eschewedfeatures/#build-time-side-effects-from-cli-args-or-env-variables). You should update your properties file before running kustomize build.

/close

**Comment by YiannisGkoufas** [comment]
@Shell32-Natsu for your reply. I think there is a bit of misunderstanding about the functionality I am talking about. In this file:
https://raw.githubusercontent.com/kubernetes-csi/csi-driver-host-path/master/deploy/kubernetes-1.18/hostpath/csi-hostpath-plugin.yaml I would like to have the directory /var/lib/kubelet customizable since it's referred in multiple places (hostpath, args etc)
I was looking for suggestions about how to do that besides the patching approach mentioned here https://stackoverflow.com/questions/63722885/use-kustomize-to-set-hostpath-path

**Comment by Shell32-Natsu** [comment]
@YiannisGkoufas You can try [variable references](https://kubernetes-sigs.github.io/kustomize/api-reference/kustomization/vars/)
