### ISSUE TITLE
Go example plugins (and other Go plugins) not building

### ISSUE THREAD

**Issue by jmhodges** [kubernetes-sigs/kustomize#2965]
With kustomize v3.8.2, the example plugin github.com/monopole/sopsencodedsecrets also doesn't run because of package mismatch. There doesn't appear to be a`v3.8.2` tag that's usable in sopsencodedsecrets's go.mod (the `kustomize/v3.8.2` is an invalid version string for `go mod` because `go mod` needs the string to start with a `v` and then be followed by a semantic version)

Here's the package mismatch I'm seeing:

```
$  kustomize build --enable_alpha_plugins ./foobar
Error: loading generator plugins: plugin /Users/jmhodges/.config/kustomize/plugin/v1/sopsencodedsecrets/SopsEncodedSecrets fails to load: plugin.Open("/Users/jmhodges/.config/kustomize/plugin/v1/sopsencodedsecrets/SopsEncodedSecrets"): plugin was built with a different version of package github.com/golang/protobuf/proto
```

Similarly, I wrote my own plugin that ran in to:

```
plugin was built with a different version of package sigs.k8s.io/kustomize/v3/pkg/gvk
```

I'm not sure what the solution is here. Without a proper go.mod tag, it's not clear what a Go developer is supposed to do.

**Comment by jmhodges** [comment]
It looks like there's a new API we're supposed to be depending on? I'm having trouble with some package mismatch using it, as well, but I suppose this is another ticket.

Perhaps this ticket should be about updating the Go plugin docs?

**Comment by Shell32-Natsu** [comment]
What's the "new API"? Could you provide the link to the docs that you are referring to?

**Comment by jmhodges** [comment]
Ah, yes! Here's the link I found for docs https://kubernetes-sigs.github.io/kustomize/guides/plugins/ (there's a redirect to it from the GitHub page that comes back from Googling "kustomize go plugins": https://github.com/kubernetes-sigs/kustomize/tree/master/docs/plugins).

It  -- by way of the @monopole/sopsencodedsecrets example it uses -- uses `sigs.k8s.io/kustomize/v3/pkg/ifc` and other `v3` import paths. The new API is apparently in the `sigs.k8s.io/kustomize/api/...` packages?

**Comment by Shell32-Natsu** [comment]
`sigs.k8s.io/kustomize/v3/pkg/ifc` has been refactored more than a year. You should use the *new API*.

**Comment by jmhodges** [comment]
Yeah, I'm asking for the docs to be updated.

**Comment by Shell32-Natsu** [comment]
*sops encoded secrets* and *SOPSGenerator* are out of kustomize repo so we cannot make sure they are up to date. Will note this in the doc.

**Comment by monopole** [comment]
[issues]: https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+%22plugin+was+built+with+a+different+version+of+package%22

Unfortunately, usage of the Go plugins package (in upstream Go lang) has problems that afaict haven't been solved.  

Some characteristic bugs listed [here][issues].

Go's  [plugin package](https://pkg.go.dev/plugin) hasn't seemed to have gotten attention,  which has to be considered in light of how well other things have gone with the Go language.

We warn about their use [here](https://kubernetes-sigs.github.io/kustomize/guides/plugins/goplugincaveats).  They've never been suitable as a code distribution mechanism, but the hope was that they be a means to build high performance (in-process) transformers in kustomize, for those willing to compile `main` along with their plugins.

This arrangement is appealing, because a plugin author can use the existing test framework for builtin transformers, and the step to contributing to the main code base is just send a PR with the plugin - no need to edit kustomize's transformer orchestration code.

However, even that's been problematic, as the right combination of compiler flags, compiler environment and working directory has been unclear and possibly changing (again, see [issues], esp https://github.com/golang/go/issues/27751).

Maybe we can use this bug as a means to find the right combination to make it work reliably.
If not, we should deprecated Go plugins until more progress is made on the Go side.

**Comment by jmhodges** [comment]
I ran into many of the problems you discuss!

That's all fair. I suppose I can convert this into an exec system.
