### ISSUE TITLE
Feature request: read from stdin as a resource

### ISSUE THREAD

**Issue by torsten-liermann** [kubernetes-sigs/kustomize#2985]
Would it be possible to have kustomize build read the resource from stdin, just like Unix pipes work?

That would simplify use cases, which at the moment include kustomize unnecessarily via wrapper scripts.

For example: `helm template --post-renderer ./kustomize-wrapper.sh`

kustomize-wrapper.sh:
```
cat> input-for-kustomize.yaml
Customize build.
```

It would be conceivable to have kustomize read from stdin if no resource is specified, or "-" (minus) or /dev/fd/0 for a resource path

Thanks!

**Comment by Shell32-Natsu** [comment]
@monopole WDYT?

**Comment by monopole** [comment]
For the particular case of reading from a helm chart, we have [this example](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md).  It  could use some improvement - see #3128

A previously proposed interpretation of a missing `resources:` field was to treat it as a wildcard, e.g.
a missing `resources:` field would be equivalent to
```
resources:
- *
- */*
- */*/*   (etc.)
```

If this implicit _inclusion_ method were supported (i.e. if no resource manifest is specified, then read all the files in the directory tree), then kustomize would have to provide an _exclusion_ manifest to specify the files that should _not_ be included (like a `.gitignore` file).  A program like kustomize must specify either inclusions or exclusions; we opted to specify inclusions (like a `Makefile`).  Also, [globbing is not supported](https://kubernetes-sigs.github.io/kustomize/faq/eschewedfeatures/#globs-in-kustomization-files).


The goal of these choices is to err on the side of literal declaration of the cluster's configuration. One should only have to consult a kustomization file (and the files it points to) to understand the config, and not also have to understand what was on disk at the time someone ran `kustomize build`.

Reading from `stdin` is technically possible of course.  We could allow a `-` in the list of `resources:` and use that to trigger a read from `stdin`.

But it breaks the notion of declaring what you use even more than globbing does.  With globbing, you can maybe assume that if the kustomization file and its surroundings were maintained in source control that you have a clear declaration of configuration.

Leaving this issue open for more comment.

Would like to see #3128 done before thinking about allowing `stdin`, to see if that's good enough.

Meanwhile suggest try following the chartinflator example (see the [unit test](https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/someteam.example.com/v1/chartinflator/ChartInflator_test.go#L78)).

**Comment by aodinokov** [comment]
>kustomize read from stdin if no resource is specified, or "-" (minus) or /dev/fd/0 for a resource path

Not sure it's the best option, because kustomize may call other kustomization in resources and it also may have that "-".

One more idea - to add a flag `--as-transformer` to `kustomize build` command that would read stdin and add all read yamls as like they were mentioned in kustomization.yaml `resorces` section located in DIR passed to `kustomize build`.

The underlaying kustomizations in that case won't get that resources - only the top one.
Also I think it correlates with the general idea that [everything is transformer](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/#everything-is-a-transformer) in a way that right now kustomize is rather `generator`, because it can't accept and transform stdin.
But if we make it - it will be possible to put only chain of transformers in kustomization.yaml and kustomize will apply all of them to stdin and put everything in stdout like a normal transformer... and this is great, because 'everything is transformer' even kustomize itself :) ... btw it will work more like `kpt fn run`

also it may allow to remove some of that separate commands in `kustomize cfg`, e.g.
```
  annotate      [Alpha] Set an annotation on Resources.
  grep          [Alpha] Search for matching Resources in a directory or from stdin
```
because it's possible to do them with kustomization...

cc: @monopole

**Comment by KnVerey** [comment]
@monopole and I discussed this at length, and in the end we agreed that this feature should not be accepted. Although the trigger isn't CLI args or env vars in this case, it is definitely still a "[build-time side effect](https://kubectl.docs.kubernetes.io/faq/kustomize/eschewedfeatures/#build-time-side-effects-from-cli-args-or-env-variables)". While it may be convenient for certain workflows built around it, facilitating dependence on build-time side-effects violates an important principle of Kustomize's approach. As @monopole commented earlier, "one should only have to consult a kustomization file (and the files it points to) to understand the config, and not also have to understand what was on disk at the time someone ran `kustomize build`." We will update the [Eschewed Features](https://kubectl.docs.kubernetes.io/faq/kustomize/eschewedfeatures/) to clarify this.

As for the Helm use case in particular, the example mentioned earlier has been replaced with / promoted to a [built-in transformer](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md), and contributions to make it better for real-world Helm use cases are appreciated.

/close

**Comment by aodinokov** [comment]
This is a great explanation:

> "one should only have to consult a kustomization file (and the files it points to) to understand the config, and not also have to understand what was on disk at the time someone ran `kustomize build`."

When I PoC'ed that feature with additional flag  `--as-transformer` I had a gut feeling that it should be a different command. something like `kustomize transform` rather than  `kustomize build --as-transformer` :) But this implies lots of additional use-cases.  This is potentially a completely different tool that has a lot in overlap with `kustomize fn run`/`kpt fn run` :)

Thank you @KnVerey :)

**Comment by tcurdt** [comment]
Disappointing. This would be great:

`cat kustomization.yaml | kustomize build - | kubectl apply -f -`
