### ISSUE TITLE
[Question] 3.8.3 Breaks Namespace Creation

### ISSUE THREAD

**Issue by zacheryph** [kubernetes-sigs/kustomize#3156]
Kustomize does not auto-create namespaces, but after 3.8.2, all namespace resources get overwritten. Is this an expected breakage to not be allowed to create a secondary supporting namespace? and yet... still forced to create a Namespace resource to ensure the namespace exists?

### Playground
```shell
$ cat kustomization.yaml
namespace: one
resources: ["ns.yaml"]

$ cat ns.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: two
---
apiVersion: v1
kind: Namespace
metadata:
  name: three
```

### 3.8.2
As you would expect having two Namespace objects (or... more)
```shell
$ kustomize version
{Version:kustomize/v3.8.2 GitCommit:e2973f6ecc9be6187cfd5ecf5e180f842249b3c6 BuildDate:2020-08-29T17:44:01Z GoOs:darwin GoArch:amd64}

$ kustomize build
apiVersion: v1
kind: Namespace
metadata:
  name: three
---
apiVersion: v1
kind: Namespace
metadata:
  name: two
```

### 3.8.3
Something happened.

```shell
$ ~/Downloads/kustomize version
{Version:kustomize/v3.8.3 GitCommit:161af9d99c16125a4394326a3d26000dbf5dd159 BuildDate:2020-09-18T00:21:28Z GoOs:darwin GoArch:amd64}

$ ~/Downloads/kustomize build
Error: namespace transformation produces ID conflict:
[
  {"apiVersion":"v1","kind":"Namespace","metadata":{"name":"one"}}{nsfx:false,beh:unspecified}
  {"apiVersion":"v1","kind":"Namespace","metadata":{"name":"one"}}{nsfx:false,beh:unspecified}
]
```

**Comment by Shell32-Natsu** [comment]
Reason: #2953 

`namespace` field will update the `metadata.name` property for all `namespace` resources. Given all the resources' namespace will be overridden, is there any necessity to create other namespaces with different names?

**Comment by zacheryph** [comment]
In my case I was creating a secondary namespace the CI system was using to execute its builds in.

I am not against this. I like the idea of not having to define the namespace in two places. Maybe just the way its implemented? My question is... you force the name of any _and all_ Namespace resources to the defined namespace within kustomization.yaml, why not just.. create the namespace period? You now force people to create a resource file just to override one of the biggest values inside of it.

Why not introduce a `createNamespace` directive that will create said Namespace, and.. leave hand-made Namespace resources alone?

**Comment by Shell32-Natsu** [comment]
If you put a `namespace` in the kustomize, what kustomize considers is you want to override the namespace to *all* resources. If there is a resource with `kind: Namespace`, it's reasonable to update the name as well because other resources may be in that namespace.

If you want to create separate namespaces, I have 2 ideas.

1. Use an overlay to add namespaces. `namespace` in kustomization file is a transformer and it will be run against the resources in its scope. The `namespace` will be only added to the resources in bases.
2. Use a custom transformer. Custom transformers are run after builtin ones so you can add the namespaces without being overridden.
