### ISSUE TITLE
Set cross-cutting options using CLI

### ISSUE THREAD

**Issue by msonnleitner** [kubernetes-sigs/kustomize#3390]
**Is your feature request related to a problem? Please describe.**

In Helm, is it possible to provide a release name using `helm install release-name chart` (and generating resource names with that value). 

In kustomize, it is possible to specify a `namePrefix` and `nameSuffix`, however this has to be done in a the `kustomization.yaml`

**Describe the solution you'd like**

a feature to specify that in the CLI, like

`kustomize build  --namePrefix dev- . 
`

**Describe alternatives you've considered**

It can be hard-coded and/or changed  in`kustomization.yaml`. However, this means changing the file (which may not be desirable in a CI context)

**Comment by natasha41575** [comment]
One of the principles of kustomize is that everything that `kustomize build` needs should be specified in the kustomization file so that it can be checked into source control and reproduced. See https://kubectl.docs.kubernetes.io/faq/kustomize/eschewedfeatures/#build-time-side-effects-from-cli-args-or-env-variables for more details.

An alternative solution to your issue would be to do the following:

`kustomize edit set nameprefix 'dev-'`

Followed by 

`kustomize build`

**Comment by msonnleitner** [comment]
Thank you for your answer. Well if this is against kustomize's philosophy, I guess I am going to close this issue.
