### ISSUE TITLE
Support assign variants' value directly

### ISSUE THREAD

**Issue by Betula-L** [kubernetes-sigs/kustomize#345]
The values of variants must depend on some refs, for example
```
vars:
  - name: SOME_SECRET_NAME
    objref:
      kind: Secret
      name: my-secret
      apiVersion: v1
  - name: MY_SERVICE_NAME
    objref:
      kind: Service
      name: my-service
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
```
However, why can't i define variants as follow?
```
vars:
  - name: SOME_SECRET_NAME
    value: "abc"
```

**Comment by Liujingfang1** [comment]
@Betula-L `Vars` uses the same idea as [downward API ](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#motivation-for-the-downward-api)and injects other object's field value into containers. 
 Kustomize provides other approaches for doing the same thing as using arbitrary value in vars.
You can apply `patches` or [`patchesJson6902`](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/jsonpatch.md) in overlays.

**Comment by ajbouh** [comment]
@Liujingfang1 one possible difference between Vars and the other approaches is it's reasonable to expect a failure of some kind if you misspell the name of a variable (or fail to define it). It's hard to imagine supporting that sort of thing for patches, as the whole idea of the patch is that it's "optional" from the perspective of the base. Right?

**Comment by ajbouh** [comment]
I just came across another need for this: I'm trying to use kustomize to "render" my kubernetes manifests for different regions. Since there's no concept of a "region" object in kubernetes/kustomize, there's nothing to use in objref!

Using patches or patchesJson6902 is a poor fit because there are multiple locations that must be updated with a variable's value. It is much simpler to initially specify a variable in *one* place and reference it in many places. Maintenance of the variable approach is also easier, as you can add additional references to a variable as needed.

**Comment by Betula-L** [comment]
I agree this `Using patches or patchesJson6902 is a poor fit ` as described by `ajbouh`.

**Comment by ajbouh** [comment]
I'm working around this in some cases by adding the target value as an annotation or label in a patch and then using objref in a var definition.

**Comment by ajbouh** [comment]
What would putting api-server into global mean? Why would vars be wrong?

**Comment by Liujingfang1** [comment]
VAR was designed with the purpose to inject one object's info into another object's container. It's not for arbitrary text match/replace.

**Comment by ajbouh** [comment]
Got it, thanks for explaining that.

**Comment by Liujingfang1** [comment]
Assigning Vars directly is not supported. We will add some document for that.

**Comment by muvaf** [comment]
It'd be awesome to have that or another feature that achieves this. What I'm implementing right now is that there is a Custom Resource in the Kubernetes cluster and my controller manipulates `kustomization.yaml` file with the values from that specific custom resource, then run kustomize and then deploy the generated YAMLs per CR instance.

Just like @Betula-L 's case, there are some configuration fields such as `region` that I'd like to give at the top `kustomization.yaml` file and expect to propagate down to all resources. All deployed resources are custom resources as well, so I'm able to define the `VarReferences` following [this tutorial](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md#adding-a-custom-resource). But I cannot do something like;
```
vars:
- name: BEE_ACTION
  objref:
    kind: Bee
    name: bee
    apiVersion: v1beta1
  fieldref:
    fieldpath: spec.action
```
because the instance of `Bee` kind is not kustomize directory, it's in the cluster. So, when kustomize is run, it cannot find that CR instance. But in my controller, I have both CR instance object and `Kustomization` object loaded from `kustomization.yaml`. So, I'm already loading and editing the `kustomization.yaml` file in Go code, I'd have loved the ability to just put something like
```
vars:
- name: BEE_ACTION
  value: actionstr
```

@Liujingfang1 If you can point me to another direction that'd make it possible to achieve the same thing, that'd be great, too.
