### ISSUE TITLE
Multiple patches in one file

### ISSUE THREAD

**Issue by yanniszark** [kubernetes-sigs/kustomize#3481]
**Is your feature request related to a problem? Please describe.**

Related issue: https://github.com/kubernetes-sigs/kustomize/issues/3028

`patchesStrategicMerge` supported specifying multiple patches in one file. The new `patches` field, which seems to be the new recommended way, only supports one patch per file.

**Describe the solution you'd like**

Support multiple patches per file.

**Describe alternatives you've considered**

Use the older `patchesStrategicMerge` field. However, it would be great if we could standardize.

**Additional context**

I am not sure why this decision was taken, as many times it's useful to be able to specify multiple patches in one place. Perhaps they are connected by some context (together they achieve some goal). What was the reason for not supporting such a scenario? Would you consider adding it?

cc @monopole

**Comment by dlipovetsky** [comment]
> We could relax that and allow N:M, but the field will be a little more complex, a little more error prone, and errors (or unexpected outcomes) a littler harder to debug/explain.

kustomize v4.1.3  interprets items in `patches` differently. For example, let's say an entry is a path to a file with multiple patches. If the item uses the `path` field, then `kustomize build`  reports an error parsing the file ([Minimal working example](https://github.com/dlipovetsky/kustomize-patches-error/tree/aa3810df1985d8566c18a3bf312fd7f5f208e706)). If the item does _not_ use the `path` field, `kustomize build` succeeds ([Minimal working example](https://github.com/dlipovetsky/kustomize-patches-error/tree/34b1078223fd4defda161760ba8166c81c0643b3)).

I could not understand why `kustomize build` would break if the item used the `path` field, but work otherwise. I found it very confusing.

Since kustomize continues to support the `patchesStrategicMerge` field, I would ask that kustomize be _more_ strict about the `patches` field, i.e., that `kustomize build` fail if an item in `patches` does not have the expected fields.

**Comment by scratchmex** [comment]
@monopole any further discussion about this? @dlipovetsky said a reason. Sorry to bump this but I also encounter this behavior and I would find it very convenient to use the `patches` section.

**Comment by lblazewski** [comment]
Hey!!

Sorry to bump such and old thread but in the light of: https://github.com/kubernetes-sigs/kustomize/issues/4706 which deprecates `patchesStrategicMerge` should this be reconsidered?

I thought that the deprecation of `patchesStrategicMerge` would allow now to specify 

```
patches:
 - path: my-strategic-merge-patch.yaml
 ```

which can include inside multiple strategic merge patches separated by `---`

**Comment by natasha41575** [comment]
@lblazewski I see you are commenting on many related issues regarding the same request. We are aware of https://github.com/kubernetes-sigs/kustomize/issues/5049. I would like to ask that we keep the discussion on that issue so that we can track it more easily. 

I'll add a link to this issue there. I am inclined to support your request, but we need some time to discuss how we would like to handle it and will provide an update on https://github.com/kubernetes-sigs/kustomize/issues/5049 when we reach a decision.
