### ISSUE TITLE
Offer the option to use annotations instead of hash suffix in ConfigMap generator

### ISSUE THREAD

**Issue by benjamin-bergia** [kubernetes-sigs/kustomize#3635]
**Is your feature request related to a problem? Please describe.**
I use the CM generator to generate pretty much all my CMs. I like the the hash suffix feature that trigger a rollout of all my deployments when my configuration changes. Unfortunately in some cases, I want to reference these CMs in applications that are not managed by kustomize or part of a different project. This means that I have to use the `disableNameSuffixHash` option on these CMs and lose the rollout automation.

**Describe the solution you'd like**
I would like an additional option on the CM generator. Something like `enableAnnotationHash` which could be used alone or in combination with the name suffix hash. When set to `true`, kustomize would go through all the resources referencing the CM (like it currently does for the name suffix), but instead of updating the CM name in the reference, it would add annotations like `hash.kustomize.io/myconfigmapname: myconfigmaphash`. This should behave like `commonLabels`, ie adding the annotations not only to the deployment metadata but also to any annotations in the spec and templates.

**Comment by Shell32-Natsu** [comment]
You can take a look at [exec plugin](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/execpluginguidedexample/) to create your own plugin.

**Comment by benjamin-bergia** [comment]
@Shell32-Natsu I don't think it's possible. It means writing an exec plugin that re-implement almost exactly what the configmap generator does. Also the complicated part of the configmap generator is not generating the configmap (it's already illustrated in the doc you sent), it's the logic to update references.

**Comment by Shell32-Natsu** [comment]
I will leave this issue open and see if there are other requests for the same feature.

**Comment by ChristianCiach** [comment]
I second this request, because I have the same use case. An operator that comes with my cluster (k3s) requires me to create a configmap with a specific name.

The secret I want to use is created by a Kustomize-`Component`  that is used by a lot of "overlays". And for the vast majority of these overlays I actually want to let Kustomize generate a hash value. 

As a workaround for said operator that expects a hardcoded configmap name, I've tried to disable the hash suffix for this specific overlay. But no matter what I try inside my overlay, Kustomize insist to add the hash suffix to the name. In other words: It doesn't seem to be possible to disable the hash suffix generation for specific overlays. You can only enable or disable the hash suffix generation in the same kustomization where the generator is specified. Is this a bug?

My Component:
```
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: 'cacerts'
    files:
      - 'configs/cacert.pem'
```

I've tried multiple things in my overlay to get rid of the hash, but none of these methods work:
```
components:
  - '../../cacerts'

generatorOptions:
  disableNameSuffixHash: true
```
Another attempt:
```
components:
  - '../../cacerts'

patches:
  - target:
      kind: ConfigMap
      name: cacerts.*
    patch: |-
      - op: replace
        path: /metadata/name
        value: traefik-cacerts
```

But none of these get rid of the hash suffix.

If the hash wasn't part of the name, but instead defined as annotations, I could use the required configmap name without issues.

**Comment by benjamin-bergia** [comment]
@ChristianCiach It's not a bug the generatorOptions need to be specified in the same file than the generator like you mentioned ;)

**Comment by pcjun97** [comment]
Was facing the same issue and developed a custom exec plugin: https://github.com/pcjun97/kustomize-hash-annotator. It can hash any resources, not just ConfigMap or Secret generated with the builtin generators, and add the annotations to any resources as well.

**Comment by olfway** [comment]
I'm using it with https://github.com/kbst/terraform-provider-kustomization and unfortunately hash suffix causes diff to be useless

**Comment by ChristianCiach** [comment]
What @olfway just said is also true for https://github.com/vmware-tanzu/carvel-kapp. Kapp would normally show an "update" operation and shows the diff. Because of hash suffixes, it will just show "delete" and "create" operations. I can live with that, but it surely would be nicer with annotations.

**Comment by benjamin-bergia** [comment]
I am still having issues with this. Right now change a CM in my repo means having the whole file for `mycm-23de23` being deleted and a new one for say `mycm-34ef34` being created. It is kind of hard to make any sense of the diff.

The whole mechanic for implementing this feature request is already there. It just means that instead of patching the CM name in each resource referencing it we need to add/update an annotation.

This could replace the CM hash suffix entirely and provides a clearer neater solution.
