### ISSUE TITLE
[Question] Installation kustomize for armv7

### ISSUE THREAD

**Issue by maroci** [kubernetes-sigs/kustomize#3646]
I was trying to install kustomize on my RPI OS lite armv7.
I was trying the binary but, this script doesn’t work for ARM architecture. 

Can you help suggest an alternative way to install kustomize for arm architecture? 
Thanks

**Comment by Shell32-Natsu** [comment]
I don't have ARM machine in my hand now so I cannot check this for you. Could you provide your commands to install kustomize and the error message?

**Comment by maroci** [comment]
**The Command I run us:** 
curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

**ERROR:** 
-bash: ./kustomize: cannot execute binary file: Exec format error

I was assuming maybe I'm wrong that I'm running amrv7 and I cannot run binary for OS at 64 bit. I'm not sure.
Thank you very much.

**Comment by darktempla** [comment]
@maroci - I wouldn't mind an armv7 binary as well. There are a lot of old Raspberry Pi v3 and earlier out there that are running 32bit v6 and v7 ARM architectures. So would be nice to be able to easily be able to have these running on hardware that whilst a bit dated is still functional and very good in a home lab or work test environment.

After doing some digging the install script looks like it fails for you because there is no supported version to download.

If you go to the link below you see what is compiled and released. Only arm64 is supported from an ARM architecture point of view.

- https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.0.5

As a work around you could use the kustomize plugin version that comes bundled with kubectl. I found an ARM v7 based compiled version from google. I have tested this on a "Raspberry Pi 3 Model B Plus Rev 1.3" and seems to work okay. So you would run something like this `./kubectl kustomize .`

- https://storage.googleapis.com/kubernetes-release/release/v1.18.8/bin/linux/arm/kubectl
