### ISSUE TITLE
YAML-formatted JSON6902 patches are added twice

### ISSUE THREAD

**Issue by mgoodness** [kubernetes-sigs/kustomize#368]
overlay `kustomization.yaml`:
```patchesJson6902:
- path: add_args.yaml
  target:
    group: apps
    kind: Deployment
    name: external-dns
    version: v1
```

overlay `add_args.yaml`:
```- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --domain-filter=sandbox-kubeadm.us-east-1.tktm.io
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --txt-owner-id=sandbox-kubeadm
```

output:
```
      - args:
        ...
        - --domain-filter=sandbox-kubeadm.us-east-1.tktm.io
        - --txt-owner-id=sandbox-kubeadm
        - --domain-filter=sandbox-kubeadm.us-east-1.tktm.io
        - --txt-owner-id=sandbox-kubeadm
```

**Comment by miekg** [comment]
Seeing this as well

**Comment by schweikert** [comment]
This looks to be a YAML specific bug, possibly caused by the fact that the code uses a different library for YAML-formatted JSON6902 patches and JSON-formatted JSON6902 patches. It feels a bit weird to use completely different code bases for the patch logic, only based on wether the patch is formatted as JSON or YAML. Maybe it would be better to convert the YAML-formatted JSON6902 to JSON first and use the normal evanphx/json-patch library?
