### ISSUE TITLE
incomprehensible error message

### ISSUE THREAD

**Issue by symbiont-ji** [kubernetes-sigs/kustomize#3812]
In https://github.com/kubernetes-sigs/kustomize/blob/a5914abad89e0b18129eaf1acc784f9fe7d21439/api/loader/fileloader.go#L161, what does "must be a directory to be a root" even mean? That's not English!

**Comment by Shell32-Natsu** [comment]
This error message means the `path` must be a directory, so it can be used as a build *root*.

**Comment by symbiont-ji** [comment]
Can the phrasing be fixed please?

**Comment by rdxmb** [comment]
This is indeed very confusing. I have a syntax error in my `services.yaml` , e.g. the `ports` key is missing. As a result I get

```
$ kustomize build .
Error: accumulating resources: accumulation err='accumulating resources from 'resources/service.yaml': yaml: line 9: did not find expected key': got file 'service.yaml', but '/home/marc/projects/k8-orchestration/tick-kustomize/base/kapacitor/resources/service.yaml' must be a directory to be a root
```

The first part of the error is kind of ok, but the second part does not make any sense here for the user.

Files:
```

$ cat resources/service.yaml 
---
apiVersion: v1
kind: Service
metadata:
  name: kapacitor
  labels:
    app.kubernetes.io/name: tick-kapacitor
spec:
  selector:
    app.kubernetes.io/name: tick-kapacitor
    - name: http
      port: 9092
      protocol: TCP
  type: ClusterIP
```

```
$ cat kustomization.yaml 
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/service.yaml
  - resources/statefulset.yaml
```

**Comment by rdxmb** [comment]
@Shell32-Natsu in some cases the error message might be correct. However, it appears also when there are some syntax problems within the files. Then it's very confusing. This seems to be an issue for me :)

**Comment by digihunch** [comment]
In my case, the  actual error was duplicate resource name. 
This error message is very misleading and it appears before the actual error message.

**Comment by m-Bilal** [comment]
Does the error message "`path` must be a directory so that it can be used as a build root" make more sense?

**Comment by natasha41575** [comment]
> Is there a specific reason we're ignoring other errors here?

What we are trying to do is first try to load the resource as a file. If there is an error, proceed to try to load the resource as a directory. 

Perhaps it doesn't make the most sense and there may be a way to restructure the code to provide more specific error messages.

**Comment by m-Bilal** [comment]
I think the fix would be to make `Read()` in [kyaml/kio/byteio_reader.go](https://github.com/kubernetes-sigs/kustomize/blob/c65ef489ca2782dafc2f50a62b21b2560dd54168/kyaml/kio/byteio_reader.go#L198) return a specific error type (like `MalformedYAMLError` / `InvalidInputError`) so that we can check for it in `kusttarget.go`'s `accumulateFile()` and return if that is the error type. Is that the correct approach?

Another way I can think of doing this is to check if the `path` is not a directory and there's an error in `kusttarget`'s `accumulateFile()`, return the error instead of trying to load the resource as a directory.

**Comment by felipetssilva** [comment]
> In
> 
> https://github.com/kubernetes-sigs/kustomize/blob/a5914abad89e0b18129eaf1acc784f9fe7d21439/api/loader/fileloader.go#L161
> 
> , what does "must be a directory to be a root" even mean? That's not English!

I am leaving this for future reference: 

This error is because we must pass a directory to the kubectl apply -k <kustomization_directory> (or kubectl kustomize <kustomization_directory>) command. For example : this 'k apply -k application/' works! and this k apply -k application/application/kustomize.yaml DOES NOT!!

Error message is confusing but the problem is simple :)

**Comment by gocpplua** [comment]
minio
├── argo-server-deployment.yaml
├── argo-server-sa.yaml
├── argo-server-service.yaml
└── kustomization.yaml


/data/kubernetes/k3s$ sudo k3s kubectl apply -k ./minio
serviceaccount/argo-server created
service/argo-server created
deployment.apps/argo-server created

**Comment by lugipfupf** [comment]
In case this might help someone else:
Running on a rather old 2.5.5 ArgoCD, we got the same error message. Reason was a `kustomization.yaml` with quite a lot of yaml references hiding a duplicate entry.
