### ISSUE TITLE
helmCharts doesn't support APIVersions

### ISSUE THREAD

**Issue by james-callahan** [kubernetes-sigs/kustomize#3816]
Similar to #3458

The new `helmCharts` feature (#3784) needs a way to pass in APIVersions.

CC @monopole

**Comment by Shell32-Natsu** [comment]
For every possible option that will be passed to helm we should have a field in the plugin config.

**Comment by monopole** [comment]
https://github.com/kubernetes-sigs/kustomize/issues/3815#issuecomment-825820444

**Comment by james-callahan** [comment]
.

**Comment by james-callahan** [comment]
hmm. why didn't @fejta-bot remove the stale label when I commented?

**Comment by natasha41575** [comment]
We will be supporting this in the [next iteration of the helm generator](https://github.com/kubernetes-sigs/kustomize/issues/4401).

**Comment by highb** [comment]
The lack of any way of specifying APIVersions or other data that is often required by charts (and not passable via values) seriously limits the utility of the `helmGenerator` for me. Given this limitation, it seems that the better long term solution is to use `helm template` to generate the manifests required against the cluster they will be deployed to and then check them in as a new `base` for Kustomize. Unfortunately, that defeats a lot of the purpose of making a Helm chart at all.

I'm eagerly awaiting the planned work to move `helmGenerator` out into it's own plugin so that the community can add missing features like these.

**Comment by james-callahan** [comment]
> I'm eagerly awaiting the planned work to move `helmGenerator` out into it's own plugin so that the community can add missing features like these.

https://github.com/mgoltzsche/khelm already exists
I suggest the current helm generator included with kustomize just gets dropped
