### ISSUE TITLE
Remove setters code from cmd/config and kyaml

### ISSUE THREAD

**Issue by phanimarupaka** [kubernetes-sigs/kustomize#4045]
Setters functionality is provided as a KRM function. We should remove code related to setters in cmd/config and kyaml.

**Comment by phanimarupaka** [comment]
@natasha41575 Let me know if you have cycles to pick this up.

cc @KnVerey

**Comment by natasha41575** [comment]
I have cycles to pick them up but also would like clarity on how to deprecate the commands `kustomize cfg create-setter` and `kustomize cfg set`.

Related: https://github.com/kubernetes-sigs/kustomize/issues/3953

Discussion there agrees with removing these commands.

**Comment by KnVerey** [comment]
> Since they are alpha, can we just remove them?

Great question. Any idea if there is precedent to follow here? Perhaps you're right and we can just remove them without warning in 5.0... or maybe even before then? Re: communication, a release note pointing to docs for the KRM function should suffice, I think.

>  it seems like we should only remove them when we are ready to do a major release. @KnVerey could you clarify the timeline?

The idea is to group together all the breaking changes we've been wanting to make into a single release, to minimize the number of times users have to engage with an update. Partly timeline depends on how we want to handle the Kustomization v1 project. Historically, it seems like breaking changes to Kustomization were made by incrementing the CLI major version instead of the Kustomization version. Since we're necessarily changing the Kustomization version with that project, I think the "right way" (higher effort) would be to have a CLI version that supports both beta and v1, and then eventually remove beta support in another major CLI version. We'll need to check with @monopole on that. The other thing CLI 5.0 timeline depends on is deprecation of flags--because those WILL need a proper deprecation cycle, given that the CLI is already GA.

**Comment by natasha41575** [comment]
The commands will be marked deprecated in the next release. We can remove the code as part of the kustomize CLI v5 release.

**Comment by natasha41575** [comment]
The setters code lives here I think: https://github.com/kubernetes-sigs/kustomize/tree/master/kyaml/setters2 and https://github.com/kubernetes-sigs/kustomize/tree/master/kyaml/fix/fixsetters.

Can someone investigate if we are still using the `setters2` package anywhere? If not, we can probably just take it out entirely.

**Comment by khrisrichardson** [comment]
I see a couple examples outside of kpt:

[fluxcd/image-automation-controller](https://github.com/fluxcd/image-automation-controller/blob/6827808a1aa8c31ae0c05366db8e90c011f6ebd2/pkg/update/filter.go#L24)
[rancher/fleet](https://github.com/rancher/fleet/blob/0a6cf6cb9278d00e743e79ed1884b19e1bc6ec74/internal/cmd/controller/controllers/image/update/setters.go#L16)

**Comment by natasha41575** [comment]
> Are still using them, They pinned these two into a specific kyaml version. If we decide to go for this removal then we can make a release note that this is actually removed on the next version since we already marked this as deprecated before.

SGTM!

**Comment by natasha41575** [comment]
Also a note, the issue itself should stay in "in progress" - "Needs LGTM" is just for PRs.
