### ISSUE TITLE
multiple matches: failed to find unique target for patch (possible bug)

### ISSUE THREAD

**Issue by messiahUA** [kubernetes-sigs/kustomize#4050]
I'm not sure whether this is a bug, so I'm first asking a question.
Here is the file structure https://github.com/messiahUA/kustomize:
```.
├── apps
│   └── app
│       ├── deployment.yaml
│       └── kustomization.yaml
└── env
    ├── base
    │   ├── app2
    │   │   ├── kustomization.yaml # includes "app" and patches metadata.name to "app2"
    │   │   └── patch.yaml
    │   └── kustomization.yaml # includes "app" and "app2"
    └── overlay
        ├── kustomization.yaml # includes "env" base and applies patches to "app" and "app2"
        ├── patch2.yaml
        └── patch.yaml
```
All the main points should be clear from the above tree.

I've tried with kustomize:
**{Version:kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 BuildDate:2021-06-30T22:49:26Z GoOs:linux GoArch:amd64}**

I expect that it should just work, but I get:
**Error: multiple matches for Id apps_v1_Deployment|~X|app; failed to find unique target for patch apps_v1_Deployment|app**

Obviously there is a clash between two "app" in the "env" base, but I have patched the name in the env base.

I've tried with **kustomize/v3.8.2** and it works, so either it is a bug or something changed fundamentally. I hope this can be fixed because logically this is very good structure and this problem breaks everything.

**Comment by messiahUA** [comment]
I've checked all 3.8.x version and the latest which works is 3.8.9. It breaks on 3.8.10.

**Comment by messiahUA** [comment]
@natasha41575 I've checked all commits and found that f71854a breaks this.

**Comment by natasha41575** [comment]
I'm not sure why your configuration was working to begin with.

A patch can (at least, is supposed to) refer to a resource by any of its previous names. So, when you try to patch your Deployment named `app`, the patch matches `app`, but it also matches `app2` because the resource was previously named `app`. The fact that it wasn't throwing an error before sounds like a bug with the old behavior. My guess is https://github.com/kubernetes-sigs/kustomize/commit/f71854a0c81a33fd296e4e504064251f59ddf32a#diff-867890f08da8fc61c6a7c1e194065fe2d018ba56bf0428e4d42cf363f52ac727L111 is the line that did this.

Usually when a base is being reused by multiple overlays, we expect that each overlay will make changes to the resource IDs to prevent clashes like this. We recommend something like this:

```
├── apps
│   └── app
│       ├── deployment.yaml
│       └── kustomization.yaml
└── env
    ├── base
    │   ├── app1
    │   │   ├── kustomization.yaml # includes "app" and patches metadata.name to "app1"
    │   │   └── patch.yaml
    │   ├── app2
    │   │   ├── kustomization.yaml # includes "app" and patches metadata.name to "app2"
    │   │   └── patch.yaml
    │   └── kustomization.yaml # includes "app1" and "app2"
    └── overlay
        ├── kustomization.yaml # includes "env" base and applies patches to "app1" and "app2"
        ├── patch2.yaml
        └── patch1.yaml
```

Essentially, I am suggesting symmetry in your layers, which will require another layer between app and your overlay, so that you can rename it "app1" and patch it without conflicts. Does this workflow suit your use case?

**Comment by messiahUA** [comment]
@natasha41575 **thanks a lot for the reply!** I've tried exactly what you've suggested and it works and I think it's good, the structure is even more consistent, although I would say it's probably not very logical from my perspective in terms of how replacements are done and it is counterintuitive (or maybe I'm "special" :).

I have also thought that the deal is with the structure and I've tried your suggestion without renaming app, but I'm wrong and I got the same error, so in the end one needs to create a separate layer AND rename the resource. It's not obvious because you expect that the only condition is to have unique names.

By the way, I've also noted in the docs that allowNameChange is false by default and I'm not setting it to true, but name replacement it works, so apparently it applies to some other situation.

Considering this is not a bug, but a feature this issue can be closed. THANKS

**Comment by natasha41575** [comment]
> By the way, I've also noted in the docs that allowNameChange is false by default and I'm not setting it to true, but name replacement works, so apparently it applies to some other situation.

I think this only applies to patchesStrategicMerge; I'll do some testing and update the docs.
