### ISSUE TITLE
Allow build, but disable standard output of manifest

### ISSUE THREAD

**Issue by benmorehouse** [kubernetes-sigs/kustomize#4107]
In the event that you are running `kustomize build` in a CI/CD platform, it's appropriate to want to be able to ensure that your overlay builds correctly, but not write the manifest to standard out. This can leak sensitive information to a UI.

A solution to this problem would be being able to run a `kustomize build`, but the only content written to standard out be error messages. 

If there are no errors, then the CLI should just output something along the lines of `kustomize build succeeded`

An example command for this would be:

```
$ kustomize build --disable-std-out
...
kustomize build succeeded!
```

**Comment by benmorehouse** [comment]
Would be very excited to put up a PR for this, should it be accepted as something appropriate to add at this time!

**Comment by natasha41575** [comment]
While I don't necessarily oppose the introduction of such a flag, I am curious why you would be unable to pipe the output to `/dev/null` instead?

e.g.
```
kustomize build > /dev/null
if [ $? -ne 0 ]; then
    echo "Error"
fi
```

**Comment by benmorehouse** [comment]
@natasha41575 that's honestly a good point, thanks for sending this!

I feel like this isn't as intuitive to someone though, unless they've got a solid understanding of bash scripting as well as kustomize. Idk if that's justification to build a feature necessarily. Wdyt?

For what it's worth, Kubectl also includes a mode like this using `--dry-run`, where it will validate the output, and only print out errors.

Another hard point to this pipe solution is that in my CI/CD scenario, I run multiple kustomize builds back to back:

```
kustomize build ./app/base
kustomize build ./app/overlays/production
kustomize build ./app/overlays/stage
```
and so on...

Having to plop this bash script in for each one of the build commands doesn't seem DRY.

**Comment by natasha41575** [comment]
> For what it's worth, Kubectl also includes a mode like this using --dry-run, where it will validate the output, and only print out errors.

The kubectl `--dry-run` option exists so that you can preview local changes to your configuration without applying those changes to your cluster. This is not really analogous, because kustomize never communicates with the cluster; the _only_ thing that kustomize does is write to output. 

IMO piping the output of the command is a very common thing to do and it is not unreasonable to expect users to do so. If you want something that will only print out errors, you can do

`kustomize build > /dev/null`, which will send `stdout` to `dev/null` and print out `stderr`. 

I can leave this issue open to see if there is more interest from others but I find it hard to justify a feature that can be done via piping.

**Comment by natasha41575** [comment]
https://thoughtbot.com/blog/input-output-redirection-in-the-shell

**Comment by natasha41575** [comment]
There doesn't seem to be any further interest in this feature from others, and I believe piping is a reasonable solution, so I'm closing this issue.
