### ISSUE TITLE
Kustomize edit panics when Kustomization file begins with document separator

### ISSUE THREAD

**Issue by avisiedo** [kubernetes-sigs/kustomize#4123]
**Describe the bug**

I get a panic when running `kustomize edit set namespace mynamespace`.

**Files that can reproduce the issue**

kustomization.yaml

```yaml

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: freeipa
```

**Expected output**

No panic message and the `namespace` field updated to `mynamespace`.

**Actual output**

```raw
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
sigs.k8s.io/kustomize/kustomize/v4/commands/internal/kustfile.(*kustomizationFile).parseCommentedFields(0xc0002e9140, 0xc000030c60, 0x5a, 0x60, 0x0, 0x0)
        /workspace/myClone/kustomize/commands/internal/kustfile/kustomizationfile.go:216 +0x7c5
sigs.k8s.io/kustomize/kustomize/v4/commands/internal/kustfile.(*kustomizationFile).Read(0xc0002e9140, 0xf66538, 0xc0002e9140, 0x0)
        /workspace/myClone/kustomize/commands/internal/kustfile/kustomizationfile.go:174 +0x14a
sigs.k8s.io/kustomize/kustomize/v4/commands/edit/set.(*setNamespaceOptions).RunSetNamespace(0xc000275940, 0xbcb760, 0xf66538, 0x1, 0x0)
        /workspace/myClone/kustomize/commands/edit/set/setnamespace.go:66 +0x65
sigs.k8s.io/kustomize/kustomize/v4/commands/edit/set.newCmdSetNamespace.func1(0xc000315080, 0xc000320420, 0x1, 0x1, 0x0, 0x0)
        /workspace/myClone/kustomize/commands/edit/set/setnamespace.go:41 +0xd0
github.com/spf13/cobra.(*Command).execute(0xc000315080, 0xc0003203e0, 0x1, 0x1, 0xc000315080, 0xc0003203e0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000308000, 0x0, 0xa12400, 0xc000030118)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /workspace/myClone/kustomize/main.go:14 +0x2a
```

**Kustomize version**

```raw
kustomize version
{Version:kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 BuildDate:2021-06-30T22:49:26Z GoOs:linux GoArch:amd64}
```

**Platform**

Linux

**Additional context**

Installed by:

```shell
curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
```

**Comment by avisiedo** [comment]
I have just realized I had a blank line at the beginning of the file. Removing that blank line into the `kustomization.yaml` file, make the command run as expected.

**Comment by KnVerey** [comment]
/assign @KnVerey 
/triage accepted
/retitle Kustomize panics when Kustomization file begins with document separator

**Comment by m-Bilal** [comment]
@KnVerey the panic happens because in this line
https://github.com/kubernetes-sigs/kustomize/blob/402f6ca72bd0d804d202376c39b5d8aeffbef8c6/kustomize/commands/internal/kustfile/kustomizationfile.go#L216 `len(mf.originalFields)` returns 0.
The reason for this is when the file begins with a blank line (or a comment) and a document separator immediately follows it, `len(comments)` is > 0 but `len(mf.originalFields)` is still 0, and since document separator does not match any field, it goes into the following `else if` condition
https://github.com/kubernetes-sigs/kustomize/blob/402f6ca72bd0d804d202376c39b5d8aeffbef8c6/kustomize/commands/internal/kustfile/kustomizationfile.go#L215
So, the kustomization files
```

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: freeipa
```
and
```
# This is a comment
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: freeipa
```
result in exactly same errors.

I was able to fix this by changing https://github.com/kubernetes-sigs/kustomize/blob/402f6ca72bd0d804d202376c39b5d8aeffbef8c6/kustomize/commands/internal/kustfile/kustomizationfile.go#L215 to `else if len(comments) > 0 && len(mf.originalFields) > 0`. Then `kustomize edit set namespace mynamespace` simply ignores the document separator and results are as follows:
```

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: freeipa
```
becomes:
```

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mynamespace
```
(the blank line is still there), and 
```
# This is a comment
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: freeipa
```
becomes
```
# This is a comment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mynamespace
```

 I'll raise a PR with this fix, if there's anything I missed or if it should be a different fix, please let me know.
