### ISSUE TITLE
Configuration-Value nameSuffix is ignored

### ISSUE THREAD

**Issue by JoachimBergt** [kubernetes-sigs/kustomize#4164]
Whatever pathes are set for the ConfigurationValue `nameSuffix` are ignored. Only the Pathes from  `namePrefix` are used for the Name-Transformer.

The Module `api/internal/target/kusttarget_configplugin.go` will just pass the ConfigurationParameter `nameSuffix` to `FieldSpecs` of `PrefixSuffixTransformer` (because the `plugin/buildin/prefixsuffixtransformer/PrefixSuffixTransformer.go` only supports one `fieldSpecs`-Array)

This means, that it is not possible to declare some pathes to only receive a Prefix OR a suffix, if both are configured.

I'm trying to expose the `namePrefix` and `nameSuffix` values automatically into a ArgoCD-Application Description. When I generate the `Application` with kustomize, I want to mirror the name-changes into `spec/source/kustomize/{namePrefix|nameSuffix}`

config.yaml

```
namePrefix:
- path: metadata/labels/prefix

nameSuffix:
- path: metadata/labels/suffix
```

test.yaml

```
kind: Test
metadata:
  name: test
  labels:
    prefix: ""
    suffix: ""
```

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
- config.yaml
resources:
- test.yaml

namePrefix: "pre-"
nameSuffix: "-suf"
```

**Expected output**
```
kind: Test
metadata:
  labels:
    prefix: pre-
    suffix: -suf
  name: pre-test-suf
```

**Actual output**

```
kind: Test
metadata:
  labels:
    prefix: pre--suf
    suffix: ""
  name: pre-test-suf
```

**Kustomize version**

3.9.4..4.3.0

**Platform**

Windows (3.9.4), Linux (4.3.0)

**Comment by droopy4096** [comment]
experiencing same issue:

* Fedora 34
* Kustomize 4.0.3

```
$ kustomize version
{Version:unknown GitCommit:$Format:%H$ BuildDate:1970-01-01T00:00:00Z GoOs:linux GoArch:amd64}
$ rpm -qa | grep kustomi
golang-sigs-k8s-kustomize-4.0.3-2.fc34.x86_64
```

**Comment by Serializator** [comment]
I experimented a bit with the `builtinhelpers.PrefixSuffixTransformer` factory by appending `tc.NameSuffix` to `tc.NamePrefix` as well as returning a separate transformer plugin for both the prefix and suffix.

I feel like prefixes and suffixes are too tightly coupled right now (as they are assumed to be applied to the same `FieldSpec`, though (as presented in this issue) this might not always be the case.

@KnVerey, I'm thinking of separating the "PrefixSuffixTransformer" into separate "PrefixTransformer" and "SuffixTransformer" transformers. I'm new to the Kustomize project (and contributing to Kubernetes SIGs in general) and am not sure if I'm missing something. What do you think?

**Comment by natasha41575** [comment]
> I'm thinking of separating the "PrefixSuffixTransformer" into separate "PrefixTransformer" and "SuffixTransformer" transformers. I'm new to the Kustomize project (and contributing to Kubernetes SIGs in general) and am not sure if I'm missing something. What do you think?

This is something I'd suggested offline and I would be happy to review a PR that does so. While they are very similar in what they do, at the end of the day people have different use cases for each and if it prevents bugs such as the one you've found I am in support of decoupling them. You're right that they assume the same fieldspecs:

https://github.com/kubernetes-sigs/kustomize/blob/2f115223cccfb8faeedb6fbcb382eff7296a4a24/plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer.go#L80-L84

Something that comes to mind though is that they have a lot of code in common; most of that code is in `api/filters/prefixsuffix/prefixsuffix.go`.  In an effort to prevent duplicating as much code as possible, I would suggest we keep the functionality of `api/filters/prefixsuffix/prefixsuffix.go` and have both the `PrefixTransformer` and the `SuffixTransformer` use the common code in `api/filters/prefixsuffix/prefixsuffix.go`. In fact, the more we can move into the filter, the better.

One caveat however is that in order to maintain backwards compatibility, we should still support the following use case:

kustomization.yaml
```
resources:
  - deployment.yaml

transformers:
  - config.yaml
```

config.yaml
```
apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: notImportantHere
prefix: baked-
suffix: -pie
fieldSpecs:
  - path: metadata/name
```

We would have to internally map such a case to the new separate `PrefixTransformer` and `SuffixTransformer` (and also have some regression tests for it).

**Comment by Serializator** [comment]
Thank you for the detailed and in-depth feedback @natasha41575! I made a really rough "prototype" in which I refactored the `PrefixSuffixTransformer` into separate transformers. I ran all tests and they all succeeded.

**But...** It works flawlessly only if the old `PrefixSuffixTransformer` is not added to builtin transformers within `target.configureBuiltinTransformers`.  If the builtin transformers contain all `PrefixSuffixTransformer`, PrefixTransformer` and `SuffixTransformer` then the prefix / suffix are applied twice.

Keeping the `PrefixSuffixTransformer` and making it re-use the `PrefixTransformer` and `SuffixTransformer` wouldn't solve this problem as the prefix / suffix would still be applied twice.

I think that the `PrefixSuffixTransformer` should only remain as a type (for backward compatibility purposes) which at the moment of parsing the `kustomization.yaml` (the `transformers` configuration) gets separated into a `PrefixTransformer` and `SuffixTransformer` (if applicable).

**Comment by Serializator** [comment]
It is 9 days ago that I posted the last status update and unfortunately I ran against a roadblock.

What I was trying to do is keep the "PrefixSuffixTransformer" type (`builtinhelpers.PrefixSuffixTransformer`) as kind of a "symbolic" or "virtual" reference but without an actual implementation (for backwards compatibility). Once I started deleting the implementation for this type some of the tests started to fail.

Why? Because the `kusttest_test.HarnessEnhanced` (if I remember correctly) when loading a transformer (e.g. `kind: PrefixSuffixTransformer`) it will try to find an `.so` file somewhere and throw an error if it can't find it. Thus a "symbolic" or "virtual" kind of approach won't work without a redo of the `kusttest_test.HarnessEnhanced` implementation and maybe much more.

I've tried an approach where I kept an implementation for the `PrefixSuffixTransformer` but made it reference the individual `PrefixTransformer` and `SuffixTransformer` but this wouldn't work because it uses JSON / YAML serialization and deserialization to get data into the structs of the transformers (the `PrefixTransformer` and `SuffixTransformer` structs can't be serialized and deserialized like this).

I might get away with adding some kind of factory to `resmap.PluginHelpers` to instantiate a `PrefixTransformer` and `SuffixTransformer` from the `PrefixSuffixTransformer` itself but I feel like this is too much of a hacky approach and I don't know if it will even work either.

@natasha41575, do you have an idea or opinion on this?

**Comment by KnVerey** [comment]
> Why? Because the kusttest_test.HarnessEnhanced (if I remember correctly) when loading a transformer (e.g. kind: PrefixSuffixTransformer) it will try to find an .so file somewhere and throw an error if it can't find it. 

Would you be able to share the specific error and some tests that cause it? I see that the test framework has a step where it generates those .so files, but it looks like it is triggered explicitly, e.g. by `PrepBuiltin("PrefixSuffixTransformer")`. My understanding (which could be incomplete) is that the harness is preparing the .so files so that they'll be there when `loadAndConfigurePlugin` tries to locate them, which it only does for built-ins if using `BpLoadingOptions: BploLoadFromFileSys` mode. That mode is used by default in the enhanced test harness for whatever reason, which means the builtins are being loaded as plugins rather than from the api module's copy. After your change, the PrefixSuffixTransformer could no longer be used as a plugin, since that code will not exist.

Ideas/discussion points:
- @natasha41575 do you think it is important to maintain the ability to use PrefixSuffixTransformer as a Go plugin? Especially since we are planning to deprecate Go plugins, I'm thinking we do not need to.
- If a relatively small number of tests are affected (i.e. only PrefixSuffix tests), perhaps we could change the `BpLoadingOptions` for those specifically?
- I'm not sure why `BploLoadFromFileSys` is the default. Maybe it would be workable to switch the default and treat them as plugins only in the tests within the plugins directory?

**Comment by natasha41575** [comment]
> do you think it is important to maintain the ability to use PrefixSuffixTransformer as a Go plugin? Especially since we are planning to deprecate Go plugins, I'm thinking we do not need to.

@KnVerey Long term, no, I don't think it's necessary to maintain it. But until we deprecate and remove Go plugins (at which point I'm also happy to deprecate and remove `PrefixSuffixTransformer`), I'm wondering about uses like:

```
transformers: 
- |- 
  apiVersion: builtin
  kind: PrefixSuffixTransformer
  metadata:
    name: notImportantHere
  prefix: baked-
  suffix: -pie
  fieldSpecs:
    - path: metadata/name
 ```

Do you think it's necessary to support this in the short term? And if so, is it possible to do so without using it as a Go plugin? 

> but this wouldn't work because it uses JSON / YAML serialization and deserialization to get data into the structs of the transformers (the PrefixTransformer and SuffixTransformer structs can't be serialized and deserialized like this)

@Serializator Why can't `Prefixtransformer` and `SuffixTransformer` structs serialize and deserialize data in the same way that the current `PrefixSuffixTransformer` does? What's different about them that prevents them from having largely the same implementation?

**Comment by KnVerey** [comment]
> Do you think it's necessary to support this in the short term? And if so, is it possible to do so without using it as a Go plugin?

It's probably best to keep it until v5 at least. We could also keep it indefinitely if the low-overhead implementation @Serializator is attempting ends up working out. I could see it being useful to be able to set prefixes and suffixes at once without having to repeat the fieldSpecs.

Since distributed Kustomize uses the truly built-in version, to the best of my understanding, we don't depend on the Go plugin version existing to make that work.

**Comment by Serializator** [comment]
> That mode is used by default in the enhanced test harness for whatever reason, which means the builtins are being loaded as plugins rather than from the api module's copy. After your change, the PrefixSuffixTransformer could no longer be used as a plugin, since that code will not exist.

@KnVerey, exactly. Below the error.

```
=== RUN   TestMatchesCurrentID
    plugintestenv.go:61: compile failed: cannot find source at '/home/jvdberkmortel/Ark/kubernetes-sigs/kustomize/plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer.go'
2021/11/30 01:07:04 compiler created: /home/jvdberkmortel/Ark/kubernetes-sigs/kustomize/plugin/builtin/replicacounttransformer/ReplicaCountTransformer.so
    harnessenhanced.go:179: Err: expected file with Go object code at: /home/jvdberkmortel/Ark/kubernetes-sigs/kustomize/plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer.so
--- FAIL: TestMatchesCurrentID (0.09s)
```

> Why can't Prefixtransformer and SuffixTransformer structs serialize and deserialize data in the same way that the current PrefixSuffixTransformer does? What's different about them that prevents them from having largely the same implementation?

@natasha41575, I was mistaken about the serialization / deserialization. It was something I struggled with but it wasn't about the serialization / deserialization but more about the different way that transformers are loaded normally versus in tests.

---

I was thinking of passing a factory (in this case for transformers) to the `prefixsuffixtransformer.PrefixSuffixTransformer` through `resmap.PluginHelpers` such that the `prefixsuffixtransformer.PrefixSuffixTransformer` could instantiate its own `prefixtransformer.PrefixTransformer` and `suffixtransformer.SuffixTransformer` and apply them as transformations.

What this would mean is no code-duplication in terms of logic for the prefix- and suffix transformers whilst keeping the `prefixsuffixtransformer.PrefixSuffixTransformer` such that the tests don't fail.

@KnVerey / @natasha41575, would this be a good approach or are there better options?

**Comment by natasha41575** [comment]
> I was thinking of passing a factory (in this case for transformers) to the prefixsuffixtransformer.PrefixSuffixTransformer through resmap.PluginHelpers such that the prefixsuffixtransformer.PrefixSuffixTransformer could instantiate its own prefixtransformer.PrefixTransformer and suffixtransformer.SuffixTransformer and apply them as transformations.

That approach sounds fine to me.

Though an implentation detail I'm curious about is why you need to pass in a factory to `prefixsuffixtransformer.PrefixSuffixTransformer`, could it not just directly instantiate its own `prefixtransformer.PrefixTransformer` with `NewPrefixTransformerPlugin()`? This is something we can discuss more when the PR is open, perhaps some of my questions will be answered in seeing the implementation. 

I think @KnVerey's suggestions are worth exploring:

> If a relatively small number of tests are affected (i.e. only PrefixSuffix tests), perhaps we could change the BpLoadingOptions for those specifically?
> I'm not sure why BploLoadFromFileSys is the default. Maybe it would be workable to switch the default and treat them as plugins only in the tests within the plugins directory?

I am in support of these changes, if it helps your tests to pass.

**Comment by Serializator** [comment]
@natasha41575, I'm sorry, I read them but totally forgot (it's 01:30 AM so that is probably why 😅). Will take a look at @KnVerey her suggestions / approach before moving on with the one I mentioned. Changing `BpLoadingOptions` would be less impactful and error-prone. Thanks for all the feedback and help by the way!

**Comment by KnVerey** [comment]
Looking at the specific test example you provided, it explicitly attempts to compile the PrefixSuffixTransformer plugin via `PrepBuiltin("PrefixSuffixTransformer")`. Do you still get an error if you remove that line from that (and other affected) tests? All that line is doing is asking for the plugin to be compiled, which we don't want/need anymore.

**Comment by Serializator** [comment]
@KnVerey, coincidentally I was just working on trying out your approach. It didn't work out-of-the-box by remove `th.PrepBuiltin("PrefixSuffixTransformer")` as the loading option was still `types.BploLoadFromFileSys`.

```
=== RUN   TestMatchesCurrentID                                                                                                                                                                 
    harnessenhanced.go:179: Err: expected` file with Go object code at: /home/jvdberkmortel/Ark/kubernetes-sigs/kustomize/plugin/builtin/prefixsuffixtransformer/PrefixSuffixTransformer.so     
--- FAIL: TestMatchesCurrentID (0.00s) 
```

I added the below line in addition to removing `th.PrepBuiltin("PrefixSuffixTransformer")` and (as far I as can tell) it works like you said. Thank you!

`th.GetPluginConfig().BpLoadingOptions = types.BploUseStaticallyLinked`

Please let me know if you have any other feedback in regards to the above, otherwise I will create a PR 👍🏼
