### ISSUE TITLE
Kustomize patch is not working correctly

### ISSUE THREAD

**Issue by ssuganth** [kubernetes-sigs/kustomize#4175]
My deploymentconfig under base folder:

  apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  #namespace: ssuganth-dev
  metadata:
    name: demoapi-dc
    #namespace: ssuganth-dev
    labels:
      app.kubernetes.io/part-of: demoapi-app
  spec:
    completionDeadlineSeconds: 1200
    replicas: 2
    selector:
      name: demoapi-dc
    strategy:
      type: Rolling
      maxSurge: 50%
      maxUnavailable: 0
    template:
      metadata:
        labels:
          dev-app: demoapi-app
          name: demoapi-dc
      spec:
        containers:
          - name: demoapi-dc
            image: image-registry.openshift-image-registry.svc:5000/ssuganth-stage/sampledemo-api:dev
            
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
            resources:
              limits:
                cpu: 10m
                memory: 64Mi
              requests:
                cpu: 10m
                memory: 64Mi
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - demoapi-dc
          from:
            kind: ImageStreamTag
            #namespace: "ssuganth-dev"
            name: 'sampledemo-api:dev'
  status: {}

My patch file:

  apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: demoapi-dc
  spec:
    template:
      spec:
        containers:
          - name: demoapi-dc
            resources:
              limits:
                cpu: 10m
                memory: 6400Mi

I need to update only the resources: -> limits: (cpu & memory) but not resources: -> requests (cpu & memory). The cpu & memory under requests must be same as in the base file.

When I execute the above patch over the base, the requests (cpu & memory) values are completely lost in the output. My expected behavior is should be present in output with same base value and only the resources limit cpu & memory must change as per the patch.

Can you someone explain this behavior and help?

**Comment by KnVerey** [comment]
/kind support
/triage not-an-issue

I can't say for sure without seeing the Kustomization, but given that `kind: DeploymentConfig` is a custom resource, I'm guessing your Kustomization isn't providing the schemas for it. Without the schemas, kustomize uses a default strategy for merging lists, which is not what you want for containers. You can provide schemas through the [openapi](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/openapi/) or [crds](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/crds/) features. I'd recommend the newer openapi method, since we have plans to deprecate crds (#3944).
