### ISSUE TITLE
develop Kustomize plugin to sign images within the manifests using cosign tool

### ISSUE THREAD

**Issue by developer-guy** [kubernetes-sigs/kustomize#4217]
**Is your feature request related to a problem? Please describe.**

It is not related to a problem, it is more like a new feature request.

**Describe the solution you'd like**

Recently, I came across a git repository called [sopsencodedsecrets](https://github.com/monopole/sopsencodedsecrets). Then, I searched for `Kustomize` plugins and realized that it is easy to develop plugins using Go for extending `Kustomize` [^1]. So, I'm proposing a new plugin called `sign-with-cosign-plugin` which helps us to sign all the images within the manifest files for Deployment, DaemonSet, Pod, etc by using `cosign` [^2].

**Additional context**
[^1]: [Extending Kustomize with Go Plugins](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/#go-plugins)
[^2]: [cosign](https://github.com/sigstore/cosign)

We (w/@dentrax @erkanzileli) are the volunteers to do this issue as well.

**Comment by KnVerey** [comment]
I'm glad to hear your interest in extending Kustomize! Please note that all extension mechanisms are still in alpha, and [Go plugins](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/go_plugins/) are currently slated for deprecation because of the issues described in the docs. If you move forward with this extension, I would encourage you to build it as a [container-based KRM function](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/containerized_krm_functions/) and help us improve that extension development experience with any feedback you may have.

You can find more information on the vision for Kustomize extensions in this provisional KEP: https://github.com/kubernetes/enhancements/issues/2953. 

Since this would be an extension, I don't think we need to keep a tracking issue open on this repo. Please reopen if I've misunderstood.
/close
