### ISSUE TITLE
helmChartInflationGenerator: Support multiple helm values files

### ISSUE THREAD

**Issue by jkroepke** [kubernetes-sigs/kustomize#4219]
**Is your feature request related to a problem? Please describe.**

I'm. using the helmChartInflationGenerator to combine multiple helm charts into one ArgoCD release

In my case, I have a ArgoCD Application, that contains:

* kube-prometheus-stack
* oauth-proxy
* Additional manifests like SealedSecrets

This the kube-prometheus-stack is a heavy value file, I would like to create a values.yaml file to the base and extend the values as needed for specific environments. This pattern works out of the box with helm by define multiple value files.

Currently, the helmChartInflationGenerator only allows to define one valueFile + valueInline.

**Describe the solution you'd like**

Support multiple value files inside the helmChartInflationGenerator.

Helm does support this by just running `helm template -f base/values.yaml -f stages/values.yaml`

**Describe alternatives you've considered**

Using a combination of valueFile and valuesInline, but this is going the be messy.

**Additional context**

**Comment by khrisrichardson** [comment]
@KnVerey does it sound reasonable that this may be a class of problem that becomes more tractable once the plugin composition effort you have proposed lands (e.g. - a HelmValuesMerge mutator that doesn't yet exist populates the valuesInline field of the HelmChartInflationGenerator, which is somehow late bound to a variant as opposed to being clumsily bound to a base where its evaluated too early in the cycle for any notion of a Helm values overlay to be effective or predictable if for example there were conflicting values in the Helm base or overlay, such that were they not passed to the Helm templating engine as a unit would yield non-deterministic results)? If not, would you deem that a worthy use case to consider for plugin composition? Thanks

**Comment by jkroepke** [comment]
Please do not implement an own yaml merge logic. It may incompatible with the helm values merge, since helm supports some [custom merge strategies](https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key). Implement an own logic would result in new bug reports from time to time.

I recommend to add an additional property valueFiles to the existing plugin `helmChartInflationGenerator`.  `valueFiles` should accept a list or array of file paths. When executing the helm template command, pass all value files to the helm command `helm template . -f file1 -f file2`. For future, deprecate `valueFile` and remove it in kustomize v5.

Additionally, in case kustomize would pass the file path to helm, it would enable the support for [downloader plugins](https://helm.sh/docs/topics/plugins/#downloader-plugins).

I understand, downloading value files from remote location can result in non-deterministic results. But there are plugins like [helm-secrets](https://github.com/jkroepke/helm-secrets) which using the plugin downloader mechanic to decrypt encrypted files which can be live in the same repository as the kustomization.yaml itself.

**Comment by khrisrichardson** [comment]
Hi @jkroepke. I didn't mean to discount your original request. I can see the utility in permitting multiple values files, but the mention of a HelmValuesMerger was meant to be illustrative, not prescriptive, and could easily take the form of coalescing a list of values files and/or merging valuesInline.

The main point I was trying to drive home is how @pbecotte's assertion regarding values in both bases and overlays illustrates the exceptional nature of the helmChartInflationGenerator, which does not allow for neat layered encapsulation like other mutators, but instead would need to operate in a lazily evaluated manner to address [his comment](https://github.com/kubernetes-sigs/kustomize/issues/4219#issuecomment-942711457). If plugin composition were to take this use case into consideration, the burden on the end user could be minimized.

I have attempted to merge valuesInline with partial success by presenting the HelmChartInflationGenerator in the base as a resource and using PatchTransformer in overlays to merge the valuesInline fields. The effort could have been streamlined if multiple values files were supported instead. The problem with this approach was that patching the HelmChartInflationGenerator resource from the base in an overlay, did not make it any more amenable for consumption by the overlay, since the base also used the generator by design and GVKN conflicts ensued in the overlay.

Such is the type of problem one encounters when dealing with templating. They should write a tool or two that composes bases and variants to produce overlays, so we can stop this templating madness. :)

**Comment by pbecotte** [comment]
You'll see that I wound up with the same solution...using patches on the valuesInline field to pass transformer and generator configuration up the stack. I opened a ticket related to this as well.

I had the same thought about the helm values resource and actually cloned this repo to take a shot at implementing.  I quickly realized I don't follow the code base well enough, but have some observations.

1. The values file is relative to the LAST kustomize root, same for chart home. Makes it very interesting composing complicated overlays.
2. I wanted to have patches for the helm chart objects in the base- in order to work the patches will have to be lazy evaluated as well as the chart generator (otherwise the resources won't exist)
3. I wanted to add values.yaml, resources, and patches in components. Again, none of the transformers should run before the chart generator.  Except ones that target the chart generator itself.

Allowing me to specify multiple values files would let me hack it together more easily though,  by just including the generator in the last kustomize and pulling in extra values files instead of overlays. So it may be less correct...but would definitely be easier to implement

**Comment by pbecotte** [comment]
I just reread my comment and realized- what I was trying to say is "multiple values files doesn't help with the hard problems - but its an easy change that will at least help with SOME problems"

**Comment by natasha41575** [comment]
We will be supporting this in [our next iteration of the helm generator](https://github.com/kubernetes-sigs/kustomize/issues/4401).

**Comment by jkroepke** [comment]
unstable

**Comment by wmiller112** [comment]
Not sure if this fits here exactly, but I came across this and a few similar issues trying to work out how I could patch helm values in either valuesInline of valuesFile. Seems its not _directly_ supported, but I did find a workaround I haven't seen mentioned. 
I've created two directories:

`envs/` can contain a directory for  each env you wish to deploy to -  optionally a base that they reference. The env (and base) can define some resources, and patch resources that will be generated by our helm chart.  In each of the env's kustomization.yaml files, instead of pointing directly to a `HelmChartInflationGenerator`, we can point to another kustomize directory and generate it dynamically.

`helm/` has a base that contains a `HelmChartInflationGenerator` defines the chart, repo, name, version, and some valuesInline. The kustomization.yaml references this as a **resource**, not a generator. Then `helm/` can also contain some patch dirs that strategicmerge or json patch the valueInline of the `HelmChartInflationGenerator`.

The `envs/<env>/kustomization.yaml`  `generators` points to `helm/<patch>/`, and the resulting valuesInline are patched as needed. Note this does require `--load-restrictor=LoadRestrictionsNone` - I haven't tried it, but pretty sure nesting to try to keep within load-restrictor boundary would result in cycle error.

**Comment by wmiller112** [comment]
Not sure if this fits here exactly, but I came across this and a few similar issues trying to work out how I could patch Helm values in either `valuesInline` of `valuesFile`. Seems its not _directly_ supported, but I did find a workaround that doesn't involve too much repetition. This [demo repo](https://github.com/wmiller112/kustomize-helm-values) shows how you can point the `generator` to another kustomize directory that patches a `HelmChartInflationGenerator` as a resource.

**Comment by envyj020** [comment]
> Not sure if this fits here exactly, but I came across this and a few similar issues trying to work out how I could patch Helm values in either `valuesInline` of `valuesFile`. Seems its not _directly_ supported, but I did find a workaround that doesn't involve too much repetition. This [demo repo](https://github.com/wmiller112/kustomize-helm-values) shows how you can point the `generator` to another kustomize directory that patches a `HelmChartInflationGenerator` as a resource.

@wmiller112 is your example supposed to merge the `valuesInLine` between the base `HelmChartInflationGenerator` and the patched one? because It didn't work for me.

**Comment by aaronborden-rivian** [comment]
👋 I am absolutely in favor of implementing this feature and ask that this Helm chart example be clarified as part of this work.

The [Helm chart inflation example](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md#performance) seems to be advocating against this feature. Instead, it promotes inflating the chart manually and committing that to the repository and not rely on using remote third-party configuration at all.

 Maybe we can remove this document?
