### ISSUE TITLE
Add env vars to --enable-helm (or all?) flags

### ISSUE THREAD

**Issue by snuggie12** [kubernetes-sigs/kustomize#4286]
**Is your feature request related to a problem? Please describe.**
We use argocd and have various applications on different versions of kustomize. Since we added 4.2.0 we're unable to properly do diffs since it doesn't know which options to download and `--enable-helm` breaks 3.x apps.

Could we get an environment variable for `--enable-helm`? The earlier versions won't do anything with it if it is set but the versions that support it will.

I tested following https://github.com/carolynvs/stingoftheviper/blob/main/main.go and I think as implemented all `kustomize build` flags get an env var for free as long as they start with `KUSTOMIZE_BUILD_`.

**Describe the solution you'd like**
Use spf13/viper to load in my one flag or all flags related to `kustomize build` as an env variable.

**Describe alternatives you've considered**
I would be okay if there was a way inside of `kustomization.yaml` to enable helm. My understanding is that it is an acknowledgement of sorts that you're running something external so perhaps it could only be restricted to local bases?

I mostly went with env vars because it was something I knew I could grasp within kustomize's code base. If there are other suggestions I'm all for it.

**Additional context**
https://github.com/argoproj/argo-cd/issues/5532

**Comment by natasha41575** [comment]
We cannot put the enablement of helm in an environment variable; it needs to be a flag because there are security risks and we need to be certain that the user intends to enable it when they are running kustomize. However, we are hoping to move towards a solution where helm will not need to be treated with special flags, you can see the details here:

https://github.com/kubernetes-sigs/kustomize/issues/4401
