### ISSUE TITLE
Support helm authentication for helm chart repositories.

### ISSUE THREAD

**Issue by ArthurCieslik** [kubernetes-sigs/kustomize#4335]
When using helmCharts in kustomize, helm chart repositories authentication is not supported.
Further, kustomize prevents the helm credentials storage and usage due to the way kustomize is using helm.

**Example:**

In a case like this:

````
helmCharts:
- name: minecraft
  repo: https://itzg.github.io/minecraft-server-charts
````

Kustomize uses to download the chart a helm command like this

````
helm pull minecraft --repo https://itzg.github.io/minecraft-server-charts
````

Helm supports credentials to chart repositories via parameters or it's own repository management. You can template, install or pull a helm chart via a secured repository either by

````
helm pull helmChart --repo https://secured.com/chartrepo --username <username> --password <password>
````

or adding a repository to the helm configuration including the repository credentials

````
helm repo add securedRepo https://secured.com/chartrepo --username <username> --password <password>
helm pull securedRepo/helmChart
````

**Issue**:

Kustomize is not supporting the handover of repository credentials, but it is also prevents the usage of helm repository management by making the field 'repo' mandatory.
It is an optional field in the kustomize yaml but in such case the repo parameter is set during the helm command anyway, which prevents helm to look into it's own repository configuration:

**Solution**:

Make the 'repo' field optional, since the repository can be predefined in a helm configuration and the repository name becomes part of the chartName:

````
helmCharts:
- name: chartRepoName/minecraft
````

Alternatively introduce an repoName field in the kustomize helmCharts section where repoName becomes part of the helm command:

````
helm pull repoName/name
````

**Comment by snuggie12** [comment]
This is pretty easy to fix, but I have quite a few (newb) questions before I could throw out a PR:
- How do I get a fork into my gopath? Do I just create the fork, create the dirs in `src` and then `git clone`??
- Do the maintainers even want this change? The functionality used to be there but was removed in 4.x
- Does helm support other protocols besides http(s)?? If so, should I change the regex to a made up one like `repo://`??
- I suppose it could wait until the PR but I really have no clue whether creating that variable or appending `fmt.Sprintf` is better. Same goes for my syntax on the if condition (not a developer)

tested diff:
```
diff --git a/api/internal/builtins/HelmChartInflationGenerator.go b/api/internal/builtins/HelmChartInflationGenerator.go
index 2a654ad1f..11308139e 100644
--- a/api/internal/builtins/HelmChartInflationGenerator.go
+++ b/api/internal/builtins/HelmChartInflationGenerator.go
@@ -290,9 +290,13 @@ func (p *HelmChartInflationGeneratorPlugin) pullCommand() []string {
        args := []string{
                "pull",
                "--untar",
-               "--untardir", p.absChartHome(),
-               "--repo", p.Repo,
-               p.Name}
+               "--untardir", p.absChartHome()}
+       if match, _ := regexp.MatchString("^https?://", p.Repo); match == true {
+               args = append(args, "--repo", p.Repo, p.Name)
+       } else {
+               repoName := p.Repo + "/" + p.Name
+               args = append(args, repoName)
+       }
        if p.Version != "" {
                args = append(args, "--version", p.Version)
        }
```

PS It appears as if `helm pull` is broken in another way in 4.X+. It no longer downloads the chart to a temp dir if you specify `helmGlobals.configHome`. If that issue doesn't exist I'll file that one separately.

**Comment by natasha41575** [comment]
We will be supporting this in [our next iteration of the helm generator](https://github.com/kubernetes-sigs/kustomize/issues/4401).

**Comment by QuinnBast** [comment]
I am now facing this issue as well. It seems like the helm chart inflator is non-functional after the helm v3 release.

[Since oci registry support is not functional](https://github.com/kubernetes-sigs/kustomize/issues/4381), I attempted to use a chartmuseum repository instead to hopefully make this tool work using a non-oci protocol. However, I ended up running into this issue. I was unable to add a repo with the saved credentials through `helm repo add`, nor was I able to specify `helmCommand` to be a command that contained the desired flags for the helm pull command (something like `--helm-command helm --ca-file <pathToFile>`).

In the issue I linked above I proposed a similar change to the one outlined in @snuggie12 's comment. I would love to see these changes get applied as this would eliminate a TON of bash scripting that we currently have around deployment.

**Comment by tis-rpage** [comment]
I think this is a bit of a mis-feature, as authentication can be established with repositories prior to kustomize being involved, ala `helm login`.

**Comment by minnie-jeong-otsk** [comment]
It might be a silly question, but in which pod should I do :
`helm repo add securedRepo https://secured.com/chartrepo --username <username> --password <password>`

I see lots of pods like: argocd-repo-server, argocd-server, argocd-redis-ha-server, ... 

Or can I do helm repo add setting somewhere in yaml file? If so, where it would be?

**Comment by QuinnBast** [comment]
> It might be a silly question, but in which pod should I do : `helm repo add securedRepo https://secured.com/chartrepo --username <username> --password <password>`

You shouldn't have to run this in a pod. You should just need to run it on your local machine where you are running the `helm` commands. However, even if you do that the `helmCharts` inflator within Kustomize does not work (which is why this issue is open).

**Comment by tis-rpage** [comment]
The environment variable for HELM_REGISTRY_CONFIG can be specified so that the registry authentication is available to kustomize, and the pod can mount the authentication secrets into the namespace in an appropriate location thereby negating the need for this ticket.

**Comment by snuggie12** [comment]
> The environment variable for HELM_REGISTRY_CONFIG can be specified so that the registry authentication is available to kustomize so it's inherited by the helm subshell, and the pod can mount the authentication secrets into the namespace in an appropriate location thereby negating the need for this ticket.

Could you supply a working example including versions of kustomize and helm plus all relevant yaml and config files?

The problem as I know it is that beginning in 4.x of kustomize the api for a helm chart was reduced and when a "helm pull" is initiated it doesn't have the correct format to pull from a repo that is locally stored and had no capability of providing a username and password to a straight URL.

**Comment by tis-rpage** [comment]
HELM_REGISTRY_CONFIG uses the same json format pioneered by DOCKER_CONFIG. If you run a `helm login` it'll generate `${XDG_CONFIG_HOME}/helm/registry.json` which you can then mount into your pod and set the HELM_REGISTRY_CONFIG variable to point to the mounted file. Then when `kustomize` executes, it'll inherit the HELM_REGISTRY_CONFIG and the `helm pull` subshell will have the same environment and be able to get the authentication details.

**Comment by cconnert** [comment]
> `HELM_REGISTRY_CONFIG` uses the same json format pioneered by `DOCKER_CONFIG`. If you run a `helm login` it'll generate `${XDG_CONFIG_HOME}/helm/registry.json` which you can then mount into your pod and set the HELM_REGISTRY_CONFIG variable to point to the mounted file. Then when `kustomize` executes, it'll inherit the HELM_REGISTRY_CONFIG and the `helm pull` subshell will have the same environment and be able to get the authentication details.

Thanks. However I would also like to request a working example. First of all at my system I don not find the `${XDG_CONFIG_HOME}/helm/registry.json`. Instead I do have a `${XDG_CONFIG_HOME}/helm//repositories.yaml`. Setting `HELM_REGISTRY_CONFIG` to point to that leads to:
error: WARNING: invalid character 'a' looking for beginning of value
Thus I converted the yaml into a json but still the `helm pull ...` fails. 
Further I would like to know how I can set that environment variable with the `-e or --env` argument, as this has no effect in my case. I am on helm 3.7.0 and kubectl 1.23.5. Thanks!

**Comment by tis-rpage** [comment]
Don't try to hand create the file contents, use `helm login` to generate the contents. It should look something like this:
```json
{
    "auths": {
        "<AWSACCOUNTIDGOESHERE>.dkr.ecr.us-east-1.amazonaws.com": {
            "auth": "<BASE64encodedAUTHSTRING>"
        },
        "<OCIREGISTRY>.example.com": {
            "auth": "<BASE64encodedAUTHSTRING>"
        }
    }
}
```
The BASE64encodedAUTHSTRING is roughly this format:
`<USERNAME>:<BASE64encodedPAYLOAD>`
with BASE64encodedPAYLOAD for my AWS creds being:
```json
{
    "payload": "<BASE64encodedBINARY>",
    "datakey": "<BASE64encodedBINARY>",
    "version": "2",
    "type": "DATA_KEY",
    "expiration": "<INTEGER_OFFSET>",
```

**Comment by snuggie12** [comment]
Sorry, I have been away from work and hadn't gotten a chance to clear this up.

@tis-rpage As I said above, it is not about the authentication. It's the format of the `helm pull` command. If you look at my working [diff](https://github.com/kubernetes-sigs/kustomize/issues/4335#issuecomment-1002868034) and take the example of using the old `stable` repo and we'll say `prometheus` chart you'll see in the current version it performs:

`helm pull --untar --untardir /Users/snuggie-12/...omitted... --repo stable prometheus`

when it should be:

`helm pull --untar --untardir /Users/snuggie-12/...omitted... stable/prometheus`

I think what's important is that this is going to get fixed in #4401 and [the kep for the registry](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/2985-public-krm-functions-registry#kep-2985-public-krm-functions-registry).

@natasha41575 are the features for the new helm plugin specifically tracked? I haven't seen one yet.

@QuinnBast thanks for also including my code in your patch and release! I know you were more focused on `oci` so I appreciate it. I'll give it a shot in the next day or two.

**Comment by tis-rpage** [comment]
> @tis-rpage As I said above, it is not about the authentication. It's the format of the `helm pull` command. If you look at my working [diff](https://github.com/kubernetes-sigs/kustomize/issues/4335#issuecomment-1002868034) and take the example of using the old `stable` repo and we'll say `prometheus` chart you'll see in the current version it performs:
> ...
> I think what's important is that this is going to get fixed in #4401 and [the kep for the registry](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/2985-public-krm-functions-registry#kep-2985-public-krm-functions-registry).

QuinnBast already opened up #4381 specifically to address OCI connections. My comments on this ticket are regarding authentication, which kustomize/helm already support via external authentication passed in via secured files and environment variable references.

In general, putting credentials on the command line is poor practice, as it exposes credentials via `/proc/$$/cmdline`. Therefore I recommend removing any capability from patch submission to continue to discourage poor practices.

**Comment by snuggie12** [comment]
> 
> If you pre-seed `charts/mychart` with your expanded repo, you can reference it via kustomize.
> 

I think "pre-seed" is where the disconnect may be. A lot of issues created around the future of helm chart inflation with kustomize are about running it in a gitops environment like argocd. There's no chance to run `helm login` or the `helm pull` you listed above.

**Comment by tis-rpage** [comment]
Most workflows allow you to have a `pre:` stage for this type of use-case, I'd be surprised if ArgoCD is glaringly deficient in that regard. I believe ArgoWorkflows supports this kind of concept, though it's likely not as opinionated as ArgoCD.

**Comment by remidebette** [comment]
Hi all,
I am not able to make the `HELM_REGISTRY_CONFIG` workaround work for a Harbor authenticated Helm repository. (401)

The `kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: <CHARTNAME>
    version: <some version>
    repo: https://<host>/chartrepo/<repo>
    valuesFile: values-develop.yaml
    namespace: argocd
    releaseName: ...

```

I see that the helm command ran behind the scenes is : 
```sh
HELM_REGISTRY_CONFIG=/.../registry.json helm pull --untar --untardir <some path>/<CHARTNAME>/charts --repo https://<host>/chartrepo/<repo> <CHARTNAME> --version <some version>
```

Instead, in my case I can generate a `HELM_REPOSITORY_CONFIG` that works with an Harbor username and API key.
When you do that, one can then use a repository name instead of the url `https://<host>/chartrepo/<repo>`

But then the helm command that would works should not have `--repo` 
```sh
HELM_REGISTRY_CONFIG=/.../registry.json helm pull --untar --untardir <some path>/<CHARTNAME>/charts  <repository name>/<CHARTNAME> --version <some version>
```

Hence I tried to remove the repository url in the `kustomization.yaml` like so:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: <repository name>/<CHARTNAME>
    version: <some version>
    repo: null
    valuesFile: values-develop.yaml
    namespace: argocd
    releaseName: ...
```

Alas, I get the following error:
```sh
Error: no repo specified for pull, no chart found at ''
```

Am I missing anything?

**Comment by QuinnBast** [comment]
@remidebette Yeah, that is the entire purpose of this issue and [this issue](https://github.com/kubernetes-sigs/kustomize/issues/4381). In the linked issue I've created a binary which contains the fix although it is not officially supported.

**Comment by jmmclean** [comment]
@natasha41575 it looks like the code specifically for this is here - https://github.com/kubernetes-sigs/kustomize/blob/master/plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go#L235-L238

I wish i had more Golang expertise to properly contribute, but is there a way we can make the `--repo` flag optional if `repo/chartname` is supplied for the name? I believe this would satisfy the request by @remidebette .

**Comment by QuinnBast** [comment]
@jmmclean
[This diff](https://github.com/kubernetes-sigs/kustomize/compare/master...QuinnBast:kustomize:helm3Fix) should work.

I also [released an unofficial patch](https://github.com/kubernetes-sigs/kustomize/issues/4381#issuecomment-1088817267) for this a few months ago

**Comment by LucasMaciuga** [comment]
Would be great to hear some news about this topic and what speaks against the fix @QuinnBast provided?

Also what I don't understand how to use/implement the [render-helm-chart from krm-functions-registry](https://github.com/kubernetes-sigs/krm-functions-registry/tree/main/krm-functions/sig-cli/render-helm-chart). I have understood that it is [here](https://github.com/kubernetes-sigs/kustomize/issues/4401) mentiond as the new home of the "helm-chart generator plugin", but I have no clue how to use it.

**Comment by gritzkoo** [comment]
I'm getting the same issue trying to use a private helm repository using Github.
Locally, to download the helm repo, I need to use the command:

```sh
helm repo add my-private-repo https://my-corp.github.io/my-private-helm \
  --username some-one \
  --password $GITHUB_TOKEN \
  --pass-credentials
helm pull my-private-repo/my-chart
```

It would be great if kustomization installation/config accepted global credentials to be used in all helm contexts using the flags like `--username --password --pass-credentials`. The flag `--pass-credentials` is essential because using GitHub pages to host helm `index.yaml` with a `https://raw.githubusercontent.com` DNS to download artifacts needs the authentication context to pass through the credentials used in helm to Github

**Comment by remidebette** [comment]
Hi,
I concur about this issue.

We use micromamba in a Docker multistaging context to optimise our build time and images size.

This will be a pain for us to include rapids

**Comment by KnVerey** [comment]
/triage out-of-scope
/kind feature
/close

This will be supported in the new KRM Function implementation, but is out of scope for the current Kustomize built-in:
https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/helmcharts/#long-term-support

**Comment by QuinnBast** [comment]
Wait, this got closed?

That is very disappointing... This makes Kustomize completely unusable to me as we need to use the `helmCharts` block on a locally hosted private registry but have no way of doing so.

The Helm long-term plan has had no action in over 2 years so it's sad that such a simple feature as logging in to a helm registry is "out of scope"...

**Comment by QuinnBast** [comment]
Hey @isarns 

I have not. Our solution is to just do:

```
helm repo add my-private-repo https://someURL --username username --password password
helm pull my-private-repo/someChart --version 0.0.1
```

And commit the pulled helm chart to the repo... :/

But because ArgoCD has git clone timeout limits and they have not yet implemented shallow clones, we had to make an entirely seperate git repo just to maintain this... It's quite annoying to say the least.

**Comment by isarns** [comment]
Hey @QuinnBast, thanks for your reply!

I’m a bit concerned that this approach feels like it’s just creating a monorepo—a pattern we’ve been trying to avoid.

In my case, I ended up forking kustomize to add an additional helm pull behavior. For example, with this configuration:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: saved-repo-name
    version: 0.0.1
    name: package-name
    namespace: test
    releaseName: test
    valuesFile: "values.yaml"
```

Notice that the `repo` field doesn’t begin with `https://`, `http://`, or `oci://`. Instead, my patch directs it to a local `repositories.yaml` file, where credentials are looked up and used for authentication. This works fine on my local machine—provided that `repositories.yaml` has been populated via `helm repo add`.

However, when I later deployed the new kustomize binary as a custom tool on the ArgoCD repo server, I discovered that ArgoCD doesn’t persist helm credentials in a `repositories.yaml` file. Instead, it loads them dynamically each time `argocd helm` is executed.

At this point, I’m somewhat stuck, but I’ve been considering a couple of options:

1. **Submit a PR to kustomize:** If my changes get merged and released, we might be able to mount a `repositories.yaml` on the ArgoCD repo server. I’d also look into using the [GitHub App Secret Generator](https://external-secrets.io/latest/api/generator/github/) to create and mount the necessary secret.

2. **Develop a custom plugin:** Another idea is to build a plugin that uses `envsubst` to substitute environment variables in kustomize manifests—for example, transforming a repo entry like:
   ```
   repo: https://git:$ARGOCD_VAR_READ_ONLY_PAT@raw.githubusercontent.com/my-org/my-private-helm-repository/main/
   ```
   I’m still exploring this possibility.

I also briefly considered adding an authentication key directly to the helmCharts configuration, but it appears that using environment variables in kustomize is impossible without external tools, so it would simply expose secrets.

I’d appreciate your thoughts and any feedback from the community on which approach might be best.

Thanks again!

**Comment by isarns** [comment]
Hi everyone,  

I previously submitted a PR (#5864) that removed the temporary Helm config and added support for pulling with the repository name. However, it was closed because Kustomize needs to ensure consistent behavior across all environments, avoiding different outcomes based on the setup.  

From my understanding, Kustomize does not intend to support private Helm repositories or use existing Helm credentials stored in the Helm config directory—at least not without the temporary config directory.  

Would it be possible to introduce a flag that explicitly allows Kustomize to use the system's Helm configuration or pass in credentials? This way, authentication could happen before running `kustomize build`.  

I was particularly excited to see this https://github.com/helm/helm/pull/9760)](https://github.com/helm/helm/pull/9760, as it could potentially resolve this issue **if** Kustomize leveraged the system’s Helm config.  

@KnVerey, would it be possible to reopen this discussion? Kustomize is the de facto choice for GitOps (especially with ArgoCD), and this feature would be incredibly valuable for many users.  

Looking forward to your thoughts! Thanks for your time.

**Comment by QuinnBast** [comment]
> The next iteration of the helm inflation generator will take the form of a KRM function, which will have no such restrictions on what types of features we can add and support. You can see more details in the [Helm support long term plan](https://github.com/kubernetes-sigs/kustomize/issues/4401).

So uh... it's been 4 years... What is going on here? Still no support for private registries? #4401 hasn't really had much going on either...

@natasha41575 maybe?

**Comment by tis-rpage** [comment]
> > The next iteration of the helm inflation generator will take the form of a KRM function, which will have no such restrictions on what types of features we can add and support. You can see more details in the [Helm support long term plan](https://github.com/kubernetes-sigs/kustomize/issues/4401).
> 
> So uh... it's been 4 years... What is going on here? Still no support for private registries? [#4401](https://github.com/kubernetes-sigs/kustomize/issues/4401) hasn't really had much going on either...
> 
> [@natasha41575](https://github.com/natasha41575) maybe?

I think the project is functionally a deadend and consider Kustomize and Helm incompatible. Since I last commented on this post, they introduced a breaking change to kustomize helm rendering such that it internally adds annotations and breaks the original behavior of the builtins operating on the helm templated output. This means even if you can connect kustomize to an external Helm repository, you can no longer modify those resources without breaking some internal mechanisms that kustomize depends on for tracking resources.

So imagine running a kustomize build and expecting to modify the namespace of all the generated helm objects that don't specify a namespace by default. Can't be done without some severe abuse of internal annotations or magic prefixing to make various plugins target keys they weren't designed to like prefixsuffix or label annotations.

So while it'd be nice if Kustomize added Helm OCI support, I think it's better to stop the use of Kustomize altogether. It had an admirable goal, but it's not well maintained, doesn't follow semver and is happy to break existing capability to foster "declarative first" even if we messed up on that separation earlier on the apps design life.

From a practical standpoint, using FluxCD and KRO in-cluster provide a much better experience than Kustomize+Helm ever could.
FluxCD HelmReleases can point at OCI repositories and the auth mechanism has some insight behind it.
