### ISSUE TITLE
kustomize edit add generator

### ISSUE THREAD

**Issue by lack** [kubernetes-sigs/kustomize#4343]
**Is your feature request related to a problem? Please describe.**

When I have a large number of generators in a directory, it is cumbersome to add them all to kustomization.yaml by hand.

**Describe the solution you'd like**

Just like is already available for transformers, I would like the "kustomize edit add" command to support adding generators by wildcard.

Probably "kustomize edit remove generator" should be added too for consistency.

**Describe alternatives you've considered**

Writing my own script that does this.

**Comment by natasha41575** [comment]
Are you envisioning something similar to `kustomize edit add resource`? As in, if I do `kustomize edit add generator gener.yaml`, my kustomization.yaml file will be updated to contain the following:

```
generators:
- gener.yaml
```

If my understanding of the feature request is correct, I don't have any objections to this command being added to kustomize as a feature, especially since we already have a `kustomize edit add transformer` field that does exactly the same thing with the `transformers` field.

I would be happy to review and potentially accept a PR that implements this. If anyone is interested, you can look at the code in [kustomize/commands/edit/add/addtransformer.go](https://github.com/kubernetes-sigs/kustomize/blob/master/kustomize/commands/edit/add/addtransformer.go) and copy most of the implementation from there - just change `Transformers` to `Generators`. 

/triage accepted
/kind feature
/label help wanted

**Comment by lack** [comment]
> Are you envisioning something similar to `kustomize edit add resource`? As in, if I do `kustomize edit add generator gener.yaml`, my kustomization.yaml file will be updated to contain the following:
> 
> ```
> generators:
> - gener.yaml
> ```

Exactly what I meant :)

> If my understanding of the feature request is correct, I don't have any objections to this command being added to kustomize as a feature, especially since we already have a `kustomize edit add transformer` field that does exactly the same thing with the `transformers` field.
> 
> I would be happy to review and potentially accept a PR that implements this. If anyone is interested, you can look at the code in [kustomize/commands/edit/add/addtransformer.go](https://github.com/kubernetes-sigs/kustomize/blob/master/kustomize/commands/edit/add/addtransformer.go) and copy most of the implementation from there - just change `Transformers` to `Generators`. 

Thanks!  I may give it a shot myself, time permitting...

**Comment by natasha41575** [comment]
I have created the PR for this feature here https://github.com/kubernetes-sigs/kustomize/pull/4361

**Comment by jgato** [comment]
was this finally included? it seems an interesting feature, why we cannot add other resources but no generators with the edit add?
