### ISSUE TITLE
Control component ordering

### ISSUE THREAD

**Issue by chicocvenancio** [kubernetes-sigs/kustomize#4345]
**Is your feature request related to a problem? Please describe.**

Currently components are applied as a first step of any layer. That means any changes made by other transformers/generators are not available to it. This complicates a few patterns if a component is needed.

EG:
A diamond pattern like https://github.com/kubernetes-sigs/kustomize/blob/ec38bbeb999066abea59fd11c54e68377765a510/api/krusty/diamonds_test.go with components at kirk would fail if the components tries to reference `kirk-storefront` or `spec.type`. This means a new layer would be necessary to allow for components to be used, for each leg of the diamond (we have over 90 in our setup).

**Describe the solution you'd like**
Control to apply the component at the same level their operations would be applied if not in component, first or last. Perhaps a new field?

**Comment by KnVerey** [comment]
This won't be possible in Kustomization, but the good news is we have a KEP for a new kind called Composition that has arbitrary transformer/generator/validator ordering as one of its features.
 
* [Kustomize Plugin Composition API KEP](https://github.com/kubernetes/enhancements/issues/2299) (Note that https://github.com/kubernetes/enhancements/pull/3097/files has some small changes to this)
* Prototype PR: #4323, which has a complete implementation but lists several obstacles to merging that require a fair amount of investment to solve

**Comment by KnVerey** [comment]
Actually, my first sentence wasn't strictly correct. Come to think of it, the combination of Composition prerequisites https://github.com/kubernetes-sigs/kustomize/issues/4403 and https://github.com/kubernetes-sigs/kustomize/issues/4402 should allow you to define your own sequence of generators/transformers/validators in the existing `transformers` field in a Kustomization as well.

Since we already have plans that would make this possible tracked in those issues / the KEP, please follow along there instead.
/close

**Comment by chicocvenancio** [comment]
Thanks for the links @KnVerey.
