### ISSUE TITLE
Airgap support

### ISSUE THREAD

**Issue by jpic** [kubernetes-sigs/kustomize#4346]
Airgap deployments happen on networks without internet access, with a private registry.

It would be great if we had the following commands:

- `kustomize airgap pull`: to pull all images
- `kustomize airgap prefix <your.registry/your.path>`: this would do `kustomize edit set image <each image>=<prefix>/<each image` and add the new tag to all images
- `kustomize airgap push <your.registry/your.path>`: push all retagged images to the private registry

Additionally, repos like kubeflow should be able to hook additional images, ie. for situations like [this](https://github.com/kubeflow/manifests/blob/master/apps/jupyter/jupyter-web-app/upstream/base/configs/spawner_ui_config.yaml#L23)

**Comment by KnVerey** [comment]
Kustomize exclusively deals with Kubernetes configuration files: to Kustomize, images are just a field--pushing, pulling or otherwise handling the images themselves is out of scope for this tool.

Regarding making Kustomizations work without internet access in general, you may be interested in this issue: https://github.com/kubernetes-sigs/kustomize/issues/3980.

If I've misunderstood, please reopen with more detail.

/close
