### ISSUE TITLE
Patch problem when list key name is "type"

### ISSUE THREAD

**Issue by wilstdu** [kubernetes-sigs/kustomize#4407]
**Describe the bug**
I've tried to kustomize hpa files from the kubernetes example (https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-metrics-not-related-to-kubernetes-objects), and kustomize failed to patch it correctly

I've noticed that it is because of list key name:
If the list key is "type", kustomization patches list in a weird manner.
However, if the key begins with the capital letter "Type", the patching is correct.

**Files that can reproduce the issue**
` overlay.yaml: `

` apiVersion: autoscaling/v2`
` kind: HorizontalPodAutoscaler`
` metadata:`
`   name: hpa-app-bluegreen`
` spec:`
`   minReplicas: 2`
`   maxReplicas: 3`
`   metrics:`
`   - type: Resource`
`     resource:`
`       name: cpu`
`       target:`
`         type: Utilization`
`         averageUtilization: 50`

**Expected output**

`apiVersion: autoscaling/v2`
`kind: HorizontalPodAutoscaler`
`metadata:`
`  name: hpa-app-bluegreen`
`spec:`
`  maxReplicas: 3`
`  metrics:`
`  - type: Resource:`
`     resource:`
`      name: cpu`
`      target:`
`        averageUtilization: 50`
`        type: Utilization`
`  minReplicas: 2`

**Actual output**

(notice `type` becomes part of `resource` list):
`apiVersion: autoscaling/v2`
`kind: HorizontalPodAutoscaler`
`metadata:`
`  name: hpa-app-bluegreen`
`spec:`
`  maxReplicas: 3`
`  metrics:`
`  - resource:`
`      name: cpu`
`      target:`
`        averageUtilization: 50`
`        type: Utilization`
`    type: Resource`
`  minReplicas: 2`

**Kustomize version**

kubectl version: v1.21.4
kustomize version: v4.0.5

**Platform**

Linux/Windows

**Comment by KnVerey** [comment]
It's really difficult to understand the situation since your samples aren't indented correctly. I tried to reproduce based on the description, and the only difference I'm seeing when `type` is capitalized is that the capitalization causes that field to appear before `resource` instead of after it (still at the same indentation level). Please try with the latest version of Kustomize, and if you're still able to reproduce, please re-open with usable samples--fyi the syntax is

````
```yaml
your: yaml
```
````

/close
/triage not-reproducible
