### ISSUE TITLE
Error building id.GvknString undefined (type resid.ResId has no field or method GvknString)

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes-sigs/kustomize#4409]
**Describe the bug**

```
Executing target: build
go build -o /dev/null ./...
# sigs.k8s.io/kustomize/api/resmap
../../../../go/pkg/mod/sigs.k8s.io/kustomize/api@v0.10.1/resmap/reswrangler.go:218:19: id.GvknString undefined (type resid.ResId has no field or method GvknString)
make: *** [build] Error 2
```

[This PR](https://github.com/kubernetes-sigs/kustomize/pull/4344/files#diff-3725194978232dfb5ab1f008fb3d8780758f31e48f51f549b45976a83eb7b8e3L218) changed the behavior and removed the function `GvknString`, but the latest version `sigs.k8s.io/kustomize/api@v0.10.1` [doesn't include the change](https://github.com/kubernetes-sigs/kustomize/blob/326a57a9ccd3132321b6f42f6bb141664317c3db/api/resmap/reswrangler.go#L218).

**Files that can reproduce the issue**

**Expected output**

**Actual output**

**Kustomize version**

**Platform**

**Additional context**

**Comment by natasha41575** [comment]
The PR you linked was merged in late December and included in the latest release of `kyaml`, while `sigs.k8s.io/kustomize/api@v0.10.1` was released early November. 

Am I correct in assuming that you are trying to use the latest `kyaml` in conjunction with the latest `api`? Unfortunately that is not going to work, because of `api`'s dependency on `kyaml`. This will be resolved when we do another release, but until then if you are going to use `api` with `kyaml`, you will have to use the version of `kyaml` that was released before it. 

/kind release

**Comment by dkoshkin** [comment]
>Am I correct in assuming that you are trying to use the latest kyaml in conjunction with the latest api? 

I tried to use the latest version of `kyaml` which resulted in the error and then I tried to use the latest version `api` but still saw the error.

Thanks though, will wait for another release.

**Comment by natasha41575** [comment]
There is a new release out, the new `kyaml` should be compatible with the new `api`.
