### ISSUE TITLE
Cluster wide configuration for kustomize

### ISSUE THREAD

**Issue by mukundjalan** [kubernetes-sigs/kustomize#4416]
We are having multiple kustomize modules which deploy knative services. From #3671 , I understand we are not planning to support knative transformations out-of-the-box. Due to this, I am compelled to add the same config.yaml file across all our kustomize modules. Is there a way that I could apply the knative kustomize configurations globally at the cluster level or something similar?

**Comment by KnVerey** [comment]
I'm not sure what you mean by "cluster level" since Kustomize is a purely client-side tool. As a rule, we require everything that will affect a `build`'s output to be specified within the targeted Kustomization.yaml, to ensure that builds are reproducible. This is because GitOps is such a cornerstone use case for us. That said, @natasha41575 is working on a proposal for improving the way that third party resource schemas are handled by Kustomize. The tracking issue for that is https://github.com/kubernetes-sigs/kustomize/issues/3418. Please follow that one to be notified when the KEP is up and provide your feedback there.

/close
