### ISSUE TITLE
commonlabels does not work as expected after API version change in manifests.

### ISSUE THREAD

**Issue by nachrivcost** [kubernetes-sigs/kustomize#4422]
I have long configured kustomize together with Flux for my continuous deployment. Kustomize is configured as multibase.
In one of my Overlay kustomization.yaml contains the commonlabels field **(env: production)**, it is supposed to add that label to each resource that is inside the overlay and a selector to each service.

Suddenly it has stopped working and only adds the selector, leaving the application without service since it does not contain the env label.

The only change made has been to change the kubernetes API Version in the manifests **(extensions/v1beta1 to apps/v1)** because it has been deprecated and we can no longer work with that version. Since that moment, we have started to have 
problems.

Kubernetes version: v1.16.15
Worknodes version: v1.14.7

I thought that maybe the Kustomize API Version could be to blame, but I don't know if it makes sense or not.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

Regards,

**Comment by KnVerey** [comment]
Are you using Kustomize via `kubectl kustomize`, where your `kubectl` version is 1.16.15? If so, I suspect the issue is that kubectl < 1.21 bundles a very old version of Kustomize that did not yet know about the apps/v1 API group. If that's not the case, please provide the kustomize CLI version you are using.

Version chart: https://github.com/kubernetes-sigs/kustomize#kubectl-integration
