### ISSUE TITLE
HelmChartInflationGeneratorPlugin: releaseNamespace is not respected

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/kustomize#4459]
**Describe the bug**

I'm trying to set `releaseNamespace` via `helmChartInflationGenerator` but it is not used / handed over to the `helm template` command

**Files that can reproduce the issue**

Add an additional `releaseNamespace` to https://github.com/kubernetes-sigs/kustomize/blob/d03a5ab95f16348b49afd5ed3f70856d14fa9a50/api/krusty/helmchartinflationgenerator_test.go#L59 
and run the test (including break points on helm template command calculation)

**Kustomize version**

latest main branch: commit 14cb815b

**Platform**

macOS

**Additional context**

It looks to me like the problem is that `makeHelmChartFromHca` doesn't set the `Namespace` field. Please see this PR: https://github.com/kubernetes-sigs/kustomize/pull/4460

**Workaround**

I just realized that there is the new `helmCharts` config which doesn't have this issue. So I can and should use the new config struct instead. It might still be good to fix the conversion from old to new format, so that `releaseNamespace` in the old format also works.

**Comment by natasha41575** [comment]
We plan to move the helm plugin to a KRM-style function plugin that will live in the new CNCF functions registry - so the plugin that is currently built into kustomize will no longer be supported. You can see more details here https://github.com/kubernetes-sigs/kustomize/issues/4401

We are marking all helm plugin-related issues with area/helm, so that once the CNCF functions registry is ready, we can address all these issues there.

/triage accepted

**Comment by sbueringer** [comment]
@natasha41575 Okay, should I close: https://github.com/kubernetes-sigs/kustomize/pull/4460?

I already migrated to `helmCharts` so I personally don't need the fix anymore.
