### ISSUE TITLE
Inject templates in templates - pre render

### ISSUE THREAD

**Issue by Diliz** [kubernetes-sigs/kustomize#4519]
**Is your feature request related to a problem? Please describe.**

Today, if I want to inject templated contents in an already packaged helm chart before applying any values, in order to extend the helm chart usage or else, I have to mirror the helm chart repository and add the lines I want manually, then packaged it on a custom helm repository, etc...

This solution is hard to maintain as I have to fetch content regularly on the upstream helm chart repository and reapply updates.

**Describe the solution you'd like**

Having the possibility to inject values in charts before helm rendering.

**Describe alternatives you've considered**

Add a Kubernetes job ressource template in my helm chart which will apply the rendered templated values in my deployed ressources, and add the upstream helm chart as a dependency.

**Additional context**

I am really not looking for post render injection here, I really want to add pre render injection, this would allow me to extend already existing charts which I don't own myself without duplicating the whole thing and patch it for my needs.

Example :
- My-application: have custom helm charts dependencies with specific labels per cluster
- My dependencies helm charts: have custom labels defined, for observability purposes -> I have to define this labels in the application helm charts, which does not have the same lifecycle as its dependencies at all.

**Comment by natasha41575** [comment]
Could you provide a more specific example of what you want _kustomize_ to do, perhaps with some input and output files? I read through both this issue and the issue you filed in the helm repo and I'm not sure that I completely understand what you are asking for. 

It sounds like you want kustomize to do some templating work, which is specifically out of scope for kustomize. The only helm support we currently have is the builtin helm plugin, which we will be deprecating in favor of a third-party extension that is being built (see the [long term helm support plan](https://github.com/kubernetes-sigs/kustomize/issues/4401)). 

We do want to support users who are trying to use helm and kustomize together, but we are specifically trying to avoid:
- having this support necessarily built into kustomize, which is why we are instead building it as a third party extension
- having direct support for templating features in kustomize

If you are trying to run the helm plugin in a specific way, or have a specific field option to it, could you please elaborate?

**Comment by Diliz** [comment]
Hello!

My specific usage is to extend already existing charts (which I do not manage nor build, ex: prometheus, or any helm chart from any repository) by injecting templating parts in it before using the helm template command, this would allow me to add dynamic content to any existing chart, kustomize only allow me to inject static content for now.

Currently I have to mirror the existing chart, then tweak the templates and add my dynamic stuff there, build it, test it, etc, this is far from manageable on short/long term, this will solve this issue :)

**Comment by epcim** [comment]
@ejstreet would not help you to do it with KRM gotpl renderer? https://github.com/epcim/render-gotpl-fn
