### ISSUE TITLE
Vulnerable golang version used for packaging (multiple critical and high CVEs)

### ISSUE THREAD

**Issue by rimasgo** [kubernetes-sigs/kustomize#4523]
**Describe the bug**

I have built an image where I use latest kustomize (v4.5.2) binary. I did the scan of the image with twistlock (Prisma) and it returned quite a list of CVEs associated with kustomize binary. It seems that twistlock is doing in depth scanning and checks the version of SDK (golang in this case) used to compile the binary. 

Is it possible to introduce more 'ever-green' into release process of kustomize?

Binary that was identified:
          "name": "go",
          "version": "1.16.5",
          "path": "/usr/local/bin/kustomize",
          "layerTime": 1647860026,
          "knownVulnerabilities": 55

CVEs:

CVE-2021-38297 | critical |   | go | 1.16.5 | fixed in 1.17.2, 1.16.9 | 07-Oct-2021 00:00 | 21-Mar-2022 13:11
CVE-2022-23806 | critical |   | go | 1.16.5 | fixed in 1.17.7, 1.16.14 | 11-Feb-2022 00:00 | 21-Mar-2022 13:11
CVE-2022-24921 | high |   | go | 1.16.5 | fixed in 1.17.8, 1.16.15 | 03-Mar-2022 00:00 | 21-Mar-2022 13:11
CVE-2022-23773 | high |   | go | 1.16.5 | fixed in 1.17.7, 1.16.14 | 18-Nov-2019 00:00 | 21-Mar-2022 13:11
CVE-2022-23772 | high |   | go | 1.16.5 | fixed in 1.17.7, 1.16.14 | 19-Jan-2022 00:00 | 21-Mar-2022 13:11
CVE-2021-44716 | high |   | go | 1.16.5 | fixed in 1.17.5, 1.16.12 | 09-Dec-2021 00:00 | 21-Mar-2022 13:11
CVE-2021-41772 | high |   | go | 1.16.5 | fixed in 1.17.3, 1.16.10 | 30-Aug-2021 00:00 | 21-Mar-2022 13:11
CVE-2021-41771 | high |   | go | 1.16.5 | fixed in 1.17.3, 1.16.10 | 14-Oct-2021 00:00 | 21-Mar-2022 13:11
CVE-2021-39293 | high |   | go | 1.16.5 | fixed in 1.17.1, 1.16.8 | 18-Aug-2021 00:00 | 21-Mar-2022 13:11
CVE-2021-29923 | high |   | go | 1.16.5 | fixed in 1.17 | 22-Mar-2021 00:00 | 21-Mar-2022 13:11
CVE-2021-36221 | medium |   | go | 1.16.5 | fixed in 1.16.7, 1.15.15 | 05-Aug-2021 00:00 | 21-Mar-2022 13:11
    

As you can see to cover for all vulnerabilities kustomize should be compiled using 1.17.8 or 1.16.15 if it can't move to 1.17 

**Files that can reproduce the issue**

Build image with latest kustomize and scan with Prisma

**Expected output**

No vulnerabilities

**Actual output**

CVE-2021-38297 | critical |   | go | 1.16.5 | fixed in 1.17.2, 1.16.9 | 07-Oct-2021 00:00 | 21-Mar-2022 13:11
CVE-2022-23806 | critical |   | go | 1.16.5 | fixed in 1.17.7, 1.16.14 | 11-Feb-2022 00:00 | 21-Mar-2022 13:11
CVE-2022-24921 | high |   | go | 1.16.5 | fixed in 1.17.8, 1.16.15 | 03-Mar-2022 00:00 | 21-Mar-2022 13:11
CVE-2022-23773 | high |   | go | 1.16.5 | fixed in 1.17.7, 1.16.14 | 18-Nov-2019 00:00 | 21-Mar-2022 13:11
CVE-2022-23772 | high |   | go | 1.16.5 | fixed in 1.17.7, 1.16.14 | 19-Jan-2022 00:00 | 21-Mar-2022 13:11
CVE-2021-44716 | high |   | go | 1.16.5 | fixed in 1.17.5, 1.16.12 | 09-Dec-2021 00:00 | 21-Mar-2022 13:11
CVE-2021-41772 | high |   | go | 1.16.5 | fixed in 1.17.3, 1.16.10 | 30-Aug-2021 00:00 | 21-Mar-2022 13:11
CVE-2021-41771 | high |   | go | 1.16.5 | fixed in 1.17.3, 1.16.10 | 14-Oct-2021 00:00 | 21-Mar-2022 13:11
CVE-2021-39293 | high |   | go | 1.16.5 | fixed in 1.17.1, 1.16.8 | 18-Aug-2021 00:00 | 21-Mar-2022 13:11
CVE-2021-29923 | high |   | go | 1.16.5 | fixed in 1.17 | 22-Mar-2021 00:00 | 21-Mar-2022 13:11
CVE-2021-36221 | medium |   | go | 1.16.5 | fixed in 1.16.7, 1.15.15 | 05-Aug-2021 00:00 | 21-Mar-2022 13:11

**Kustomize version**

4.5.2

**Platform**

Linux

**Additional context**

Please let me know if you need more details.

**Comment by natasha41575** [comment]
We can probably update the version of go we use to 1.16.15.

https://goreleaser.com/customization/build/ `gobinary` is a parameter we could try to use. 

https://github.com/kubernetes-sigs/kustomize/blob/master/releasing/cloudbuild.yaml is the file to update.

/triage accepted

**Comment by KnVerey** [comment]
> https://goreleaser.com/customization/build/ gobinary is a parameter we could try to use.

Thinking about this further, I believe that field just tells goreleaser to look for a binary with that name instead of "go". So to do that, we'd need to be using an image that has multiple versions of Go available. I think the goreleaser image we're using is likely the problem: https://github.com/kubernetes-sigs/kustomize/blob/master/releasing/cloudbuild.yaml#L39 / [Dockerhub](https://hub.docker.com/layers/goreleaser/goreleaser/goreleaser/v0.172.1/images/sha256-0e87d0e33840a556d3b9c10a7f71a3a69bcd9c29b86a180cbbf7d7ad1f3fa280?context=explore). Unfortunately I'm not seeing an available image with a version between 1.16.5 and 1.17. That said, despite that the k/k go.mod lists 1.16, it seems like it is actually [being built with 1.18 now](https://github.com/kubernetes/kubernetes/pull/108870), which gives us more flexibility to do the same.

**Comment by KnVerey** [comment]
The best we're going to be able to do immediately is go 1.17.1, which is what the [goreleaser v0.179.0 image uses](https://hub.docker.com/layers/goreleaser/goreleaser/goreleaser/v0.179.0/images/sha256-6cda9886cc5d58c4246f8f0338b87dbd3742dad56c4c70f37ad911d3e3d1eb63?context=explore). The limiting factor turns out to be a deprecation in goreleaser 0.180.0 that makes newer versions of goreleaser fail with Kustomize's multi-module setup. This happens because the tool is not longer able to ignore that our tags aren't pure semver (they have module prefixes). Multi-module repos like our are supposed to move to the "monorepo" feature, which requires a paid Pro license: https://goreleaser.com/customization/monorepo/. I will open a separate issue for that.

**Comment by KnVerey** [comment]
[v4.5.4](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.5.4) was built with Go 1.17.1, and I have a fix in progress that should allow us to do the next one with 1.18.0.
