### ISSUE TITLE
Support alternative filename path for kustomization.yaml, not just a directory

### ISSUE THREAD

**Issue by HariSekhon** [kubernetes-sigs/kustomize#4659]
**Is your feature request related to a problem? Please describe.**

Kustomize should accept a filename path as an argument, not just a directory path, to allow using alternate adjacent kustomization.yaml files.

**Describe the solution you'd like**

Kustomize could check the argument for being a filename and then cd to its directory before evaluating it.

This change could be backwards compatible with existing behaviour for a directory argument based on a simple cheap file or directory existence test on that argument.

Currently when you give Kustomize a directory argument it only looks for default filenames such as `kustomization.yaml` or `kustomization.yml`, but it cannot actually take a custom filename, even though this is very common with other major technologies that take standardized files, such as Dockerfiles, Jenkinsfiles etc. where there may be alternate adjacent versions of those files.

When combined with the lack of symlink support (https://github.com/kubernetes-sigs/kustomize/issues/4420) this is very inconvenient - especially when it comes to testing, debugging, deploying from another source etc.

**Describe alternatives you've considered**

Right now you have to copy files around and rename them to fit the rigid `<directory>/kustomization.yaml` structure, which is inconvenient for testing, debugging, or even deploying from several adjacent kustomization option files. 

**Additional context**

An example of a place where this is inconvenient would be deploying straight out of this repo with lots of different `<app>-kustomization.yaml` files available:

https://github.com/HariSekhon/Kubernetes-configs

**Comment by KnVerey** [comment]
/triage needs-information

We are very hesitant to support alternate filenames due to the increased complexity it would add to Kustomize's model. Kustomize is indeed quite opinionated about the file structures it expects, as part of its core design. Could you please provide more information on why the standard structure with a series of encapsulated bases that can be reused does not work for you, requiring you to have an original structure with multiple bases side by side that you then need to copy around?

Please note that #4420 is a bug, and new features should not be designed around the assumption it won't be fixed. If you have bandwidth to help with that one, we would appreciate it!

**Comment by HariSekhon** [comment]
It's common to have alternative versions of files for testing and debugging issues - and is commonly supported by most major tools - even ones with very standard opinionated filenames such as Dockerfile, Jenkinsfile, Makefile etc... all allow for specifying alternative filenames.

Apps can also have more than 1 deployment style (eg. Selenium Grid has hub/router-based model in one kustomization, and fully distributed model in another kustomization). By having the kustomization files side by side the option becomes more obvious instead of having to traverse different directories.

I guess this 2nd point is a matter of preference and style, but the first point is a matter of dev usability / ease of use.

I appreciate it's extra work to code support for passing a filename argument, but this would be of benefit to people using Kustomize day-to-day.
