### ISSUE TITLE
Add support for extra `fieldspecs` in `configurations` for `Labels`

### ISSUE THREAD

**Issue by joseparajelesGL** [kubernetes-sigs/kustomize#4816]
Currently only CommonLabels supports adding extra shared field specs inside an item in `configurations`. Is possible to have this support for the Labels plugging or is this form of shared configuration is been phased out?

**Comment by natasha41575** [comment]
Taking a look at the [transformer configuration documentation](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/transformerconfigs), it doesn't look like we currently support this for Labels. That said, I think it would be okay to add the support for adding extra fieldspecs to Labels, since we already have it for CommonLabels.

/triage accepted
/retitle Add support for extra `fieldspecs` in `configurations` for `Labels`
/kind feature
/label "good first issue"
/help

**Comment by swastik959** [comment]
@natasha41575 
 hi I am new to open source and want to contribute to this issue can you guide me through it

**Comment by BalaadityaPatanjali** [comment]
/assign
I'd like to work on this.
