### ISSUE TITLE
Support for wildcard in resource

### ISSUE THREAD

**Issue by lionelvillard** [kubernetes-sigs/kustomize#484]
Currently each resource needs to be enumerated in `kustomization.yaml` so when a new yaml file is added, `kustomization.yaml` needs to be updated. It'd be great if `resource` accepts wildcard or directory

**Comment by Liujingfang1** [comment]
@lionelvillard We did consider this support previously, but decided not to add it. The reason is documented here https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#globs-in-kustomization-files

On the other side, our `kustomize edit add resource` support globs. You can use it to add files under a directory to kustomization.yaml.

**Comment by TomyLobo** [comment]
The link posted by @Liujingfang1 has since died.
New link: https://kubectl.docs.kubernetes.io/faq/kustomize/eschewedfeatures/#globs-in-kustomization-files
