### ISSUE TITLE
Add Monokle to website 

### ISSUE THREAD

**Issue by olensmar** [kubernetes-sigs/kustomize#4846]
I'm sorry - i didn't know where to post this - I would like to suggest to add Monokle to the "Projects Integrating Kustomize" section on kustomize.io 

Monokle is a unified visual tool for authoring, analysis and deployment of Kubernetes configurations - including integrated support and functionality for Kustomize (validation, previews, compare, etc) - it's Open Source (MIT) and available on GitHub at https://github.com/kubeshop/monokle

Read more about how it supports Kustomize at https://kubeshop.github.io/monokle/kustomize/ 

If you'd like a hands-on demo to back this up please let me know!

**Comment by natasha41575** [comment]
The current kustomize.io unfortunately is not something that we built. It was built by another company which was then donated to us and we are currently in the middle of trying to migrate our content. We have an umbrella issue for that [here](https://github.com/kubernetes-sigs/kustomize/issues/4338).

With regards to adding a link to your website, I'm hesitant to put links to other non-SIG-CLI tools on our website because we don't maintain them and know little about them, and I don't know if we should be trying to endorse other tools that we are not involved with. We see that the current kustomize.io does have links to other resources, so we still need to think about what we want to do with those.

@KnVerey Do you have any thoughts on this?

/triage under-consideration

**Comment by olensmar** [comment]
thanks @natasha41575 - let me know if there is anything I can do to help move this forward..

**Comment by KnVerey** [comment]
> With regards to adding a link to your website, I'm hesitant to put links to other non-SIG-CLI tools on our website because we don't maintain them and know little about them, and I don't know if we should be trying to endorse other tools that we are not involved with. We see that the current kustomize.io does have links to other resources, so we still need to think about what we want to do with those.

I think it would be helpful for us to retain some form of the list of other popular open-source tools that integrate with us, but I agree with you that we'll need to include a disclaimer that the list does not constitute an endorsement. I also agree with you that this would be part of #4338 .

> let me know if there is anything I can do to help move this forward.

We could really use help on #4338 ! This is very valuable to the project and the issue has instructions for how to get started. The maintainer team is small and focussed on higher-context tasks, so we'll need new contributions for it to move forward anytime soon.
