### ISSUE TITLE
Kustomize testutil/kusttest support for testing Custom KRM resources.

### ISSUE THREAD

**Issue by Akshaya-T** [kubernetes-sigs/kustomize#5102]
**Use case:**

I am trying to test my KRM Functions, I am trying to use the kusttest for it, as I can simply pass the input and test the expected output by running it as generators.

But I am facing some errors while running it, do we have support for doing this?

**Error:**
```
--- FAIL: TestIAMFunction (0.81s)
    plugintestenv.go:40: unable to find plugin src root - tried: ('/Users/akshaya/my_porjects/hotfix/plugin'; relative to unit test), ('/Users/akshaya/plugin'; relative to unit test (internal pkg)), ('/Users/akshaya/plugin'; relative to api package), ('src/sigs.k8s.io/kustomize/plugin'; old style $GOPATH), ('/Users/akshaya/gopath/src/sigs.k8s.io/kustomize/plugin'; HOME with literal 'gopath'), ('/Users/akshaya/sigs.k8s.io/kustomize/plugin'; home directory)
    hasgett.go:22: Expected not equal to actual
FAIL
```

**Test code**
```
import (
	"testing"
	kusttest_test "sigs.k8s.io/kustomize/api/testutils/kusttest"
)

func TestIAMFunction(t *testing.T) {
	th := kusttest_test.MakeEnhancedHarness(t).PrepExecPlugin("", "", "")
	defer th.Reset()

	rm := th.LoadAndRunGenerator(`
apiVersion: krm/v1
kind: TestIAM
metadata:
  name: test-sa
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/infra/krm-functions/iam:latest
spec:
  name: test-sa
  env: test
`)
	th.AssertActualEqualsExpected(rm, `
....
....
`)
}
```

**Comment by KnVerey** [comment]
Hi! `kusttest` is designed for use by Kustomize itself. You can feel free to use it, but please be aware that we may make unannounced breaking changes to it in service of Kustomize's needs. Its plugin-related features can be confusing, because of the need to support both the legacy-style plugins and KRM Functions, and the fact that Kustomize internally compiles in some code that is initial written in the style of internal plugins--and the test framework is handling all that.

If you want to see what it looks like to use `kusttest` for KRM testing, please have a look at this file: https://github.com/kubernetes-sigs/kustomize/blob/3e447da6ef302a24d24b83794f7ccff0c75081af/api/krusty/fnplugin_test.go. 

Otherwise, the function framework does have its own set of test utils that are intended for external consumption, but are very much tied to the framework. You can find the Go docs for those here: https://pkg.go.dev/sigs.k8s.io/kustomize/kyaml/fn/framework/frameworktestutil

I hope that helps. If you have more questions, feel free to re-open!

/triage resolved
/close
/area kyaml
/area plugin
/kind support
