### ISSUE TITLE
LoadRestrictor with limited number of allowed parent-directory to be traversed

### ISSUE THREAD

**Issue by rucciva** [kubernetes-sigs/kustomize#5120]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

load restrictor that allows traversal directory at certain number above the current kustomize directory

### Why is this needed?

Especially for using HelmChartInflationGenerator with common values shared across overlay. 

### Can you accomplish the motivating task without this feature, and if so, how?

Yes with load-restrictor LoadRestrictionsNone, but with compromise of security since it allows traversal of non limited parent directory

### What other solutions have you considered?

manually copy-paste-ing shared values.yaml to each overlay directory

### Anything else we should know?

not currently

### Feature ownership

- [ ] I am interested in contributing this feature myself! 🎉

**Comment by KnVerey** [comment]
/triage under-consideration
/priority backlog

This is a very interesting idea. We discussed this in the bug scrub today, and we're leaning towards either:
- taking a specified number of directories (since Kustomize cannot know how many is safe)
- taking a scope flag pointing to a specific directory, which is then used for loading restrictions--this is analogous to the "scope" argument on the new `kustomize localize` so I'd like to get @annasong20 opinion on this
