### ISSUE TITLE
[Feature] Kustomize KCL Function

### ISSUE THREAD

**Issue by Peefy** [kubernetes-sigs/kustomize#5135]
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

Kustomize KCL Function Support. 

Just like `starlark`, we would like to add KCL function functionality for kustomize. [KCL](https://github.com/KusionStack/KCLVM) is specifically used for configuration writing and policy verification in cloud-native and Kubernetes scenarios.
 

### Why is this needed?

I was very glad to find the kustomize project and browse all its documents. I found that it coincided with what we wanted to do.

Specifically, we have just opened our domain language project [KCL](https://github.com/KusionStack/KCLVM). However, it is obviously not enough to use only one language for Kubernetes configuration management until we find Kustomize. We want to develop Kustomize KCL plug-ins and SDKs, so we want to keep in touch with you through this issue.

We have designed [kpt-kcl-sdk](https://github.com/KusionStack/kpt-kcl-sdk). KPT is a great Kubernetes editing tool, but there are still many needs that cannot be well met (Off-the-shelf packages are rarely deployed without any customization). So we have reason and feasibility to verify the integration of KCL and Kustomize tools.

We have implemented a simple version: https://github.com/KusionStack/kustomize-kcl

I hope you can give some suggestions. If possible, I am willing to contribute to the Kustomize community.

### Can you accomplish the motivating task without this feature, and if so, how?

Yes.

### What other solutions have you considered?

+ Kustomize starlark function.
+ KPT KCL SDK: https://github.com/KusionStack/kpt-kcl-sdk

### Feature ownership

- [X] I am interested in contributing this feature myself! 🎉

**Comment by annasong20** [comment]
Hi @Peefy, thank you for your interest in extending kustomize and your proof of concepts. 

We don't think it's a good idea to accept this feature proposal due to the current state of KRM functions in kustomize. We have [multiple KEPs](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/2953-kustomize-plugin-graduation) that need to be implemented before the ecosystem is mature, and we don't want to support significant new features before that happens.

Also, it seems that in your [POC](https://github.com/KusionStack/kustomize-kcl), you're able to integrate kustomize with KCL, so what additional functionality are you looking for? From a brief overview, it seems that KCL is a language used to create containers, and kustomize is able to consume KRM container functions. Please point out our lapse in understanding.

/triage out-of-scope
/triage needs-information

**Comment by Peefy** [comment]
> Hi @Peefy, thank you for your interest in extending kustomize and your proof of concepts.
> 
> We don't think it's a good idea to accept this feature proposal due to the current state of KRM functions in kustomize. We have [multiple KEPs](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/2953-kustomize-plugin-graduation) that need to be implemented before the ecosystem is mature, and we don't want to support significant new features before that happens.
> 
> Also, it seems that in your [POC](https://github.com/KusionStack/kustomize-kcl), you're able to integrate kustomize with KCL, so what additional functionality are you looking for? From a brief overview, it seems that KCL is a language used to create containers, and kustomize is able to consume KRM container functions. Please point out our lapse in understanding.
> 
> /triage out-of-scope /triage needs-information

Hi @annasong20, thank you for your reply. KCL can be seen as a configuration language similar to Starlark, and we have completed the [Kustomize KCL Function PoC](https://kcl-lang.io/docs/user_docs/guides/working-with-k8s/kustomize_kcl_plugin) and expected to contribute to the community, there is no additional demand for `kustomize fn`.

**Comment by Peefy** [comment]
> 你好@Peefy，我花了更多时间研究你的要求，我想我终于明白了。
> 
> 澄清一下，您希望 kustomize 像它一样支持 KCL `starlark`。即，您希望能够为生成器或转换器提供注释
> 
> ```yaml
> metadata:
>   annotations:
>       config.kubernetes.io/function: |
>         KCL:
>           path: path-to-file-with-KCL-code
> ```
> 
> 以便 kustomize 知道`path-to-file-with-KCL-code`使用 KCL 运行。你可否确认？

Hi @annasong20 . I am very happy that your understanding is correct. ❤️

**Comment by Peefy** [comment]
> Hi @annasong20 . I am very happy that your understanding is correct. ❤️ I will provide more info and design later.

+ A transformer example

```kcl
# kcl-fn-config.yaml
apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  annotations:
    config.kubernetes.io/function: |
      container:
        image: docker.io/peefyxpf/kustomize-kcl:v0.1.1
spec:
  source: |
    [resource | {if resource.kind == "Deployment": metadata.annotations: {"managed-by" = "kustomize-kcl"}} for resource in option("resource_list").items]
```

+ A validator example

```kcl
apiVersion: krm.kcl.dev/v1alpha1
kind: KCLRun
metadata:
  name: https-only
  metadata:
    annotations: 
      config.kubernetes.io/function: |
        container:
          image: docker.io/peefyxpf/kustomize-kcl:v0.1.1
      documentation: >-
        Requires Ingress resources to be HTTPS only.  Ingress resources must
        include the `kubernetes.io/ingress.allow-http` annotation, set to `false`.
        By default a valid TLS {} configuration is required, this can be made
        optional by setting the `tlsOptional` parameter to `true`.
        More info: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
spec:
  source: |
    # Construct resource and params
    resource = option("resource_list")
    items = resource.items
    params = resource.functionConfig.spec.params
    # Define the validation function
    validate_https_only = lambda item {
        if item.kind == "Ingress" and item.spec.tls:
            assert item.metadata.annotations["kubernetes.io/ingress.allow-http"] == "false", "Ingress should be https. The kubernetes.io/ingress.allow-http=false annotation is required for ${item.metadata.name}"
        item
    }
    # Validate All resource
    [validate_https_only(i) for i in items]
```

**Comment by annasong20** [comment]
Hi @Peefy, after multiple discussions with the team, I don't think kustomize will support KCL out of the box, like so,

> ```yaml
> metadata:
>   annotations:
>       config.kubernetes.io/function: |
>         KCL:
>           path: path-to-file-with-KCL-code
> ```

in the near future. 

The reasoning is, as stated in https://github.com/kubernetes-sigs/kustomize/issues/5135#issuecomment-1564853748, that we want to graduate KRM functions first. KRM container functions allow, as you show in https://github.com/kubernetes-sigs/kustomize/issues/5135#issuecomment-1592378440 via your transformer and validator examples, the flexibility to provide your own containers for your use cases without requiring the dependencies to be built into kustomize. You are able to run KCL without your requested feature. This is especially important given that starlark is being deprecated due to inconsistent dependencies: please reference #4349.

**Comment by Peefy** [comment]
Thank you for your reply! We will provide our own Kustomize KCL container to run KCL codes.
