### ISSUE TITLE
Site building guide for docker results in an error

### ISSUE THREAD

**Issue by typeid** [kubernetes-sigs/kustomize#5331]
### What happened?

When following [instructions to run the site locally using docker compose](https://github.com/kubernetes-sigs/kustomize/tree/7c36ed21b3587e7124326743a888db5374e86d93/site#building), I run in the following error:
```
docker-compose up
Starting site_site_1 ... done
Attaching to site_site_1
site_1  | Start building sites … 
site_1  | hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended linux/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=hugoguru
site_1  | ERROR 2023/09/17 05:59:21 Failed to read Git log: fatal: not a git repository (or any parent up to mount point /)
site_1  | Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
site_1  | Built in 6 ms
site_1  | Error: Error building site: "/src/content/en/_index.html:7:1": failed to extract shortcode: template for shortcode "blocks/cover" not found
site_site_1 exited with code 255
```

It seems like a step to initialize and update submodules for docsy is missing in the steps.

### What did you expect to happen?

Steps to follow don't result in an error.

### How can we reproduce it (as minimally and precisely as possible)?

```terminal
# In a fresh clone of the kustomize repository:
$ docker-compose build
$ docker-compose up -d
```

### Expected output

Site is exposed on localhost:1313

### Actual output

```
site_site_1 exited with code 255
```

### Kustomize version

latest

### Operating system

None

**Comment by DiptoChakrabarty** [comment]
can confirm noticed this issue 

/kind documentation

**Comment by natasha41575** [comment]
After speaking with the docs team, turns out they have not been able to get the docker-compose instructions to work and ended up just installing hugo on their local machine and building the site that way. They have been alternatively been installing hugo locally and building the site there. Another alternative is to look into what the kubernetes website does and follow that example.

@ncapps and @stormqueen1990 Can you follow up here to recommend a solution here? (@typeid you can also ping them on Slack for help with contributing to kustomize or the docs project)

/assign @ncapps
/assign @stormqueen1990 

/triage accept

**Comment by stormqueen1990** [comment]
k/website offers Makefile targets and a Dockerfile that can be used to build the website locally and run in a container. We could apply a similar approach for the Kustomize documentation.

Refs:
* https://github.com/kubernetes/website/blob/main/Dockerfile
* https://github.com/kubernetes/website/blob/main/Makefile

cc @ncapps
