### ISSUE TITLE
[Request] Allow modifying annotations

### ISSUE THREAD

**Issue by jgonera** [kubernetes-sigs/kustomize#564]
I have a deploy script that works more or less like this (simplified version):

```
kustomize edit set imagetag myimage:$VERSION
kustomize edit add annotation deployTimestamp:$(date -u +"%Y-%m-%dT%H%M%SZ")
kustomize build | kubectl apply -f -

git add .
git commit --message="Deploy $VERSION"
git push origin master
```

I'm using annotations to be able to force a deploy even if I didn't change anything, but it seems that `kustomize edit add annotation` will not modify an existing annotation:

```
Error: annotation deployTimestamp already in kustomization file
```

Could this behavior be changed? Or maybe I should approach this differently?

**Comment by 2opremio** [comment]
@Liujingfang1 Is a `--force` flag still acceptable? I may find the time to create a PR.

Derailing a bit, I have always found the distinction of `edit add` and `edit set` really inconvenient for automation. My expected behavior would be _add it if it doesn't exist and and edit it if it does_. In that way I would expect a `--force` flag for other commands like `edit set image` too.
