### ISSUE TITLE
Feature request: load remote resources

### ISSUE THREAD

**Issue by yujunz** [kubernetes-sigs/kustomize#580]
How do I customize resources based on non-kustomize content, e.g.

https://github.com/awslabs/aws-service-operator/blob/master/configs/

It would be nice if we can support remote `resources` similar to remote `bases`

**Comment by Liujingfang1** [comment]
We thought about this when we developed the remote support in kustomize and decided not to support it. The reason is that the resources and patches are better to be in the relative path files rather than a remote link. You could either fork the awslabs into your own repo and make it a remote base or copy the file content to a  local file.

**Comment by yujunz** [comment]
Understood. Thanks @Liujingfang1
