### ISSUE TITLE
Support variables in istio host resources

### ISSUE THREAD

**Issue by rkr-kununu** [kubernetes-sigs/kustomize#685]
Since istio is being integrated into [gcloud](https://thenewstack.io/google-integrates-istio-service-mesh-into-kubernetes-service/) and other k8s solutions.  It would be very helpful to permit host name variable solutions to istio.

This is related to #267 

This may not be an exhaustive list, but the various istio resources that would benefit from this would be:
```
- kind: VirtualService
  path: spec/hosts
- kind: Gateway
  path: spec/servers/hosts
```

**Comment by kunickiaj** [comment]
Sad to see this go dead. Have had yaml sprawl dealing with this in kustomize so far, that we're reconsidering template based alternatives.

**Comment by rkr-kununu** [comment]
Actually since kustomize supports defining variables with [any custom resource](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md#adding-a-custom-resource).  We were able to integrate istio very easily.

```
$ cat config/istio.yaml 
varReference:
# VirtualService support
- path: spec/hosts
  kind: VirtualService
  apiVersion: networking.istio.io/v1alpha3

# Gateway support
- path: spec/servers/port/name
  apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
- path: spec/servers/hosts
  apiVersion: networking.istio.io/v1alpha3
  kind: Gateway
```

**Comment by kunickiaj** [comment]
Not quite what I was looking for. I'm trying to find a way to reduce the boilerplate maintenance for different envs -- the spec/host field of a DestinationRule holds the FQDN of the service, so that includes the namespace. I could not figure out how to use a nameReference to _set_ the spec/host field of the DestinationRule based on the namespace from kustomization.yaml.

Thus, most Istio resource end up duplicated with just a different namespace in the host field across environments. Or is that in line with kustomize's philosophy?

Having a git branch per env is appealing, as it allows us to merge or cherry pick changes to envs and deploy on push. I'm trying to see how that would work here, aside from creating a git repo per environment.
