### ISSUE TITLE
patchesStrategicMerge for non-kubernetes resources

### ISSUE THREAD

**Issue by johnhny** [kubernetes-sigs/kustomize#742]
Hi everybody 👋

I'm curious how to use Kustomize patchesStrategicMerge to patch **non-kubernetes resources**.

I created a tiny example project, to demonstrate the issue:
https://github.com/johnhny/kustomize-patch-non-k8s

1. A k8s deployment with a patch that should MERGE into the original deployment.yml
2. A non-k8s resource ("bee") with a patch that should MERGE into the original bee.yml

When you run and compare these two configurations like:
``` bash
diff <(kustomize build bee) <(kustomize build deployment)
```
... you will notice, that Kustomize/patchesStrategicMerge **is not merging but replacing** the original tree in the bee.yml:
![image](https://user-images.githubusercontent.com/25933511/51914299-d41ba380-23d8-11e9-9770-432b5eac14cf.png)
For the k8s-deployment patch, all works like expected 👍 

Can you give us a hint, how we can get this to work in the same way for a non-k8s resource?

Thank you,
Arno

**Comment by Liujingfang1** [comment]
`patchesStrategicMerge` treats the patch as a strategic merge patch when corresponding resource is native in Kubernetes. If a kind is not found, such as a custom resource, the patch is treated as json merge patch. The JSON patch will replace the whole tree as @johnhny observed. To keep the volumes under spec, you also need to add them in the patch.

Here is some background related to this. Strategic merge patch doesn't work for custom resources since the metadata needed by this kind of patch is missing in the custom resources. https://github.com/kubernetes/kubernetes/pull/53558
