### ISSUE TITLE
Implement Kustomization file versioning policy

### ISSUE THREAD

**Issue by monopole** [kubernetes-sigs/kustomize#747]
As defined in resolution to #746

**Comment by AndresPineros** [comment]
I'm not sure if this is the place to ask, but I want to know if this solves the problem I have with Kustomize.

Currently I realized that Helm is overkill because templating should be used for complex deployments only, not your everyday application deployment. Simple deployments can be handled easily with plain Kubernetes files, but reutilization is still something attractive. Basically this is what Kustomize puts in the table.

The only problem I have with Kustomize right now is that the "base" is not versioned. Let's say I have three environments (overlays): dev, stg, prod. And let's also assume my "base" is in the state A. If I move my base forward to a state B those changes will be applied to all the overlays. What if I only want to apply state B of the base to dev and stg but not yet to production, basically, I want the production overlay to keep using the state A of the base.

Is the "version policy" the solution for this problem?
Is this something that is already solved by Kustomize?

This is something Helm solves because each version of the Chart is versioned in a Charts repository or using git URLs. It would be awesome if Kustomize allowed having a "base" repository and specifying a "base" version for each overlay. It is extra work but it is 100% optional for workflows.

Thank you very much
