### ISSUE TITLE
The command edit --from-file=key=path  fails

### ISSUE THREAD

**Issue by ant31** [kubernetes-sigs/kustomize#778]
The following command fails: 
```
$ kustomize edit add configmap config --from-file=my-key=my-configmap.yaml               
2019/02/07 16:06:08 my-key=my-configmap.yaml has no match
Error: at least from-env-file, or from-file or from-literal must be set
```
but works if I remove 'my-key='

**Comment by Liujingfang1** [comment]
The error is from this function https://github.com/kubernetes-sigs/kustomize/blob/master/pkg/commands/edit/add/util.go#L28

When `--from-file=my-key=my-configmap.yaml` is used, `my-key=my-configmap.yaml` is passed down to this function to check the existence of the file. The fix is to remove `my-key=` when calling this function.
