### ISSUE TITLE
two kustomize files share some resource files

### ISSUE THREAD

**Issue by figo** [kubernetes-sigs/kustomize#794]
before kustomize 2.0 version, it is possible to have 2 kustomize files refer to same resource file

for example
folder1/kustomize_1.yaml
```
resources:
- ../example/example.yaml
```
folder2/kustomize_2.yaml
```
resources:
- ../example/example.yaml
```

now with kustomize 2.0, it is restricting `../`, it becomes impossible to have 
two kustomizes sharing same resource file.

one possible solution for this is:
add option to specify kustomize file name at `kustomize build`

for example:
```
kustomize build --kustomizefile kustomize_1.yaml
kustomize build --kustomizefile kustomize_1.yaml
```

is it possible to add such an option? and is there workaround now?
thanks

**Comment by Liujingfang1** [comment]
@figo Kustomize doesn't provide this option since we want to encourage the best practices of storing the entire configurations in a version control system. To see more details of the explanation, please go [here](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#build-time-side-effects-from-cli-args-or-env-variables). 

You can create a base kustomization with resource `example/exampl.yaml`. Then in folder1 and folder2 kustomization files, instead of listing `example.yaml` as a resource, list the base containing it.

**Comment by figo** [comment]
@Liujingfang1 thank you, i think it going to work with `bases`, if i understand it correctly, now, `bases` is means for shared resources, and `resources` is for local resources. correct?

**Comment by Liujingfang1** [comment]
@figo Yes.

**Comment by monopole** [comment]
@figo yes, use a shared base - it can be a relative path.

This is how we, for example, [share](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/helloWorld/README.md) common config between a dev, staging and production instance.

 thanks!
