### ISSUE TITLE
Name conflict reusing base with different name prefixes

### ISSUE THREAD

**Issue by jcassee** [kubernetes-sigs/kustomize#800]
I have a kustomization that uses two levels of overlays combining a common component such that when I run `kustomize build` I get the following error:
```
Error: detected conflicts when resolving name references postgres:
[noGroup_v1_PersistentVolumeClaim|noNamespace|overlay-:base2-|postgres noGroup_v1_PersistentVolumeClaim|noNamespace|overlay-:base1-|postgres]
```

Because the setup is difficult to describe in words I have attached a ZIP containing the test case:
[pvc-nameprefix-problem.zip](https://github.com/kubernetes-sigs/kustomize/files/2884966/pvc-nameprefix-problem.zip)

It seems that the common top-level name prefix seems to confuse the lower-level name reference resolution.

**Comment by Liujingfang1** [comment]
I'll look into this. It is probably caused by how kustomize finds matching objects.

**Comment by mildred** [comment]
Basically, the tree structure is like:

```.
├── base1
│   ├── base
│   │   └── kustomization.yaml
│   └── overlay
│       └── kustomization.yaml
├── base2
│   ├── base
│   │   └── kustomization.yaml
│   └── overlay
│       └── kustomization.yaml
├── kustomization.yaml
└── postgres
    ├── kustomization.yaml
    └── resources.yaml
```

The root module depends on `base1/overlay` and `base2/overlay` which themselves depends upon `base[12]/base` which depends upon `postgres`. The kustomization in `base[12]/*` is adding a name prefix (adding `overlay-` for `base[12]/overlay` and `base[12]` for `base[12]/base`).

I suppose the goal of this kustomization is to deploy two instances of postgresql deployments and PVC.

- The first instance should be named `overlay-base1-postgresql` (through base1/overlay and base1/base)
- The second instance should be named `overlay-base2-postgresql`

The error is: *Error: Multiple matches for name ~G_v1_PersistentVolumeClaim|~X|overlay-:base1-|postgres|~S:
  [~G_v1_PersistentVolumeClaim|~X|overlay-:base1-|postgres|~S ~G_v1_PersistentVolumeClaim|~X|overlay-:base2-|postgres|~S]*

I don't really understand that cryptic message, but I suppose that kustomize is considering that because both instances have the sane namePrefix (`overlay-`) and the same non-kustomized name (`postgres`), they run into a name conflict. However, there is between another prefix added that removes the ambiguity (`base1-`/`base2-`)

It seems to me an important feature to work properly in kustomize at it allows proper dependency management (unlike helm that bundle everything in a giant template).

**Comment by mildred** [comment]
The error is generated here:
https://github.com/kubernetes-sigs/kustomize/blob/e8eed838b5d16ecce7750e806fd9f544ed848ed3/pkg/transformers/namereference.go#L98

**Comment by mildred** [comment]
The comment above is incorrect:

```go
matchedIds := m.GetMatchingIds(id.GvknEquals)
// If there's more than one match, there's no way 
// to know which one to pick, so emit error. 
```

`id.GvknEquals` is only checking that the name without the prefixes and suffixes is equal:

```go
// GvknEquals returns true if the other id matches
// Group/Version/Kind/name.
func (n ResId) GvknEquals(id ResId) bool {
```

But here, we can compare with the prefix and suffix, and even perhaps the namespace.

I would create the following function to check the prefix and suffix as well:

```go
// GvknEquals returns true if the other id matches
// Group/Version/Kind/name/prefix/suffix.
func (n ResId) GvknPsEquals(id ResId) bool {
	return n.ItemId.Prefix == id.ItemId.Prefix && n.ItemId.Suffix == id.ItemId.Suffix && n.GvknEquals(id)
}
```

And use it in matching:

```go
matchedIds := m.GetMatchingIds(id.GvknPsEquals) 
```

**Comment by mildred** [comment]
Or perhaps even `GvknEquals` should be transformed to test equal prefix and suffix as the prefix and suffix is going to be included in the name after all.

**Comment by mildred** [comment]
The same change should happen at:

https://github.com/kubernetes-sigs/kustomize/blob/e8eed838b5d16ecce7750e806fd9f544ed848ed3/pkg/transformers/namereference.go#L120

**Comment by monopole** [comment]
Can someone write a test documenting this behavior in the model of PR #1278 ?

It takes about as much work as writing the commentary above, but the test is unambiguous and we automatically get test coverage.
https://github.com/kubernetes-sigs/kustomize/blob/master/docs/bugs.md
We need help!

**Comment by jbrette** [comment]
@jcassee @mildred Can you retest.  [This environment](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0800)  which replicates your files, indicates that the issue has been fixed since kusstomize 3.1.0.

**Comment by jcassee** [comment]
@jbrette Indeed, the current master has no problem with this kustomization.

@monopole I'll try and create a PR with this kustomization as a test case.

**Comment by jcassee** [comment]
Thanks @jbrette!
