### ISSUE TITLE
Allow using kustomize as HELM plugin

### ISSUE THREAD

**Issue by AssafKatz3** [kubernetes-sigs/kustomize#88]
We have use case of a lot of production environment (we manage with HELM) and one development environment which requires overlay (open debug port for example) and strictly must not be used in production. Therefore I suggest to allow kustomize to be used as [HELM downloader plugin](https://github.com/kubernetes/helm/blob/master/docs/plugins.md#downloader-plugins) so it will be possible to pass the chart through kustomize before it will be used in development environment.

**Comment by monopole** [comment]
What prevents it?

**Comment by AssafKatz3** [comment]
@monopole The problems that you mentioned and the requirement to handle zip files

**Comment by monopole** [comment]
Helm downloader plugins are used to grab charts, which aren't k8s API objects.  They are Go templates.  Kustomize will never read Go templates.

The problem susgests using  kustomize in a _post_-helm step, not as a HELM chart downloader plugin.

Helm has a flag that lets one emit a processed chart (a template expanded into viable k8s API objects) to disk rather than sending it into tiller.

kustomize could then read that, edit it and spit it to stdout.
