### ISSUE TITLE
personal access tokens and github enterprise (GHE)

### ISSUE THREAD

**Issue by objectiveous** [kubernetes-sigs/kustomize#944]
Please consider supporting github enterprise and github's personal access tokens.

**Comment by richardmarshall** [comment]
To confirm, you're hoping for a way to use the method described here: https://github.blog/2012-09-21-easier-builds-and-deployments-using-git-over-https-and-oauth/, to authenticate git fetches of remote resources without having to hard code the token into the kustomization file?

Based on how that seems to work we could probably generalize this to "supporting http basic auth for git resources". Since other SCM providers have similar ways of providing API token auth for git clones over HTTPS it would be good to ensure an implementation will work for them as well.

/kind feature

**Comment by matt-smith** [comment]
a small workaround is to run `git config --global url."https://${GITHUB_TOKEN}@mygithub.com/".insteadOf "https://mygithub.com/"` prior to running the `kustomize build`. Works well in CI if you trash the workspace after each run

**Comment by marco2704** [comment]
@matt-smith Wound not that workaround fail with special characters? 🤔
