### ISSUE TITLE
Hello World Example outdated

### ISSUE THREAD

**Issue by kellerkind84** [kubernetes-sigs/kustomize#969]
The Hello World example seems to be outdated. The file tree suggested leads to an error, it only works when base and overlay folders are neighbors.

**Comment by monopole** [comment]
True, the tree shown does have the base and overlay folders as siblings, but this is intentional and  doesn't result in an error.  This and all examples are run as part of the pre-commit test.

One could use another arrangement, but that would require changing the relative paths in the base references in the kustomization files under the overlays directory.  Right now they read
```
bases:
- ../../base
```
which is correct for this particular arrangement.

Thanks for the report, please reopen if i've misunderstood this comment.
